// Inkwoven -- the 24 gems: six per colour with tiers 1, 1, 2, 2, 3, 3.
//
// One IIFE that registers into DATA.gems (no top-level names). Data only: gem text is generated by DATA.gemText from `mod`, except
// the one gem whose four-way effect reads better by hand (`text`). Tests: tests/rogue_book_treasure.test.mjs (validator, quotas,
// the power ladder, and every gem played on cards of every type, both rows, and through a real combat).
//
// HOW A GEM WORKS (DESIGN 4.6, DATA.resolveCard). A slot takes a gem of its own colour, a prism slot takes any. `dmg`, `block` and
// `heal` add N to EVERY matching op on the card (per hit, ops inside cond and repeat and ops other gems appended included, hook
// bodies excluded); `hits` adds to the first top level dmg op; `cost` is a signed delta and tier 3 only (ignored on X and 0 cost
// cards); `draw`, `energy`, `status`, `poison`, `fx` are APPENDED to the end of the card's ops in slot order; `kw` adds and
// `kwRemove` removes keywords; `cond` gates the whole gem on the owner's row. A gem with nothing to apply to is shown grey.
//
// COLOUR IDENTITY (why each colour is what it is, and where it is safe to socket)
//   RED   offence. Lives in slots of cards that have a dmg op. Flat damage, extra hits, a life-stealing rider, a front-row power
//         gem, and at tier 3 a card that also splashes the whole line. The flat keys (`dmg`, `hits`) do nothing on a card
//         without a dmg op, which is exactly why the slot rules only put red on attacks.
//   BLUE  defence. Lives on cards with Block, heal or a hero status. Flat Block, Thorns, Dodge, healing and, at tier 3, Block for
//         the ally. Appended `status` and `fx` work on any card; the flat `block` key needs a Block op.
//   GREEN utility. Works on ANY card: no flat damage, Block or heal keys, only draw, Retain, cost, Energy and pick effects.
//   GOLD  wild. Works on ANY card: status seeds (Might, Ritual, Dodge), gold and Ink on play, a resource amplifier, and a
//         back row gem that draws and dodges. No flat keys either.
//
// THE POWER LADDER (rough "damage equivalents" per play of the card, see the model in the test): tier 1 is a solid small bonus
// worth about 2.5 to 5, tier 2 is a real upgrade worth about 5 to 10, tier 3 changes what the card is for: a strike becomes a
// sweep, a Block skill becomes a Thorns engine, any card gets cheaper or pays Energy back, an ordinary card starts a Ritual.
//
// TARGETING. Appended ops with `tgt:'enemy'` make an area card ask for a target, and `tgt:'all'` never does; the one enemy op that
// could be either (Bloodmoon Carnelian's life steal) is written `enemy` on purpose: it is a single bite and it should land on the
// enemy you chose. Sunfall Ruby hits `all`, so it is safe on an area card.
//
// LOCKED (Library unlocks, never tier 1): Bloodmoon Carnelian, Springwell Tanzanite (tier 2); Kirin Jasper, Sanctum Iolite,
// Wellspring Tourmaline, Dusklight Amber (tier 3). Each colour keeps an unlocked tier 2 and tier 3 gem so every gem cache and
// event that asks for a colour or a tier can always answer.
(() => {
  const gems = {
    // ------------------------------------------------------------------ RED: offence
    ember_ruby: {
      name: 'Ember Ruby', color: 'red', tier: 1, art: { cut: 'round' },
      mod: { dmg: 2 },
    },
    vanguard_garnet: {
      name: 'Vanguard Garnet', color: 'red', tier: 1, art: { cut: 'square' },
      mod: { cond: 'front', dmg: 3 },
    },
    twinfang_spinel: {
      name: 'Twinfang Spinel', color: 'red', tier: 2, art: { cut: 'oval' },
      mod: { hits: 1 },
    },
    bloodmoon_carnelian: {
      name: 'Bloodmoon Carnelian', color: 'red', tier: 2, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'dmg', n: 4, tgt: 'enemy', lifesteal: true }] },
    },
    sunfall_ruby: {
      name: 'Sunfall Ruby', color: 'red', tier: 3, art: { cut: 'star' },
      mod: { fx: [{ op: 'dmg', n: 6, tgt: 'all' }] },
    },
    kirin_jasper: {
      name: 'Kirin Jasper', color: 'red', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { cond: 'front', hits: 1, dmg: 2 },
    },

    // ------------------------------------------------------------------ BLUE: defence
    tidewatch_sapphire: {
      name: 'Tidewatch Sapphire', color: 'blue', tier: 1, art: { cut: 'round' },
      mod: { block: 3 },
    },
    thornwake_lapis: {
      name: 'Thornwake Lapis', color: 'blue', tier: 1, art: { cut: 'oval' },
      mod: { status: { s: 'thorns', n: 1, tgt: 'self' } },
    },
    mirrorlake_aquamarine: {
      name: 'Mirrorlake Aquamarine', color: 'blue', tier: 2, art: { cut: 'square' },
      mod: { block: 2, status: { s: 'dodge', n: 1, tgt: 'self' } },
    },
    springwell_tanzanite: {
      name: 'Springwell Tanzanite', color: 'blue', tier: 2, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'heal', n: 2, tgt: 'both' }] },
    },
    ironbark_sapphire: {
      name: 'Ironbark Sapphire', color: 'blue', tier: 3, art: { cut: 'star' },
      mod: { block: 2, status: { s: 'thorns', n: 3, tgt: 'self' } },
    },
    sanctum_iolite: {
      name: 'Sanctum Iolite', color: 'blue', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'block', n: 8, tgt: 'ally' }] },
    },

    // ------------------------------------------------------------------ GREEN: utility (works on any card)
    quickthought_emerald: {
      name: 'Quickthought Emerald', color: 'green', tier: 1, art: { cut: 'round' },
      mod: { draw: 1 },
    },
    keepsake_peridot: {
      name: 'Keepsake Peridot', color: 'green', tier: 1, art: { cut: 'oval' },
      mod: { kw: ['retain'] },
    },
    evergreen_jade: {
      name: 'Evergreen Jade', color: 'green', tier: 2, art: { cut: 'square' },
      mod: { draw: 1, kwRemove: ['exhaust'] },
    },
    scholars_malachite: {
      name: 'Scholar\'s Malachite', color: 'green', tier: 2, art: { cut: 'drop' },
      mod: { fx: [{ op: 'pick', from: 'discard', n: 1, then: 'toHand' }] },
    },
    featherlight_emerald: {
      name: 'Featherlight Emerald', color: 'green', tier: 3, art: { cut: 'star' },
      mod: { cost: -1 },
    },
    wellspring_tourmaline: {
      name: 'Wellspring Tourmaline', color: 'green', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { energy: 1 },
    },

    // ------------------------------------------------------------------ GOLD: wild (works on any card)
    sunwake_topaz: {
      name: 'Sunwake Topaz', color: 'gold', tier: 1, art: { cut: 'round' },
      mod: { status: { s: 'might', n: 1, tgt: 'self' } },
    },
    coinluck_citrine: {
      name: 'Coinluck Citrine', color: 'gold', tier: 1, art: { cut: 'oval' },
      mod: { fx: [{ op: 'gold', n: 4 }] },
    },
    inkwell_amber: {
      name: 'Inkwell Amber', color: 'gold', tier: 2, art: { cut: 'square' },
      mod: { fx: [{ op: 'ink', n: 1 }, { op: 'gold', n: 3 }] },
    },
    heartflame_topaz: {
      // Four conditions read badly, so this one carries its own text. A hero only ever holds the resource of their own
      // (Bloom, Sumi, Ward or Charge), so exactly one of the four ops can fire, and only once that resource is above zero.
      name: 'Heartflame Topaz', color: 'gold', tier: 2, art: { cut: 'drop' },
      text: 'If you hold Bloom, Sumi, Ward or Charge, gain 2 more of it.',
      mod: {
        fx: [
          { op: 'cond', if: { status: { s: 'bloom' } }, then: [{ op: 'status', s: 'bloom', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'sumi' } }, then: [{ op: 'status', s: 'sumi', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'ward' } }, then: [{ op: 'status', s: 'ward', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'charge' } }, then: [{ op: 'status', s: 'charge', n: 2, tgt: 'self' }] },
        ],
      },
    },
    solstice_citrine: {
      name: 'Solstice Citrine', color: 'gold', tier: 3, art: { cut: 'star' },
      mod: { status: { s: 'ritual', n: 1, tgt: 'self' } },
    },
    dusklight_amber: {
      name: 'Dusklight Amber', color: 'gold', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { cond: 'back', draw: 2, status: { s: 'dodge', n: 1, tgt: 'self' } },
    },
  };

  DATA.add('gems', gems);
})();
