import * as E from './engine.mjs';
import {HEROES,CARDS,RELICS,GEMS,TALENTS,CHAPTERS,cardStats,describe} from './data.mjs';
import {Sound} from './audio.mjs';
const $=q=>document.querySelector(q),app=$('#app'),modal=$('#modal-root'),sound=new Sound();
const KEY='inkbound.run.v1',META='inkbound.meta.v1',SETTINGS='inkbound.settings.v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d;}catch{return d;}};
let meta=read(META,{pages:0,wins:0,runs:0,wealth:0,vitality:0,maxLevel:0}),settings=read(SETTINGS,{sound:true,music:true,motion:true});
sound.enabled=settings.sound;sound.music=settings.music;document.body.classList.toggle('reduced-motion',!settings.motion);
let saved;try{saved=localStorage.getItem(KEY);}catch{}let run=saved?E.restore(saved):null,screen='home',pair=['akari','ren'],selected=null,paintMode=false,busy=false,deckMode='all',socketGem=null,modalView=null,hoverNode=null;
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{if(run)localStorage.setItem(KEY,E.serialize(run));localStorage.setItem(META,JSON.stringify(meta));localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{toast('Browser storage is unavailable. Keep this tab open to preserve your run.');}}
const icons={sword:'M5 19 19 5m-9 0h9v9M4 14l6 6m-7 1 3-3',shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6Z',heart:'M12 20 4 12C-2 4 7 0 12 7c5-7 14-3 8 5Z',brush:'m8 15 10-12 3 3L10 17M8 15c-6-1-1 7-6 7 6 0 10-1 8-5Z',ink:'M12 2s-7 9-7 14a7 7 0 0 0 14 0c0-5-7-14-7-14Z',coin:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-8-5v10m3-8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9',gem:'m3 8 4-5h10l4 5-9 13Zm0 0h18M7 3l5 18 5-18',star:'m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1Z',moon:'M19 16A9 9 0 0 1 8 3a9 9 0 1 0 11 13Z',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16',cards:'m8 3 13 2-3 17-13-2ZM5 4 2 7l2 13',camp:'m12 3 10 17H2ZM12 3v17m-5 0 5-8 5 8',shop:'M3 9V4h18v5M2 9h20M4 9v12h16V9m-11 4h6v8',chest:'M3 10V6q9-7 18 0v14H3Zm0 0h18M10 8h4v5h-4Z',feather:'M4 21 17 5M8 17C-1 7 14-2 21 3c2 9-3 20-13 14Z',leaf:'M4 20 17 7M5 18C-2 6 12 2 21 3c0 10-3 22-16 15Z',bell:'M5 17h14l-2-4V8a5 5 0 0 0-10 0v5Zm5 3h4',lantern:'M8 5h8l3 5v8H5v-8Zm0 0V2h8v3M8 21h8m-4-13v10',swap:'M3 7h17l-4-4m5 14H4l4 4',book:'M12 5C8 1 2 3 2 3v17s6-2 10 2c4-4 10-2 10-2V3s-6-2-10 2Zm0 0v17',close:'m5 5 14 14M5 19 19 5',menu:'M4 6h16M4 12h16M4 18h16',arrow:'M4 12h16m-6-6 6 6-6 6',check:'m4 12 5 5L20 6',question:'M9 8a4 4 0 1 1 6 3q-3 1-3 4m0 3v1',skull:'M5 15a9 9 0 1 1 14 0v6H5ZM8 11v2m8-2v2m-7 4v4m6-4v4',flame:'M13 2c2 8 8 8 6 15-3 8-15 5-14-3 0-4 4-6 4-9 3 2 3 5 3 5Z',sound:'M3 9h4l5-5v16l-5-5H3Zm13-3q8 6 0 12m-1-8q3 2 0 4',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8Zm0-6v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2'};
function icon(n,cls=''){return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.star}"/></svg>`;}
const btn=(label,action,cls='',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const sprite=(kind,i,cls='')=>`<div class="sprite ${kind} ${cls}" style="--sx:${kind==='heroes'?(i%2)*100:(i%3)*50}%;--sy:${kind==='heroes'?Math.floor(i/2)*100:Math.floor(i/3)*100}%" aria-hidden="true"></div>`;
function particles(){return `<div class="petals" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i style="--x:${(i*31)%100}%;--d:${8+i%6}s;--delay:-${i*1.7}s"></i>`).join('')}</div>`;}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function effects(kind,x=innerWidth*.6,y=innerHeight*.45,text=''){if(!settings.motion)return;let root=$('#effects');root.innerHTML=`<div class="burst ${kind}" style="left:${x}px;top:${y}px">${Array.from({length:12},(_,i)=>`<i style="--angle:${i*30}deg;--distance:${40+(i%4)*20}px"></i>`).join('')}<b>${esc(text)}</b></div>`;clearTimeout(effects.timer);effects.timer=setTimeout(()=>{root.innerHTML='';},1100);if(kind==='hit')app.classList.add('shake');setTimeout(()=>app.classList.remove('shake'),300);}
function hp(h){return `<div class="health"><i style="width:${h.hp/h.maxHp*100}%"></i><span>${h.hp} / ${h.maxHp}</span></div>`;}
function record(){if(run&&!run.recorded&&['victory','defeat'].includes(run.phase)){run.recorded=true;meta.pages+=run.pages;meta.runs++;if(run.phase==='victory'){meta.wins++;meta.maxLevel=Math.max(meta.maxLevel,run.level+1);}persist();}}
function render(){record();if(screen==='home')renderHome();else if(screen==='select')renderSelect();else renderGame();if(run)persist();}
function renderHome(){app.innerHTML=`<main class="home scene">${particles()}<header class="home-header"><span class="brand-small">${icon('moon')} A ROXORLOOPS GAME</span><button class="icon-btn" data-action="settings" aria-label="Settings">${icon('settings')}</button></header><div class="home-copy"><div class="eyebrow"><span></span> A ROGUELIKE WRITTEN IN INK</div><h1>INK<span>BOUND</span></h1><div class="title-rule"><i></i><p>THE PAINTED ECLIPSE</p><i></i></div><p class="home-tagline">Two souls. One unwritten world.</p><p class="home-desc">Gather your cards. Paint a path through the unknown.<br>Rewrite the ending the darkness chose for you.</p><div class="home-actions">${run&&!['victory','defeat'].includes(run.phase)?btn(`${icon('arrow')} Continue your story`,'continue','primary'):btn(`${icon('brush')} Begin your story`,'new','primary')}${run?btn('New expedition','new','quiet'):''}${btn(`${icon('book')} How to play`,'help','quiet')}</div><div class="home-bottom"><button data-action="legacy">${icon('star')} <b>${meta.pages}</b> memory pages <span>View legacy →</span></button><small>FOUR HEROES &nbsp; · &nbsp; THREE CHAPTERS &nbsp; · &nbsp; INFINITE STORIES</small></div></div><div class="home-characters">${sprite('heroes',1,'home-ren')}${sprite('heroes',0,'home-akari')}<div class="home-seal">${icon('moon')}<span>I · III</span></div></div><footer class="home-footer"><span>THE WORLD IS WAITING FOR YOUR FIRST BRUSHSTROKE</span><span>Headphones recommended ${icon('sound')}</span></footer></main>`;}
function renderSelect(){app.innerHTML=`<main class="selection scene">${particles()}<header>${btn('← Return','home','quiet')}<span class="brand-small">INKBOUND</span>${btn(icon('question'),'help','quiet','aria-label="How to play"')}</header><div class="section-heading"><div class="eyebrow">EVERY STORY BEGINS WITH TWO</div><h1>Choose your kindred souls</h1><p>Two heroes. One shared deck. A bond that changes everything.</p></div><div class="hero-picker">${HEROES.map(h=>`<button class="hero-choice ${pair.includes(h.id)?'chosen':''}" data-action="pick" data-id="${h.id}" style="--hero-color:${h.color}"><span class="pick-order">${pair.includes(h.id)?String(pair.indexOf(h.id)+1).padStart(2,'0'):'+'}</span>${sprite('heroes',h.art)}<div class="hero-choice-info"><div class="eyebrow">${h.title}</div><h2>${h.name}</h2><p>${h.story}</p><div class="passive">${icon('star')}${h.passive}</div><span class="hero-hp">${icon('heart')}${h.hp} health</span></div></button>`).join('')}</div><div class="selection-bottom"><label>Expedition <select id="difficulty">${Array.from({length:Math.min(21,meta.maxLevel+1)},(_,i)=>`<option value="${i}">${i?'Eclipse '+i:'The first brushstroke'}</option>`).join('')}</select></label><p>${pair.map(id=>HEROES.find(h=>h.id===id).name).join(' + ')} <span>· ${pair.length}/2 selected</span></p>${btn(`Open the atlas ${icon('arrow')}`,'start','primary',pair.length!==2?'disabled':'')}</div></main>`;}
function topbar(){return `<header class="game-header"><button class="wordmark" data-action="pause">INKBOUND<span>THE PAINTED ECLIPSE</span></button><div class="chapter-indicator"><span>CHAPTER ${['I','II','III'][run.chapter]}</span><b>${CHAPTERS[run.chapter].name}</b></div><div class="resources"><span title="Gold">${icon('coin')}<b>${run.gold}</b></span><span title="Brushes">${icon('brush')}<b>${run.brushes}</b></span><span title="Moon ink">${icon('ink')}<b>${run.ink}</b></span></div><div class="header-actions"><button class="icon-btn" data-action="deck" aria-label="Open deck">${icon('cards')}<small>${run.deck.length}</small></button><button class="icon-btn ${E.talentAvailable(run)?'notify':''}" data-action="talents" aria-label="Talents">${icon('star')}</button><button class="icon-btn" data-action="pause" aria-label="Pause">${icon('menu')}</button></div></header>`;}
function party(){return `<div class="party">${run.heroes.map((h,i)=>{let def=HEROES.find(x=>x.id===h.id);return `<div class="party-card" style="--hero-color:${def.color}"><div class="portrait">${sprite('heroes',def.art)}</div><div><div class="party-name"><b>${def.name}</b><span>${i===run.front?'VANGUARD':'SUPPORT'}</span></div>${hp(h)}<small>${def.title}</small></div></div>`;}).join('')}</div>`;}
function relicBar(){return `<div class="relic-bar"><span>RELICS</span>${run.relics.map(id=>{let r=RELICS.find(r=>r.id===id);return `<button data-action="relic" data-id="${id}" title="${r.name}: ${r.text}">${icon(r.icon)}</button>`;}).join('')}</div>`;}
const typeIcon={battle:'sword',elite:'skull',boss:'moon',shop:'shop',camp:'camp',treasure:'chest',gem:'gem',event:'question',ink:'ink',gold:'coin',start:'lantern'};
const typeName={battle:'Inkbound encounter',elite:'Elite encounter',boss:'Chapter guardian',shop:'Wandering merchant',camp:'Quiet sanctuary',treasure:'Forgotten relic',gem:'Gemstone',event:'An unwritten story',ink:'Ink supplies',gold:'Lost gold',start:'First light',empty:'Quiet passage'};
function hex(n){let x=48+n.x*76+(n.y%2)*38,y=50+n.y*65;return {x,y,points:Array.from({length:6},(_,i)=>{let a=(i*60-30)*Math.PI/180;return `${x+42*Math.cos(a)},${y+42*Math.sin(a)}`;}).join(' ')};}
function mapSVG(){return `<svg class="atlas" viewBox="0 0 770 500" aria-label="Exploration map"> <defs><radialGradient id="tile"><stop stop-color="#4b7770"/><stop offset="1" stop-color="#213f44"/></radialGradient><radialGradient id="fog"><stop stop-color="#24313b"/><stop offset="1" stop-color="#17222c"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="3"/></filter></defs>${run.map.map(n=>{let p=hex(n),current=n.id===run.position,reach=E.reachable(run,n.id),active=n.seen&&!n.done&&n.type!=='empty',label=n.seen?typeName[n.type]:'Unpainted land';return `<g class="hex ${n.seen?'seen':'fog'} ${n.done?'visited':''} ${active?'landmark':''} ${current?'current':''} ${reach?'reachable':''} ${paintMode&&!n.seen&&E.distance(run.map[run.position],n)<=4?'paintable':''}" data-node="${n.id}" role="button" tabindex="0" aria-label="${label}${current?', your position':''}" transform="translate(0 0)"><title>${label}${n.seen&&!reach?' · Path blocked by an encounter':''}</title><polygon points="${p.points}"/>${n.seen?`<g transform="translate(${p.x},${p.y})">${n.type==='empty'?`<path class="terrain" d="M-20 15-8-7 3 10 12-3 25 15ZM-4-12l5-7 5 9"/>`: `<g class="node-symbol" transform="translate(-12,-15)"><path d="${icons[typeIcon[n.type]]||icons.star}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g>`}${active?`<circle class="node-ring" r="26" cy="-3"/>`:''}${n.done&&!current&&n.type!=='empty'?`<path class="done-tick" d="m15 15 3 3 6-7"/>`:''}${current?`<circle class="position-glow" r="24" fill="none"/><path class="player-pin" d="m0-13 9 13-9 13-9-13Z"/><circle r="3" fill="#fff7d9"/>`:''}${n.type==='boss'?`<text class="boss-label" y="33">GUARDIAN</text>`:''}</g>`:`<text class="fog-mark" x="${p.x}" y="${p.y+5}" text-anchor="middle">${paintMode?'+':'·'}</text>`}</g>`;}).join('')}</svg>`;}
function mapScreen(){return `<div class="map-layout"><section class="atlas-section"><div class="atlas-heading"><div><div class="eyebrow">THE LIVING ATLAS</div><h1>${CHAPTERS[run.chapter].name}</h1><p>${CHAPTERS[run.chapter].subtitle}</p></div><div class="compass">N<span>✧</span></div></div><div class="map-container">${mapSVG()}<div class="map-coordinates">${String(run.map.filter(n=>n.seen).length).padStart(2,'0')} / 63 TILES REVEALED</div></div><div class="map-tools"><div class="tool-group">${btn(`${icon('brush')} Brush <b>${run.brushes}</b>`,'brush','tool',run.brushes?'':'disabled')}${btn(`${icon('ink')} Moon ink <b>${run.ink}</b>`,'ink',`tool ${paintMode?'active':''}`,run.ink?'':'disabled')}</div><p>${paintMode?'Choose an unpainted tile within 4 hexes.':'Move across painted land. Brush reveals nearby hexes.'}</p></div><div class="legend"><span>${icon('sword')} Encounter</span><span>${icon('camp')} Sanctuary</span><span>${icon('shop')} Merchant</span><span>${icon('question')} Story</span><span>${icon('gem')} Gem</span></div></section><aside class="journal"><div class="journal-label">YOUR EXPEDITION <span>0${run.chapter+1}</span></div><div class="objective"><span class="eyebrow">THE CHAPTER GUARDIAN</span><h2>${CHAPTERS[run.chapter].boss}</h2><p>${run.fights>=3?'The seal has broken. Reach the eclipse to challenge the guardian.':'Defeat three encounters to break the seal. Explore to strengthen your deck.'}</p><div class="seals">${[0,1,2].map(i=>`<span class="${run.fights>i?'lit':''}">${icon(run.fights>i?'check':'sword')}</span>`).join('')}<b>${Math.min(3,run.fights)} / 3</b></div></div>${party()}${relicBar()}<div class="journal-note">${icon('feather')}<p>${esc(run.log[0]||'“A world is only a story waiting for someone brave enough to begin.”')}</p></div>${E.talentAvailable(run)?btn(`${icon('star')} A new talent awaits`,'talents','primary small'):''}</aside></div>`;}
function cardHTML(card,action='card',extra=''){let c=cardStats(card),h=HEROES.find(h=>h.id===c.hero),locked=run?.phase==='combat'&&(c.cost>run.battle.energy||run.heroes.find(h=>h.id===c.hero)?.hp<=0);return `<button class="card ${c.rarity} ${card.up?'upgraded':''} ${selected===card.uid?'selected':''} ${locked?'unplayable':''}" data-action="${action}" data-uid="${card.uid}" style="--hero-color:${h.color}" ${extra}><span class="card-cost">${c.cost}</span><div class="card-art" style="background-position:${(c.art%4)*100/3}% ${Math.floor(c.art/4)*50}%"></div><div class="card-title">${c.name}${card.up?' +':''}</div><span class="card-type">${h.name} · ${c.damage?'ATTACK':c.ally||c.power?'POWER':'SKILL'}</span><div class="card-desc">${describe(c)}</div><div class="card-foot"><span>${c.rarity.toUpperCase()}</span><span class="sockets">${[0,1].map(i=>`<i style="${card.gems[i]?'background:'+GEMS.find(g=>g.id===card.gems[i]).color:''}"></i>`).join('')}</span></div></button>`;}
function status(unit){return `<div class="status-row">${[['block','shield'],['power','sword'],['poison','leaf'],['bleed','ink'],['weak','feather'],['vulnerable','gem'],['thorns','star']].filter(([k])=>unit[k]>0).map(([k,ico])=>`<span class="status ${k}" title="${k}: ${unit[k]}">${icon(ico)}${unit[k]}</span>`).join('')}</div>`;}
function combatScreen(){const b=run.battle,card=b.hand.find(c=>c.uid===selected),c=card&&cardStats(card);return `<section class="combat"><div class="combat-heading"><div><div class="eyebrow">${b.type==='boss'?'CHAPTER GUARDIAN':b.type==='elite'?'ELITE ENCOUNTER':'THE INK COMES ALIVE'}</div><h2>${b.type==='boss'?CHAPTERS[run.chapter].boss:'A story worth fighting for'}</h2></div><span class="turn-label">TURN <b>${String(b.turn).padStart(2,'0')}</b></span></div><div class="battle-stage ${selected?'targeting':''}"><div class="battle-party">${[1-run.front,run.front].map((idx,j)=>{let h=run.heroes[idx],def=HEROES.find(x=>x.id===h.id);return `<div class="fighter hero-fighter ${j?'front':'back'} ${h.hp<=0?'fallen':''}" data-hero="${h.id}"><div class="fighter-info"><span class="role-label">${j?'VANGUARD':'SUPPORT'}</span><h3>${def.name}</h3>${hp(h)}${status(h)}</div>${sprite('heroes',def.art,'idle')}<div class="ground-shadow"></div></div>`;}).join('')}</div><div class="vs-seal">${icon('moon')}</div><div class="battle-enemies">${b.enemies.filter(e=>e.hp>0).map(e=>`<button class="fighter enemy-fighter ${e.boss?'boss':''} ${selected?'targetable':''}" data-action="enemy" data-id="${e.uid}" aria-label="Target ${e.name}"><div class="intent ${E.intent(run,e).type}">${icon(E.intent(run,e).type==='guard'?'shield':E.intent(run,e).type==='buff'?'star':'sword')} ${E.intent(run,e).label}</div>${sprite('enemies',e.art,'idle')}<div class="ground-shadow"></div><div class="enemy-info"><h3>${e.name}</h3>${hp(e)}${status(e)}</div></button>`).join('')}</div></div><div class="combat-command"><button class="swap-btn" data-action="swap" ${b.swapUsed||run.heroes.some(h=>h.hp===0)?'disabled':''}>${icon('swap')} Switch heroes <small>${b.swapUsed?'USED':'FREE · ONCE PER TURN'}</small></button><div class="combat-hint">${c?`${esc(c.name)} · ${E.targetRequired(c)?'Choose an enemy':describe(c)}`:b.ally?`Spirit companions deal ${b.ally} damage at end of turn.`:'Select a card. Read enemy intentions. Protect your vanguard.'}</div>${selected?btn('Cancel','cancel','quiet'):''}</div><div class="hand-zone"><div class="energy-column"><div class="energy-orb"><b>${b.energy}</b><span>ENERGY</span></div><button class="pile" data-action="draw">${icon('cards')} ${b.draw.length}<small>DRAW</small></button></div><div class="hand">${b.hand.map(card=>cardHTML(card)).join('')}</div><div class="end-column">${btn(`End turn ${icon('arrow')}`,'end','primary end-turn',busy?'disabled':'')}<button class="pile" data-action="discard">${icon('cards')} ${b.discard.length}<small>DISCARD · ${b.exhaust.length} EXHAUSTED</small></button></div></div></section>`;}
function encounterScreen(){let p=run.phase;if(p==='reward')return `<section class="encounter reward"><div class="reward-emblem">${icon('sword')}</div><div class="eyebrow">THE PAGE IS YOURS</div><h1>A new verse of power</h1><p>Choose a card to weave into your shared deck.</p><div class="reward-loot"><span>${icon('coin')} +${run.reward.gold} gold</span><span>${icon('brush')} +1 brush</span>${run.reward.relic?`<span>${icon('star')} ${run.reward.relic}</span>`:''}${run.reward.type==='boss'?`<span>${icon('gem')} +1 gemstone</span>`:''}</div><div class="card-offers">${run.reward.cards.map(c=>cardHTML(c,'reward')).join('')}</div>${btn('Leave the cards behind →','skip','quiet')}<p class="subtle">${Math.max(0,4-((run.deck.length-10)%4))} more cards until your next talent</p></section>`;
if(p==='shop')return `<section class="encounter shop"><div class="eyebrow">THE WANDERING MERCHANT</div><h1>Something for the journey?</h1><p>“Every treasure has a price. Every story has a buyer.”</p><div class="shop-grid">${run.shop.cards.map((c,i)=>`<div>${cardHTML(c,'inspect')} ${btn(`${icon('coin')} ${E.price(run,65)} · Acquire`,'buy','small',`data-kind="card" data-index="${i}" ${run.shop.bought.includes('card'+i)||run.gold<E.price(run,65)?'disabled':''}`)}</div>`).join('')}<div class="shop-items">${[['relic',run.shop.relic&&RELICS.find(r=>r.id===run.shop.relic),115,'star'],['gem',GEMS.find(g=>g.id===run.shop.gem),50,'gem'],['heal',{name:'Warm tea',text:'Heal both heroes for 18.'},35,'heart'],['brush',{name:'Fresh pigments',text:'Gain 2 brushes.'},30,'brush']].filter(x=>x[1]).map(([kind,item,cost,ico])=>`<button class="shop-item" data-action="buy" data-kind="${kind}" ${run.shop.bought.includes(kind+'0')||run.gold<E.price(run,cost)?'disabled':''}>${icon(ico)}<span><b>${item.name}</b><small>${item.text}</small></span><em>${E.price(run,cost)} ${icon('coin')}</em></button>`).join('')}</div></div>${btn('Return to the atlas →','leave','primary')}</section>`;
if(p==='event')return `<section class="encounter story"><div class="story-emblem">${icon('feather')}</div><div class="eyebrow">AN UNWRITTEN STORY</div><h1>${run.event.name}</h1><p class="story-copy">${run.event.text}</p><div class="choices">${run.event.options.map((o,i)=>`<button data-action="event" data-index="${i}" ${run.gold<(o.cost||0)?'disabled':''}><b>${o.name}</b><span>${o.text}</span>${icon('arrow')}</button>`).join('')}</div></section>`;
if(p==='camp')return `<section class="encounter story"><div class="story-emblem">${icon('camp')}</div><div class="eyebrow">A QUIET SANCTUARY</div><h1>Even heroes need a moment</h1><p class="story-copy">The lantern is warm. The night, for once, is kind.</p><div class="choices">${[['rest','Rest by the lantern','Restore 30% of your highest maximum health to both heroes.'],['upgrade','Hone your craft','Permanently upgrade one card.'],['brush','Mix fresh pigments','Gain 3 brushes to explore further.']].map(([id,name,text])=>`<button data-action="camp" data-id="${id}"><b>${name}</b><span>${text}</span>${icon('arrow')}</button>`).join('')}</div></section>`;
if(p==='discovery')return `<section class="encounter story"><div class="story-emblem">${icon(run.discovery.kind==='gem'?'gem':'chest')}</div><div class="eyebrow">SOMETHING LOST. SOMETHING FOUND.</div><h1>${run.discovery.title}</h1><p class="story-copy">${run.discovery.text}</p>${btn('Carry it with you →','leave','primary')}</section>`;
if(p==='chapter')return `<section class="encounter chapter-screen"><div class="eyebrow">CHAPTER ${['I','II','III'][run.chapter]}</div><h1>${CHAPTERS[run.chapter].name}</h1><p>${CHAPTERS[run.chapter].subtitle}</p><p class="story-copy">The atlas turns a page. Your wounds mend, your inks replenish.<br>Somewhere beyond the mist, another guardian wakes.</p>${btn('Paint the next chapter →','chapter','primary')}</section>`;
if(p==='victory'||p==='defeat')return `<section class="encounter ending"><div class="story-emblem">${icon(p==='victory'?'moon':'feather')}</div><div class="eyebrow">${p==='victory'?'THE ENDING IS YOURS':'NO STORY IS EVER TRULY LOST'}</div><h1>${p==='victory'?'You rewrote the dawn.':'The ink remembers you.'}</h1><p class="story-copy">${p==='victory'?'The eclipse breaks. For the first time, the world has a tomorrow.':'Your story ends here. But its echoes will strengthen the next.'}</p><div class="run-stats"><div><b>${run.totalFights}</b><span>VICTORIES</span></div><div><b>${run.stats.damage}</b><span>DAMAGE DEALT</span></div><div><b>${run.deck.length}</b><span>CARDS WOVEN</span></div><div><b>+${run.pages}</b><span>MEMORY PAGES</span></div></div><div class="ending-actions">${btn('Begin another story','new','primary')}${btn('Spend memory pages','legacy','quiet')}${btn('Title screen','home','quiet')}</div></section>`;
return '';}
function renderGame(){if(!run){screen='home';return render();}app.innerHTML=`<main class="game scene chapter-${run.chapter} ${run.phase==='combat'?'in-combat':''}">${particles()}${topbar()}${run.phase==='map'?mapScreen():run.phase==='combat'?combatScreen():encounterScreen()}<footer class="game-footer"><span>${icon('moon')} ECLIPSE ${run.level} <i>·</i> ${run.phase==='combat'?'THE SHARED DECK':`SEED ${run.seed}`}</span><span class="save-label">${icon('check')} Auto-saved</span><button data-action="help">Field guide ${icon('question')}</button></footer></main>`;}
function openModal(title,body,cls=''){modalView=title;modal.innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><div><div class="eyebrow">INKBOUND · FIELD NOTES</div><h2>${title}</h2></div><button class="icon-btn" data-action="close" aria-label="Close dialog">${icon('close')}</button></header><div class="modal-content">${body}</div></section></div>`;modal.querySelector('button')?.focus();}
function closeModal(){modal.innerHTML='';modalView=null;socketGem=null;}
function help(){openModal('The art of a good story',`<div class="guide-grid">${[['brush','Paint your path','Tap revealed hexes to travel. Encounters block paths until defeated. A brush reveals a radius of two around you. Moon ink reveals a chosen tile within four hexes and its neighbors. The visible main road always leads to the boss.'],['sword','Fight as one','Your heroes share a deck and 3 energy each turn. Select a card, then an enemy for attacks. Skills play immediately. The vanguard takes enemy attacks. You may switch positions once per turn for free. Block is personal and resets at the start of your next turn.'],['cards','Build your bond','Draw 5 cards each turn. Unplayed cards are discarded; an empty draw pile reshuffles the discard. Exhausted cards return next battle. Cards belong to a hero: fallen heroes cannot play theirs. Win to revive a fallen hero at 25% health.'],['gem','Make every card yours','Find gems and open your deck to socket them. Each card has two permanent slots. Rest sites offer healing, a card upgrade, or brushes. Every 4 cards added beyond the starting 10 unlocks a talent.'],['moon','Break the eclipse','Win 3 fights to unlock each guardian. Complete all three chapters to win. Your run saves after every action. Memory pages earned at run end buy permanent health and gold upgrades. Winning unlocks harder Eclipse levels.'],['leaf','Know your effects','Poison and bleed hurt enemies before their actions, ignoring block; then lose 1 stack. Weak reduces damage by 25%; vulnerable raises damage taken by 50%. Power adds attack damage. Thorns retaliate. Summons attack at end of turn.']].map(([ico,title,body])=>`<article>${icon(ico)}<h3>${title}</h3><p>${body}</p></article>`).join('')}</div><div class="key-guide">KEYBOARD <kbd>1–9</kbd> Select card <kbd>E</kbd> End turn <kbd>S</kbd> Switch <kbd>B</kbd> Brush <kbd>D</kbd> Deck <kbd>Esc</kbd> Cancel / pause</div>`,'wide');}
function deck(view='all',upgrade=false){deckMode=view;let cards=view==='all'?run.deck:run.battle[view]||[];openModal(upgrade?'Hone a card':view==='all'?'Your shared deck':`${view[0].toUpperCase()+view.slice(1)} pile`,`${!upgrade&&view==='all'?`<div class="gem-inventory"><div><b>${run.gems.length} gemstones</b><p>Choose a gem, then a card. Two permanent sockets per card.</p></div>${run.gems.map((id,i)=>{let g=GEMS.find(x=>x.id===id);return `<button class="gem-chip ${socketGem===id?'active':''}" style="--gem-color:${g.color}" data-action="gem-select" data-id="${id}" title="${g.text}">${icon('gem')}${g.name}</button>`;}).join('')}${run.phase==='combat'?'<small>Socket gems between battles.</small>':''}</div>`:''}<div class="deck-grid">${cards.map(c=>cardHTML(c,upgrade?'upgrade':socketGem?'socket':'inspect',upgrade&&c.up?'disabled':'')).join('')||'<p>This pile is empty.</p>'}</div>`,'wide');}
function talents(){openModal('A bond beyond the page',`<p class="modal-intro">Your deck has ${run.deck.length} cards. Gain one talent for every 4 cards beyond the starting 10.</p><div class="talent-grid">${TALENTS.map(t=>`<button class="talent ${run.talents.includes(t.id)?'owned':''}" data-action="learn" data-id="${t.id}" ${!E.talentAvailable(run)||run.talents.includes(t.id)?'disabled':''}>${icon(run.talents.includes(t.id)?'check':'star')}<b>${t.name}</b><p>${t.text}</p><small>${run.talents.includes(t.id)?'LEARNED':E.talentAvailable(run)?'CHOOSE THIS TALENT':'GROW YOUR DECK TO UNLOCK'}</small></button>`).join('')}</div>`);}
function legacy(){openModal('Stories become strength',`<p class="modal-intro">Your journeys have left <b>${meta.pages} memory pages</b>. These upgrades carry into every new expedition.</p><div class="legacy-grid">${[['vitality','Living parchment','Each hero starts with +4 maximum health per level.','heart'],['wealth','Golden beginnings','Start with +15 gold per level.','coin']].map(([id,name,text,ico])=>`<article>${icon(ico)}<h3>${name}</h3><p>${text}</p><span>LEVEL ${meta[id]} / 5</span>${btn(meta[id]>=5?'Mastered':`${(meta[id]+1)*15} pages · Upgrade`,'meta','primary small',`data-id="${id}" ${meta[id]>=5||meta.pages<(meta[id]+1)*15?'disabled':''}`)}</article>`).join('')}</div><p class="subtle">${meta.runs} expeditions completed · ${meta.wins} eclipses broken</p>`);}
function settingsModal(){openModal('Make yourself at home',`<div class="settings-list">${[['sound','Sound effects'],['music','Ambient soundtrack'],['motion','Animations & particles']].map(([id,label])=>`<button data-action="setting" data-id="${id}"><span>${label}</span><b class="toggle ${settings[id]?'on':''}">${settings[id]?'ON':'OFF'}</b></button>`).join('')}</div><p class="subtle">Original synthesized ambient music. Your settings and expedition are saved on this device.</p>`);}
function pause(){openModal('A moment between pages',`<div class="pause-actions">${btn('Return to your story','close','primary')}${btn('Field guide','help')}${btn('Settings','settings')}${btn('Save & title screen','save-home','quiet')}${btn('Abandon this expedition','abandon','danger')}</div>`);}
function perform(fn,kind='click'){let success=fn();if(success===false)return false;sound.play(kind);selected=null;render();return true;}
function playCard(uid,target){const card=run.battle.hand.find(c=>c.uid===uid);if(!card)return;const c=cardStats(card),enemy=run.battle.enemies.find(e=>e.uid===target),old=enemy?.hp;let el=target?document.querySelector(`[data-action="enemy"][data-id="${target}"]`):document.querySelector(`[data-hero="${c.hero}"]`),rect=el?.getBoundingClientRect();if(perform(()=>E.play(run,uid,target),c.damage?'hit':'guard')){effects(c.damage?'hit':'guard',rect?rect.x+rect.width/2:innerWidth/2,rect?rect.y+rect.height/2:innerHeight/2,c.damage&&enemy?'-'+(old-enemy.hp):c.block?'+'+c.block:'✧');if(run.phase==='combat'){document.querySelector(`[data-hero="${c.hero}"]`)?.classList.add(c.damage?'striking':'casting');if(target)document.querySelector(`[data-action="enemy"][data-id="${target}"]`)?.classList.add('struck');setTimeout(()=>document.querySelectorAll('.striking,.casting,.struck').forEach(el=>el.classList.remove('striking','casting','struck')),500);}if(run.phase==='reward')sound.play('reward');}else toast('Not enough energy, or this hero has fallen.');}
document.addEventListener('click',event=>{const node=event.target.closest('[data-node]');if(node&&screen==='game'&&run.phase==='map'){sound.init();const id=+node.dataset.node;if(paintMode){if(perform(()=>E.paint(run,'ink',id),'paint')){paintMode=false;render();}else toast('Choose unpainted land within four hexes.');}else{const oldLog=run.log[0];if(!perform(()=>E.visit(run,id)))toast(run.log[0]!==oldLog?run.log[0]:'Reveal a connected path to travel here.');}return;}
 const el=event.target.closest('[data-action]');if(!el||el.disabled||busy)return;const a=el.dataset.action,id=el.dataset.id,uid=+el.dataset.uid,index=+(el.dataset.index||0);sound.init();
 if(a==='close'){closeModal();return;}if(a==='help'){help();return;}if(a==='settings'){settingsModal();return;}if(a==='legacy'){legacy();return;}if(a==='setting'){settings[id]=!settings[id];sound.enabled=settings.sound;sound.music=settings.music;document.body.classList.toggle('reduced-motion',!settings.motion);persist();settingsModal();return;}
 if(a==='meta'){let cost=(meta[id]+1)*15;if(meta.pages>=cost&&meta[id]<5){meta.pages-=cost;meta[id]++;persist();legacy();}return;}
 if(a==='home'||a==='save-home'){closeModal();screen='home';render();return;}
 if(a==='continue'){screen='game';render();return;}
 if(a==='new'){if(run&&!['victory','defeat'].includes(run.phase)){openModal('Start a new story?',`<p>Your current expedition will end. You keep ${run.pages} earned memory pages.</p><div class="pause-actions">${btn('Begin a new expedition','confirm-new','primary')}${btn('Keep playing','close','quiet')}</div>`);}else{closeModal();screen='select';render();}return;}
 if(a==='confirm-new'||a==='abandon-confirm'){if(run&&!run.recorded){run.phase='defeat';record();}closeModal();screen=a==='confirm-new'?'select':'home';render();return;}
 if(a==='abandon'){openModal('Close this chapter?',`<p>End this run and keep ${run.pages} earned memory pages?</p>${btn('End expedition','abandon-confirm','danger')}${btn('Keep playing','close','quiet')}`);return;}
 if(a==='pick'){if(pair.includes(id))pair=pair.filter(x=>x!==id);else if(pair.length<2)pair.push(id);else pair=[pair[1],id];sound.play('click');render();return;}
 if(a==='start'){if(pair.length!==2)return;run=E.newRun(pair,Date.now()%1000000000,+$('#difficulty').value,meta);screen='game';sound.play('paint');render();if(!meta.runs)toast('Begin on the lantern. Tap a painted hex to explore.');return;}
 if(!run)return;
 if(a==='pause'){pause();return;}if(a==='deck'){socketGem=null;deck();return;}if(a==='draw'||a==='discard'){deck(a);return;}if(a==='talents'){talents();return;}
 if(a==='learn'){if(E.learn(run,id)){sound.play('reward');render();talents();}return;}
 if(a==='relic'){const r=RELICS.find(x=>x.id===id);openModal(r.name,`<div class="relic-detail">${icon(r.icon)}<p>${r.text}</p></div>`);return;}
 if(a==='brush'){if(!perform(()=>E.paint(run,'brush'),'paint'))toast('Move closer to unpainted land before using a brush.');return;}
 if(a==='ink'){paintMode=!paintMode;render();return;}
 if(a==='card'){let card=run.battle.hand.find(c=>c.uid===uid);if(!card)return;let c=cardStats(card);if(c.cost>run.battle.energy){toast('You need more energy for that card.');return;}if(E.targetRequired(c)){selected=selected===uid?null:uid;render();}else playCard(uid);return;}
 if(a==='enemy'){if(selected)playCard(selected,+id);else toast('Select an attack card first.');return;}
 if(a==='cancel'){selected=null;render();return;}
 if(a==='swap'){perform(()=>E.swap(run),'guard');return;}
 if(a==='end'){selected=null;busy=true;app.classList.add('enemy-turn');sound.play('turn');toast('The enemy takes its turn…');setTimeout(()=>{E.endTurn(run);busy=false;app.classList.remove('enemy-turn');render();if(run.phase==='reward')sound.play('reward');if(run.phase==='defeat')sound.play('defeat');},settings.motion?700:0);return;}
 if(a==='reward'||a==='skip'){perform(()=>E.takeReward(run,a==='reward'?uid:null),'reward');return;}
 if(a==='chapter'){run.phase='map';render();sound.play('paint');return;}
 if(a==='leave'){E.closeEncounter(run);render();return;}
 if(a==='event'){perform(()=>E.eventChoice(run,index),'reward');return;}
 if(a==='camp'){if(id==='upgrade')deck('all',true);else perform(()=>E.camp(run,id),'reward');return;}
 if(a==='upgrade'){if(E.camp(run,'upgrade',uid)){closeModal();render();sound.play('reward');}return;}
 if(a==='buy'){if(perform(()=>E.buy(run,el.dataset.kind,index),'reward'))toast('A fine choice.');return;}
 if(a==='gem-select'){if(run.phase==='combat'){toast('Socket gems between battles.');return;}socketGem=socketGem===id?null:id;deck();return;}
 if(a==='socket'){if(E.socket(run,uid,socketGem)){sound.play('reward');toast('Gem permanently socketed.');socketGem=null;persist();deck();}else toast('That card already has two gems.');return;}
 if(a==='inspect'){let card=run.deck.find(c=>c.uid===uid)||run.shop?.cards.find(c=>c.uid===uid);if(card){const c=cardStats(card);toast(c.name+': '+describe(c));}return;}
});
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='Tab'&&modalView){const focusable=[...modal.querySelectorAll('button:not([disabled]),[tabindex="0"]')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(e.key==='Escape'){if(modalView)closeModal();else if(selected){selected=null;render();}else if(screen==='game')pause();return;}if(e.key==='Enter'&&e.target.dataset.node){e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));return;}if(modalView||busy||screen!=='game')return;const a={e:'end',s:'swap',b:'brush',d:'deck'}[e.key.toLowerCase()];if(a)document.querySelector(`[data-action="${a}"]`)?.click();if(/^[1-9]$/.test(e.key)&&run.phase==='combat')document.querySelectorAll('.hand .card')[+e.key-1]?.click();});
window.addEventListener('pagehide',persist);
// A read-only snapshot is useful for automated accessibility and run verification.
window.inkbound={getState:()=>run?structuredClone(run):null};
render();
