/* ============================================================================
   build.mjs — cut the two typefaces and embed them in the game.

     node tools/beastfont/build.mjs            # rebuild + rewrite the @font-face
     node tools/beastfont/build.mjs --check    # fail if what is embedded is stale
     node tools/beastfont/build.mjs --specimen # also write a page to look at

   The fonts are WOFF, base64'd straight into birds_and_beasts/index.html. That
   file is one self-contained document by design — no external resources — and a
   web font is the one thing that would quietly break that rule, so it goes in
   the same way everything else does: inline.

   Two families, three files:
     BEASTCUT  — the display face. One weight, already black; declared across
                 the whole 100-900 range so no browser ever synthesises a bold
                 on top of a face that is already as heavy as it gets.
     BEAKWORK  — the text face, regular + bold, cut from the same skeleton with
                 a heavier metric bundle rather than smeared by the renderer.
   ========================================================================== */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildFace, smallCaps } from './alphabet.mjs';
import { buildFont, glyph } from './sfnt.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const GAME = join(REPO, 'birds_and_beasts', 'index.html');
const SPEC = join(REPO, 'birds_and_beasts', 'fonts.html');
const EM = 1000;

/* ------------------------------------------------------------- the faces --- */

// BEASTCUT — condensed, black, chiselled. The superellipse at 0.64 is what
// flattens every bowl; the chamfer knocks the corners off the stems so the
// letters read as cut plate rather than as extruded type.
export const BEASTCUT = {
  cap: 720, asc: 780, desc: -190,
  st: 150, th: 124, e: 0.64, ch: 42, ov: 12,
  wf: 0.94, side: 30, N: 12,
  cA: 46, sT: 0.575, sB: 0.595, sA0: -14,
};
// Its small caps: shorter, wider, and proportionally FATTER, so a mixed-case
// title keeps one even colour instead of going pale where the lowercase is.
export const BEASTCUT_SC = {
  ...BEASTCUT, cap: 540, st: 128, th: 108, ch: 34, ov: 10, wf: 1.06, side: 28,
};

// BEAKWORK — the text face. Tall x-height, open apertures, low contrast, and
// terminals that stop dead: it has to survive a 10px uppercase label with 2.6px
// of tracking, which is most of this game's chrome.
export const BEAKWORK = {
  cap: 700, xh: 516, asc: 742, desc: -206,
  st: 86, th: 79, e: 0.80, ch: 0, ov: 11,
  wf: 1.0, side: 48, N: 14,
  cA: 38, cAl: 34, sT: 0.585, sB: 0.61, sA0: -12,
};
export const BEAKWORK_BOLD = {
  ...BEAKWORK, st: 142, th: 126, wf: 1.035, side: 44, ov: 12,
};

/* ------------------------------------------------------------- assembly --- */
function notdef(adv, cap) {
  const m = Math.round(cap * 0.10);
  return glyph('.notdef', 0, adv,
    [[[m, 0], [adv - m, 0], [adv - m, cap], [m, cap]]],
    [[[m * 2, m * 2], [adv - m * 2, m * 2], [adv - m * 2, cap - m * 2], [m * 2, cap - m * 2]]]);
}

function makeFont(map, spec) {
  const chars = Object.keys(map).sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
  const space = map[' '];
  const glyphs = [notdef(Math.round(space.adv * 1.4), spec.capHeight)];
  for (const ch of chars) {
    const gl = map[ch];
    glyphs.push(glyph(ch, ch.codePointAt(0), gl.adv, gl.pos, gl.cut));
  }
  glyphs.push(glyph('nbsp', 0x00a0, space.adv, [], []));   // never a visible gap
  return buildFont({ ...spec, unitsPerEm: EM, glyphs });
}

function names(family, style, ver) {
  const full = style === 'Regular' ? family : `${family} ${style}`;
  return [
    [0, 'Drawn for The Birds & The Beasts. Generated by tools/beastfont.'],
    [1, family], [2, style], [3, `${full}:beastfont`], [4, full],
    [5, `Version ${ver}`], [6, full.replace(/[^A-Za-z0-9]/g, '')],
    [8, 'The Birds & The Beasts'], [11, 'https://games-71g.pages.dev/birds_and_beasts/'],
  ];
}

export function cutFonts() {
  const display = { ...buildFace(BEASTCUT), ...smallCaps(BEASTCUT_SC) };
  const text = buildFace(BEAKWORK);
  const bold = buildFace(BEAKWORK_BOLD);

  return [
    {
      id: 'beastcut', family: 'Beastcut', style: 'Regular', weight: 400,
      font: makeFont(display, {
        ascender: 800, descender: -220, lineGap: 0,
        capHeight: BEASTCUT.cap, xHeight: BEASTCUT_SC.cap, weight: 400,
        names: names('Beastcut', 'Regular', '1.000'),
      }),
    },
    {
      id: 'beakwork', family: 'Beakwork', style: 'Regular', weight: 400,
      font: makeFont(text, {
        ascender: 800, descender: -220, lineGap: 0,
        capHeight: BEAKWORK.cap, xHeight: BEAKWORK.xh, weight: 400,
        names: names('Beakwork', 'Regular', '1.000'),
      }),
    },
    {
      id: 'beakwork-bold', family: 'Beakwork', style: 'Bold', weight: 700,
      font: makeFont(bold, {
        ascender: 800, descender: -220, lineGap: 0,
        capHeight: BEAKWORK_BOLD.cap, xHeight: BEAKWORK_BOLD.xh, weight: 700,
        names: names('Beakwork', 'Bold', '1.000'),
      }),
    },
  ];
}

/* --------------------------------------------------------------- embed --- */
const BEGIN = '/* BEASTFONT:BEGIN — generated by tools/beastfont/build.mjs, do not hand-edit */';
const END = '/* BEASTFONT:END */';

export function faceBlock(cut) {
  const face = (c, family, weight, style) =>
    `  @font-face{ font-family:'${family}'; font-style:${style}; font-weight:${weight};\n` +
    `    src:url(data:font/woff;base64,${c.font.woff.toString('base64')}) format('woff'); font-display:block; }`;
  const [d, r, b] = cut;
  return [
    BEGIN,
    face(d, 'Beastcut', '100 900', 'normal'),
    face(r, 'Beakwork', '400', 'normal'),
    face(b, 'Beakwork', '700 900', 'normal'),
    END,
  ].join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const cut = cutFonts();
  const block = faceBlock(cut);

  // The game keeps its own hand-written CSS around the block, so it is spliced.
  // The specimen page is generated whole — it exists only to show the faces off
  // and to hand the .woff files out, so there is nothing in it to preserve.
  const src = readFileSync(GAME, 'utf8');
  const i = src.indexOf(BEGIN), j = src.indexOf(END);
  if (i < 0 || j < 0) {
    console.error('beastfont: no BEASTFONT:BEGIN/END markers in birds_and_beasts/index.html');
    process.exit(1);
  }
  const page = specimen(block);

  if (check) {
    let stale = false;
    if (src.slice(i, j + END.length) !== block) { console.error('beastfont: index.html is STALE'); stale = true; }
    if (readFileSync(SPEC, 'utf8') !== page) { console.error('beastfont: fonts.html is STALE'); stale = true; }
    if (stale) { console.error('beastfont: run `node tools/beastfont/build.mjs`'); process.exit(1); }
    console.log('beastfont: embedded fonts match source ✓');
  } else {
    writeFileSync(GAME, src.slice(0, i) + block + src.slice(j + END.length));
    writeFileSync(SPEC, page);
    const kb = (n) => (n / 1024).toFixed(1) + 'kB';
    for (const c of cut) console.log(`  ${c.family} ${c.style}: ${kb(c.font.ttf.length)} ttf → ${kb(c.font.woff.length)} woff`);
    console.log(`beastfont: embedded ${kb(block.length)} into the game and into fonts.html`);
  }

  if (args.includes('--woff')) {
    const out = join(HERE, 'out');
    mkdirSync(out, { recursive: true });
    for (const c of cut) writeFileSync(join(out, c.id + '.woff'), c.font.woff);
    console.log('beastfont: wrote tools/beastfont/out/*.woff');
  }
}

function specimen(block) {
  const F = (c) => `<span>${c === '&' ? '&amp;' : c === '<' ? '&lt;' : c}</span>`;
  const grid = [...'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789&@#%()[]{}!?.,:;'];
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Beastcut &amp; Beakwork — the type of The Birds &amp; The Beasts</title>
<style>
${block}
  :root{ --bg:#0b120c; --ink:#e9f3df; --dim:#8fa285; --lime:#a6ff5e; --pink:#ff8ad4; --rule:#1e2c1a; }
  *{ box-sizing:border-box; }
  body{ background:
      radial-gradient(1100px 620px at 50% -12%, rgba(130,210,95,.11), transparent 70%),
      radial-gradient(760px 520px at 92% 112%, rgba(255,120,190,.075), transparent 70%), var(--bg);
    color:var(--ink); margin:0; padding:34px 26px 90px; font-family:'Beakwork',system-ui,sans-serif;
    font-size:15px; line-height:1.5; }
  main{ max-width:900px; margin:0 auto; }
  .d{ font-family:'Beastcut',system-ui,sans-serif; }
  .row{ border-top:1px solid var(--rule); padding:26px 0 22px; }
  .row:first-of-type{ border-top:none; padding-top:0; }
  .lab{ font-family:'Beastcut',sans-serif; font-size:11px; letter-spacing:2.6px;
    text-transform:uppercase; color:#6f8465; margin-bottom:14px; }
  .hero{ font-size:clamp(38px,10vw,84px); line-height:1.0; color:var(--lime);
    letter-spacing:-.5px; text-shadow:0 0 26px rgba(150,255,90,.28), 0 3px 0 #33591a; }
  .hero em{ font-style:normal; color:var(--pink); text-shadow:0 0 26px rgba(255,130,200,.32), 0 3px 0 #7d2f5c; }
  .lede{ color:#cfe0c2; max-width:56ch; }
  .big{ font-size:clamp(26px,5.4vw,44px); line-height:1.15; }
  .mid{ font-size:24px; } .sm{ font-size:15px; } .xs{ font-size:11px; letter-spacing:2.6px; text-transform:uppercase; color:var(--dim); }
  .btnish{ display:inline-block; font-family:'Beastcut',sans-serif; font-size:15px; letter-spacing:1.6px;
    text-transform:uppercase; color:#12210c; padding:12px 22px; border-radius:13px; margin:4px 6px 4px 0;
    background:linear-gradient(180deg,#d4ff8c,#a6ee55 45%,#79c634); box-shadow:0 4px 0 #4a7c1e; }
  .grid{ display:grid; grid-template-columns:repeat(auto-fill,minmax(52px,1fr)); gap:5px; }
  .grid span{ background:#111d0f; border:1px solid var(--rule); text-align:center;
    padding:9px 2px; font-size:25px; border-radius:6px; }
  table{ border-collapse:collapse; width:100%; max-width:460px; }
  td{ padding:3px 16px 3px 0; } td.n{ text-align:right; font-family:'Beastcut',sans-serif; }
  .dl a{ display:inline-block; font-family:'Beastcut',sans-serif; font-size:13px; letter-spacing:1.4px;
    text-transform:uppercase; color:#e6f4dc; text-decoration:none; padding:10px 16px; border-radius:10px;
    margin:4px 8px 4px 0; background:linear-gradient(180deg,#3f5340,#2c3c2c 45%,#1e2a1e);
    box-shadow:0 3px 0 #152014; }
  .dl a:hover{ filter:brightness(1.12); }
  footer{ color:#6f8465; font-size:12px; margin-top:26px; }
  footer a{ color:var(--lime); }
</style></head><body><main>

<div class="row">
  <div class="lab">Two faces, drawn for one game</div>
  <div class="hero d">Beastcut<br><em>&amp; Beakwork</em></div>
  <p class="lede" style="margin-top:16px">The type of <b>The Birds &amp; The Beasts</b>. One parametric
  skeleton, two faces: <b>Beastcut</b> is condensed, black and flat-sided, with true small caps in place of a
  lowercase — headings, buttons and any number that is a score. <b>Beakwork</b> is the same bones at a tenth
  of the weight, with a tall x-height and terminals that stop dead — everything that is a sentence.</p>
</div>

<div class="row"><div class="lab">Beastcut — display</div>
  <div class="big d">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>0123456789 &amp; ? ! % @ — →</div>
  <div class="mid d" style="margin-top:12px">The nest holds ten. Feed 24 &amp; brace.</div>
  <div style="margin-top:14px">
    <span class="btnish">Open the door</span><span class="btnish">Keep it</span><span class="btnish">Cull 3</span>
  </div>
</div>

<div class="row"><div class="lab">Beakwork — text</div>
  <div class="mid">Two beasts in, one chick out.</div>
  <p class="lede">The barn is three floors and a nest on top. Post beasts on floors, two per floor, paid from a
  Feed budget; open the door and a wave walks in at the bottom. Whatever climbs off the top eats an egg, and
  <b>the eggs are your health</b>.</p>
  <div class="sm">Resemblance: 62% sire · 38% dam · might 14 · vigor 9 · guile 11</div>
  <div class="xs" style="margin-top:8px">Clutch · Cull · Hall of feathers</div>
</div>

<div class="row"><div class="lab">Tabular figures — a stat column never shifts under itself</div>
  <table>
    <tr><td><b>MIGHT</b></td><td class="n">1,204</td><td class="n">−18</td><td class="n">96%</td></tr>
    <tr><td><b>VIGOR</b></td><td class="n">0,911</td><td class="n">+70</td><td class="n">07%</td></tr>
    <tr><td><b>GUILE</b></td><td class="n">3,388</td><td class="n">×12</td><td class="n">50%</td></tr>
  </table>
</div>

<div class="row"><div class="lab">Beakwork — regular, bold, and the whole set</div>
  <div class="grid">${grid.map(F).join('')}</div>
  <div class="grid d" style="margin-top:10px">${grid.map(F).join('')}</div>
</div>

<div class="row"><div class="lab">Take them</div>
  <p class="lede">WOFF, about 8kB each, no licence to read: they were cut for this game and you can do what
  you like with them. In the game itself they are base64'd into the one HTML file, because it has no external
  resources by design.</p>
  <div class="dl" id="dl"></div>
</div>

<footer>Cut by <code>tools/beastfont</code> in the games repo —
  <a href="./">back to The Birds &amp; The Beasts</a>.</footer>
</main>
<script>
/* The three faces are already in this page as data: URIs inside @font-face.
   Rather than ship a second copy for the download links, pull them back out of
   the stylesheet and hand them over as blobs. */
(function(){
  var css = document.styleSheets[0], seen = {}, out = document.getElementById('dl');
  for (var i = 0; i < css.cssRules.length; i++) {
    var r = css.cssRules[i];
    if (!(r instanceof CSSFontFaceRule)) continue;
    var fam = r.style.getPropertyValue('font-family').replace(/['"]/g, '').trim();
    var wt = (r.style.getPropertyValue('font-weight') || '400').trim();
    // Beastcut is declared across 100-900 (it has one weight and is already
    // black), so the file name comes from the family, not from the number.
    var name = fam === 'Beastcut' ? 'Beastcut.woff'
      : 'Beakwork-' + (/^4/.test(wt) ? 'Regular' : 'Bold') + '.woff';
    if (seen[name]) continue;
    seen[name] = 1;
    var m = /base64,([A-Za-z0-9+/=]+)/.exec(r.style.getPropertyValue('src'));
    if (!m) continue;
    var bin = atob(m[1]), buf = new Uint8Array(bin.length);
    for (var k = 0; k < bin.length; k++) buf[k] = bin.charCodeAt(k);
    var a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([buf], { type: 'font/woff' }));
    a.download = name;
    a.textContent = name.replace('.woff', '') + ' — ' + Math.round(buf.length / 102.4) / 10 + 'kB';
    out.appendChild(a);
  }
})();
</script>
</body></html>
`;
}

if (process.argv[1] && process.argv[1].endsWith('build.mjs')) main();
