const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..');const out=process.env.INKBOUND_SCREENSHOTS||path.resolve(root,'../inkbound-qa');fs.mkdirSync(out,{recursive:true});
const server=require('http').createServer((q,s)=>{let p=path.join(root,decodeURIComponent(q.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';s.setHeader('Content-Type',({'.mjs':'text/javascript','.css':'text/css','.html':'text/html','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');fs.readFile(p,(e,b)=>{s.statusCode=e?404:200;s.end(e?'Not found':b)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/inkbound/`;let launch={headless:true,args:['--no-sandbox','--disable-dev-shm-usage']};if(process.env.CHROMIUM_PATH)launch.executablePath=process.env.CHROMIUM_PATH;const browser=await chromium.launch(launch);const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});await page.goto(url);await page.waitForTimeout(300);await page.addStyleTag({content:'.petals{display:none}*{animation:none!important;transition:none!important}#toast{display:none!important}'});await page.screenshot({path:path.join(out,'title-desktop.png')});await page.click('[data-action="new"]');await page.click('[data-action="start"]');await page.click('[data-action="brush"]');await page.screenshot({path:path.join(out,'atlas-desktop.png')});await page.locator('[data-node="29"]').click();let s=await page.evaluate(()=>inkbound.getState());assert.equal(s.phase,'combat');let turns=0;while(s.phase==='combat'&&turns++<30){for(let cards=0;cards<15;cards++){s=await page.evaluate(()=>inkbound.getState());if(s.phase!=='combat')break;const playable=await page.locator('.hand .card:not(.unplayable)').all();if(!playable.length)break;await playable[0].click();let targets=page.locator('.enemy-fighter.targetable');if(await targets.count())await targets.first().click();}s=await page.evaluate(()=>inkbound.getState());if(s.phase==='combat'){await page.click('[data-action="end"]');await page.waitForTimeout(750);s=await page.evaluate(()=>inkbound.getState());}}
assert.equal(s.phase,'reward','Real clicks can win first battle');await page.screenshot({path:path.join(out,'reward-desktop.png')});await page.locator('[data-action="reward"]').first().click();s=await page.evaluate(()=>inkbound.getState());assert.equal(s.deck.length,11);await page.reload();await page.click('[data-action="continue"]');assert.equal((await page.evaluate(()=>inkbound.getState())).deck.length,11);await page.click('[data-action="deck"]');assert.equal(await page.locator('.deck-grid .card').count(),11);await page.click('[data-action="close"]');
// Seed isolated encounter fixtures through the documented local save format.
const E=await import('../engine.mjs');let fixture=E.newRun(['akari','ren'],777);fixture.phase='shop';fixture.gold=500;fixture.shop={cards:E.cardChoices(fixture),relic:'tea',gem:'ruby',bought:[]};
async function load(state){await page.addInitScript(state=>localStorage.setItem('inkbound.run.v1',JSON.stringify(state)),state);await page.reload();await page.click('[data-action="continue"]');await page.addStyleTag({content:'.petals{display:none}*{animation:none!important;transition:none!important}#toast{display:none!important}'});}
await load(fixture);await page.locator('[data-action="buy"][data-kind="gem"]').click();await page.locator('[data-action="buy"][data-kind="card"]').first().click();assert.equal((await page.evaluate(()=>inkbound.getState())).gold,385);await page.screenshot({path:path.join(out,'shop-desktop.png')});await page.click('[data-action="leave"]');await page.click('[data-action="deck"]');await page.click('[data-action="gem-select"]');await page.locator('[data-action="socket"]').first().click();assert.equal((await page.evaluate(()=>inkbound.getState())).deck[0].gems[0],'ruby');await page.click('[data-action="close"]');
for(const viewport of [{width:390,height:844},{width:360,height:800},{width:844,height:390}]){await page.setViewportSize(viewport);fixture=E.newRun(['akari','ren'],456);await load(fixture);await page.screenshot({path:path.join(out,`atlas-${viewport.width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Map fits '+viewport.width);await page.locator('[data-node="29"]').click();await page.screenshot({path:path.join(out,`combat-${viewport.width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Combat fits '+viewport.width);await page.click('[data-action="deck"]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Deck modal fits '+viewport.width);await page.click('[data-action="close"]');}
assert.deepEqual(errors,[]);console.log('PASS: real combat/reward flow, reload persistence, shop, gem socket, desktop and 3 mobile viewports; zero browser/resource errors.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
