// SITE 9 — a decommissioned missile facility in the high desert, an hour before
// dark.
//
// ── the plan ────────────────────────────────────────────────────────────────
//
// Three zones, three distinct fights, one big loop that connects all of them.
//
//   APPROACH (+Z, south)   The access road in from the perimeter gate. 34 m of
//                          honest sightline down the road, but no straight lane:
//                          two staggered jersey chevrons make you slalom, and
//                          two blast revetments give you leapfrog cover with
//                          embrasures at 1.15–1.65 m to shoot through without
//                          exposing anything below the ribcage. This is the
//                          carbine's room. A shotgun brought here loses.
//
//   PAD (centre)           The apron in front of the bunker, roofed over by the
//                          east–west catwalk. An open cable trench cuts it at
//                          z≈2 — 0.9 m deep, so standing in it puts your eyeline
//                          under the apron and it is the only way to cross the
//                          middle without being seen from the roof. Sightlines
//                          here run 12–20 m: everything works, nothing dominates.
//
//   BUNKER (−Z, north)     A plus of halls with four exterior doors and a blown
//                          east wall. Longest interior sightline is 11 m, broken
//                          in the middle by a half-shut blast door. This is the
//                          shotgun's room and the rifle's nightmare. Two holes in
//                          the roof drop shafts of low sun into it, which is both
//                          the only light in there and a second way in.
//
//   VERTICAL               A steel catwalk at 3.7 m runs 29 m north up the east
//                          side of the site, turns west over the pad, and lands
//                          on the bunker roof at 4.7 m. Three ways up (stair
//                          tower in the approach, caged ladder off the pad, the
//                          roof) so it is a loop and not a perch. The roof
//                          parapet is 1.0 m — crouch cover, and it overlooks the
//                          whole pad, which is exactly the pressure the level
//                          wants on anyone crossing it.
//
// ── landmarks ───────────────────────────────────────────────────────────────
//
// You should never have to open a map. From anywhere on the site at least one of
// these is in view and they are all different shapes:
//
//   • the silo cap, north-east — an octagonal concrete collar with the launcher
//     closure door lying open beside it on its rails
//   • the red-and-white striped service gantry straddling it, 9.5 m
//   • the leaning lattice radio mast on the bunker roof, 19 m and 8° out of true
//   • the floodlight masts, which give the flat apron a ceiling
//
// ── how it is built ─────────────────────────────────────────────────────────
//
// Every visual prop is generated by world/props.js into local-space geometry,
// transformed into place, and dropped into a (chunk × material) bucket. At the
// end each bucket is merged once, so the whole static level is a few dozen
// meshes rather than a few thousand. Collision is authored separately as a much
// coarser box soup — the visual gantry has 40 pieces, the collision has 6.

import * as THREE from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { makeBox, boxFromCenter, buildGrid, queryAABB, groundBelow } from './collision.js';
import { SURFACE } from '../core/constants.js';
import * as PR from './props.js';

const { P, chamferBox, extrude, cyl, sphere, torus, place, xf, prep, mulberry } = PR;

// Site-wide levels. Everything else is measured off these.
const GY = 0.00;        // desert sand
const PY = 0.10;        // poured concrete apron — a 10 cm kerb off the sand
const FY = 0.10;        // bunker floor
const CEIL = 4.00;      // bunker soffit
const ROOF = 4.70;      // bunker roof deck
const DECK = 3.70;      // catwalk deck

const SILO = { x: 19, z: -15, rOut: 7.2, rIn: 5.4, top: 1.15 };

export function buildLevel(G, engine, materials) {
  const group = new THREE.Group();
  group.name = 'level';
  const statics = [];
  const buckets = new Map();      // "chunk|material" → BufferGeometry[]
  const rnd = mulberry(0x51ed);

  // ── material access ────────────────────────────────────────────────────────
  // The materials module is owned elsewhere and is being upgraded in parallel,
  // so this asks for what it needs and adapts. The only thing added on top is
  // vertex colours: the level bakes contact grime and windblown dust into the
  // mesh, which costs nothing and does more for "this has stood here for thirty
  // years" than any amount of extra geometry.
  const matCache = new Map();
  function matFor(name) {
    if (matCache.has(name)) return matCache.get(name);
    let m = materials.get(name);
    if (!m || (name === 'lamp' && !(materials.cache && materials.cache.has('lamp')))) {
      m = new THREE.MeshStandardMaterial({
        color: 0x14100c, emissive: 0xffb24a, emissiveIntensity: 3.2,
        roughness: 0.42, metalness: 0.0,
      });
    } else if (m.vertexColors !== true) {
      m = m.clone();
      m.vertexColors = true;
    }
    matCache.set(name, m);
    return m;
  }

  // ── placement ──────────────────────────────────────────────────────────────
  function chunkOf(x, z) {
    if (Math.abs(x) > 31 || z > 48 || z < -38) return 'edge';
    if (x > 9 && z < -4) return 'silo';
    if (x > -28 && x < 10 && z < -6) return 'bunker';
    if (z > 13) return 'approach';
    return 'pad';
  }

  // Drops one or more local-space parts into their buckets after transforming
  // them into world space. Anything merged this way is static for the run.
  function put(parts, m4, chunk) {
    const list = Array.isArray(parts) ? parts : [parts];
    for (const p of list) {
      const g = p.g ? p.g : p;
      const mat = p.m || m4.__mat || 'concrete';
      if (m4) g.applyMatrix4(m4);
      const key = (chunk || chunkOf(g.attributes.position.array[0] || 0, g.attributes.position.array[2] || 0)) + '|' + mat;
      let arr = buckets.get(key);
      if (!arr) buckets.set(key, arr = []);
      arr.push(prep(g));
    }
  }

  // Convenience for the common case: a bag of raw geometries all of one material.
  function putAll(geos, mat, x, y, z, ry = 0, rx = 0, rz = 0, chunk = null) {
    const m = xf(x, y, z, ry, rx, rz);
    put(geos.map((g) => P(g, mat)), m, chunk || chunkOf(x, z));
  }

  const S = (b) => { statics.push(b); return b; };

  // Visual + collision in one call, for the things where they genuinely agree:
  // walls, slabs, plinths, barriers.
  function block(cx, cy, cz, sx, sy, sz, mat, surface, opts = {}) {
    const c = opts.c == null ? 0.028 : opts.c;
    const g = chamferBox(sx, sy, sz, c, { color: opts.color, uvScale: opts.uvScale });
    putAll([g], mat, cx, cy, cz, opts.ry || 0, 0, 0, opts.chunk);
    if (opts.noclip) return null;
    return S(boxFromCenter(cx, cy, cz, sx, sy, sz, surface, opts));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 1 · GROUND
  // ═══════════════════════════════════════════════════════════════════════════

  buildTerrain();
  function buildTerrain() {
    // One 210 m plane. It is dead flat where the player walks — collision here
    // is a single box and it must not disagree with what the eye sees — and only
    // starts to roll once it is past the berms, so the horizon is dunes instead
    // of a ruler line.
    const N = 108, EXT = 210;
    const g = new THREE.PlaneGeometry(EXT, EXT, N, N);
    g.rotateX(-Math.PI / 2);
    const pos = g.attributes.position;
    const col = new Float32Array(pos.count * 3);
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i), z = pos.getZ(i);
      const d = Math.max(Math.abs(x) / 40, (z - 56) / 30, (-z - 44) / 30, 0);
      const away = Math.min(1, Math.max(0, d - 0.85) * 1.6);
      const h = fbm(x * 0.021, z * 0.021) * 3.4 * away + fbm(x * 0.11, z * 0.11) * 0.10;
      pos.setY(i, h - 0.01);
      // Two sands: pale wind-sorted crest, darker compacted swale. The blend is
      // driven by the same noise as the height so the tint follows the form.
      const t = 0.5 + 0.5 * fbm(x * 0.06 + 11, z * 0.06 - 7);
      col[i * 3] = 0.86 + t * 0.20;
      col[i * 3 + 1] = 0.83 + t * 0.19;
      col[i * 3 + 2] = 0.76 + t * 0.16;
    }
    g.setAttribute('color', new THREE.BufferAttribute(col, 3));
    g.computeVertexNormals();
    const uv = g.attributes.uv;
    for (let i = 0; i < uv.count; i++) uv.setXY(i, pos.getX(i), pos.getZ(i));
    const mesh = new THREE.Mesh(g, matFor('sand'));
    mesh.receiveShadow = true; mesh.castShadow = false;
    mesh.frustumCulled = false;   // it is always on screen; culling it is a wasted test
    mesh.name = 'terrain';
    group.add(mesh);
    S(makeBox({ x: -105, y: -3, z: -105 }, { x: 105, y: GY, z: 105 }, SURFACE.SAND, { tag: 'floor' }));
  }

  // Cast concrete is poured in bays with a joint between them. Generating the
  // apron as bays rather than one slab gives every 6 m a hairline of shadow, and
  // that is most of what stops a big flat floor reading as a texture on a plane.
  function apron(x0, z0, x1, z1, opts = {}) {
    const cell = opts.cell || 6, joint = 0.055;
    const nx = Math.max(1, Math.round((x1 - x0) / cell)), nz = Math.max(1, Math.round((z1 - z0) / cell));
    for (let i = 0; i < nx; i++) for (let j = 0; j < nz; j++) {
      const ax = x0 + (x1 - x0) * i / nx, bx = x0 + (x1 - x0) * (i + 1) / nx;
      const az = z0 + (z1 - z0) * j / nz, bz = z0 + (z1 - z0) * (j + 1) / nz;
      const cx = (ax + bx) / 2, cz = (az + bz) / 2;
      if (opts.skip && opts.skip(cx, cz, bx - ax, bz - az)) continue;
      const v = 0.90 + rnd() * 0.18;
      putAll([chamferBox(bx - ax - joint, 0.5, bz - az - joint, 0.03, { color: [v, v * 0.995, v * 0.98] })],
        opts.mat || 'concrete', cx, PY - 0.25, cz, 0, 0, 0, opts.chunk);
    }
  }

  // Apron collision is four boxes, not four hundred bays.
  const floorBox = (x0, z0, x1, z1, top = PY, surf = SURFACE.CONCRETE) =>
    S(makeBox({ x: x0, y: top - 0.6, z: z0 }, { x: x1, y: top, z: z1 }, surf, { tag: 'floor' }));

  // ═══════════════════════════════════════════════════════════════════════════
  // 2 · THE PAD, AND THE CABLE TRENCH THAT CROSSES IT
  // ═══════════════════════════════════════════════════════════════════════════

  const TR = { z0: 1.2, z1: 2.6, x0: -20, x1: 12, floor: -0.80 };

  apron(-26, -10, 28, 12, { skip: (cx, cz) => cz > TR.z0 - 3 && cz < TR.z1 + 3 && cx > TR.x0 - 3 && cx < TR.x1 + 3 });
  // The bays either side of the trench are cut by hand so the trench edge is a
  // clean cast lip and not a ragged join.
  apron(-26, -10, 28, TR.z0, { cell: 5.6 });
  apron(-26, TR.z1, 28, 12, { cell: 5.6 });
  apron(TR.x1, TR.z0, 28, TR.z1, { cell: 5.3 });
  apron(-26, TR.z0, TR.x0, TR.z1, { cell: 5.0 });

  floorBox(-26, -10, 28, TR.z0);
  floorBox(-26, TR.z1, 28, 12);
  floorBox(TR.x1, TR.z0, 28, TR.z1);
  floorBox(-26, TR.z0, TR.x0, TR.z1);
  // Trench floor, walls, cable bundles, and three surviving checker plates. The
  // plates are what make the trench readable as a route: you can see it is
  // continuous even where you cannot see into it.
  floorBox(TR.x0, TR.z0, TR.x1, TR.z1, TR.floor);
  putAll([chamferBox(TR.x1 - TR.x0, 0.4, 0.28, 0.02)], 'concrete', (TR.x0 + TR.x1) / 2, PY - 0.2, TR.z0 - 0.12);
  putAll([chamferBox(TR.x1 - TR.x0, 0.4, 0.28, 0.02)], 'concrete', (TR.x0 + TR.x1) / 2, PY - 0.2, TR.z1 + 0.12);
  for (let x = TR.x0 + 1; x < TR.x1; x += 2.4) {
    putAll(PR.cableTray(2.2, 0.5), 'rust', x, TR.floor + 0.06, 1.9);
  }
  for (const [px, pw] of [[-16, 3.2], [-4.5, 2.6], [7.5, 3.0]]) {
    putAll([chamferBox(pw, 0.09, TR.z1 - TR.z0 + 0.3, 0.014)], 'metal', px, PY - 0.045, (TR.z0 + TR.z1) / 2);
    S(boxFromCenter(px, PY - 0.045, (TR.z0 + TR.z1) / 2, pw, 0.09, TR.z1 - TR.z0 + 0.3, SURFACE.METAL));
  }

  // Road in from the gate, and the two aprons north of the bunker line.
  apron(-7.5, 12, 7.5, 52, { cell: 6.5 });
  floorBox(-7.5, 12, 7.5, 52);
  apron(8, -40, 30, -6, { cell: 6.2, chunk: 'silo' });
  floorBox(8, -40, 30, -6);
  apron(-26, -40, 8, -32, { cell: 6.0, chunk: 'bunker' });
  floorBox(-26, -40, 8, -32);

  // ═══════════════════════════════════════════════════════════════════════════
  // 3 · CONTROL BUNKER
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // Footprint x[−26,8] z[−32,−8]. Outer walls 0.55, partitions 0.35. A plus of
  // halls with quadrant rooms hung off it, four exterior doors and a blown east
  // wall, so nothing in here is a dead end and every room has two ways out.

  const B = { x0: -26, x1: 8, z0: -32, z1: -8, tOut: 0.55, tIn: 0.35 };
  floorBox(B.x0, B.z0, B.x1, B.z1, FY);
  apron(B.x0, B.z0, B.x1, B.z1, { cell: 5.0, chunk: 'bunker' });

  // A wall run with door and window openings punched out of it. Segments below,
  // beside and above each opening, so a lintel is real geometry with a real
  // shadow rather than a texture.
  // `axis` names the *fixed* axis: 'z' is a wall standing at a constant z and
  // running along X, 'x' is the other way round.
  function wallRun(axis, fixed, a0, a1, thick, y0, y1, opts = {}) {
    const holes = (opts.holes || []).slice().sort((p, q) => p[0] - q[0]);
    const mat = opts.mat || 'concrete';
    const surf = opts.surface == null ? SURFACE.CONCRETE : opts.surface;
    const alongX = axis === 'z';
    const emit = (b0, b1, ya, yb, m, sf) => {
      if (b1 - b0 < 0.01 || yb - ya < 0.01) return;
      const cx = alongX ? (b0 + b1) / 2 : fixed;
      const cz = alongX ? fixed : (b0 + b1) / 2;
      const sx = alongX ? b1 - b0 : thick;
      const sz = alongX ? thick : b1 - b0;
      putAll([chamferBox(sx, yb - ya, sz, 0.026)], m, cx, (ya + yb) / 2, cz, 0, 0, 0, opts.chunk);
      S(boxFromCenter(cx, (ya + yb) / 2, cz, sx, yb - ya, sz, sf, { thickness: thick * 100 }));
    };
    let cur = a0;
    for (const h of holes) {
      const [ha, hb, hy0, hy1, kind] = [h[0], h[1], h[2] == null ? 0 : h[2], h[3] == null ? y1 : h[3], h[4]];
      emit(cur, ha, y0, y1, mat, surf);
      if (hy0 > y0) emit(ha, hb, y0, hy0, mat, surf);
      if (hy1 < y1) emit(ha, hb, hy1, y1, mat, surf);
      if (kind === 'glass') {
        // Glass is its own material and its own surface id: bullets go through
        // it almost unslowed and the impact FX are completely different.
        const cx = alongX ? (ha + hb) / 2 : fixed;
        const cz = alongX ? fixed : (ha + hb) / 2;
        const sx = alongX ? hb - ha : 0.02;
        const sz = alongX ? 0.02 : hb - ha;
        putAll([chamferBox(sx, hy1 - hy0, sz, 0.004, { color: [1, 1, 1] })], 'glass', cx, (hy0 + hy1) / 2, cz, 0, 0, 0, opts.chunk);
        S(boxFromCenter(cx, (hy0 + hy1) / 2, cz, sx, hy1 - hy0, sz, SURFACE.GLASS, { thickness: 1.6 }));
        for (let t = 0.25; t < 0.99; t += 0.25) {
          const p = ha + (hb - ha) * t;
          putAll([chamferBox(alongX ? 0.07 : 0.09, hy1 - hy0, alongX ? 0.09 : 0.07, 0.01)], 'metal',
            alongX ? p : fixed, (hy0 + hy1) / 2, alongX ? fixed : p, 0, 0, 0, opts.chunk);
        }
      }
      // Every opening gets a steel buck frame. It is 4 cm of geometry and it is
      // the difference between a doorway and a hole.
      if (kind !== 'raw') frameOpening(axis, fixed, ha, hb, hy0, hy1, thick, opts.chunk);
      cur = hb;
    }
    emit(cur, a1, y0, y1, mat, surf);
  }

  function frameOpening(axis, fixed, a0, a1, y0, y1, thick, chunk) {
    const t = 0.075, alongX = axis === 'z';
    const at = (p, y, sx, sy, sz) => {
      const cx = alongX ? p : fixed, cz = alongX ? fixed : p;
      putAll([chamferBox(alongX ? sx : sz, sy, alongX ? sz : sx, 0.012)], 'metal', cx, y, cz, 0, 0, 0, chunk);
    };
    at(a0 + t / 2, (y0 + y1) / 2, t, y1 - y0, thick + 0.06);
    at(a1 - t / 2, (y0 + y1) / 2, t, y1 - y0, thick + 0.06);
    at((a0 + a1) / 2, y1 - t / 2, a1 - a0, t, thick + 0.06);
  }

  const DOOR = 2.75, LOW = 2.45;

  // outer shell
  wallRun('z', B.z0 + B.tOut / 2, B.x0, B.x1, B.tOut, FY, CEIL, { chunk: 'bunker', holes: [[-2, 2, 0, DOOR]] });
  wallRun('z', B.z1 - B.tOut / 2, B.x0, B.x1, B.tOut, FY, CEIL, {
    chunk: 'bunker',
    holes: [[-21, -13, 1.25, 2.55, 'glass'], [-9.5, -6.5, 0, LOW], [-2, 2, 0, DOOR], [3.5, 6, 0, LOW]],
  });
  wallRun('x', B.x0 + B.tOut / 2, B.z0, B.z1, B.tOut, FY, CEIL, { chunk: 'bunker', holes: [[-22, -18, 0, DOOR]] });
  wallRun('x', B.x1 - B.tOut / 2, B.z0, B.z1, B.tOut, FY, CEIL, {
    chunk: 'bunker', holes: [[-30, -27, 0, CEIL, 'raw'], [-26, -22.5, 0, DOOR]],
  });

  // partitions
  wallRun('x', -2, B.z0 + B.tOut, B.z1 - B.tOut, B.tIn, FY, CEIL, {
    chunk: 'bunker', holes: [[-30, -27, 0, LOW], [-22, -18, 0, CEIL, 'raw'], [-13, -10.5, 0, LOW]],
  });
  wallRun('x', 2, B.z0 + B.tOut, B.z1 - B.tOut, B.tIn, FY, CEIL, {
    chunk: 'bunker', holes: [[-26, -22.5, 0, CEIL, 'raw'], [-20, -17.5, 0, LOW], [-12.5, -9.5, 0, LOW]],
  });
  wallRun('z', -22, B.x0 + B.tOut, -2, B.tIn, FY, CEIL, { chunk: 'bunker', holes: [[-14.5, -10, 0, 3.3]] });
  wallRun('z', -18, B.x0 + B.tOut, -2, B.tIn, FY, CEIL, { chunk: 'bunker', holes: [[-20, -16.5, 0, LOW]] });
  wallRun('z', -26, 2, B.x1 - B.tOut, B.tIn, FY, CEIL, { chunk: 'bunker', holes: [[3.8, 6.4, 0, LOW]] });
  wallRun('z', -22.5, 2, B.x1 - B.tOut, B.tIn, FY, CEIL, { chunk: 'bunker', holes: [[3.5, 6, 0, LOW]] });
  wallRun('z', -13, 2, B.x1 - B.tOut, B.tIn, FY, CEIL, { chunk: 'bunker', holes: [[3.5, 6, 0, LOW]] });

  // The half-shut blast door mid-corridor. Without it the spine is a 23 m
  // shooting gallery; with it, it is two 11 m rooms and a pinch point you have
  // to commit to. It is also the strongest silhouette in the building.
  block(-1.45, FY + 1.6, -20, 1.1, 3.2, 0.42, 'metal', SURFACE.METAL, { chunk: 'bunker', c: 0.03 });
  putAll([chamferBox(3.9, 0.34, 0.62, 0.03)], 'concrete', 0, FY + 3.45, -20, 0, 0, 0, 'bunker');
  S(boxFromCenter(0, FY + 3.45, -20, 3.9, 0.34, 0.62, SURFACE.CONCRETE));
  for (const sx of [-1.9, 1.9]) putAll(PR.shs(3.3, 0.16, { color: null }), 'metal', sx, FY + 1.65, -20, 0, 0, Math.PI / 2, 'bunker');

  // ── roof ───────────────────────────────────────────────────────────────────
  // Two collapse holes and one open stairwell. They are the interior's only real
  // light and two of them are also entrances, which is the point: a roof you can
  // only stand on is a perch, a roof you can fall through is a route.
  const HOLES = [
    [-15.5, -28.5, -11.0, -24.5],     // over the generator hall
    [-1.7, -24.5, 1.7, -21.0],        // over the corridor, north of the blast door
    [2.0, -12.9, 7.2, -8.6],          // the open stairwell in the south-east vestibule
  ];
  roofSlab();
  function roofSlab() {
    // Slab minus holes, carved as a strip decomposition so the collision stays
    // as a handful of boxes.
    const bands = [];
    const zs = new Set([B.z0, B.z1]);
    for (const h of HOLES) { zs.add(h[1]); zs.add(h[3]); }
    const zl = [...zs].sort((a, b) => a - b);
    for (let i = 0; i + 1 < zl.length; i++) {
      const za = zl[i], zb = zl[i + 1];
      const cuts = HOLES.filter((h) => h[1] <= za + 1e-4 && h[3] >= zb - 1e-4).sort((p, q) => p[0] - q[0]);
      let x = B.x0;
      for (const c of cuts) {
        if (c[0] > x) bands.push([x, za, c[0], zb]);
        x = c[2];
      }
      if (x < B.x1) bands.push([x, za, B.x1, zb]);
    }
    for (const [x0, z0, x1, z1] of bands) {
      putAll([chamferBox(x1 - x0, ROOF - CEIL, z1 - z0, 0.03)], 'concrete',
        (x0 + x1) / 2, (CEIL + ROOF) / 2, (z0 + z1) / 2, 0, 0, 0, 'bunker');
      S(boxFromCenter((x0 + x1) / 2, (CEIL + ROOF) / 2, (z0 + z1) / 2, x1 - x0, ROOF - CEIL, z1 - z0,
        SURFACE.CONCRETE, { thickness: 70 }));
    }
    // Rubble under the two collapses, so the holes have a cause.
    putAll(PR.rubble(46, 3.4, { seed: 21, big: 0.9 }), 'concrete', -13.2, FY, -26.5, 0, 0, 0, 'bunker');
    putAll(PR.rubble(22, 2.0, { seed: 22, big: 0.55 }), 'concrete', 0, FY, -22.8, 0, 0, 0, 'bunker');
    S(boxFromCenter(-13.2, FY + 0.35, -26.5, 5.0, 0.7, 4.4, SURFACE.CONCRETE, { tag: 'rubble' }));
  }

  // Parapet, with a gap where the catwalk lands.
  const PAR = 1.0;
  wallRun('z', B.z1 - 0.18, B.x0, B.x1, 0.36, ROOF, ROOF + PAR, { chunk: 'bunker', holes: [[-7.7, -5.1, 0, ROOF + PAR, 'raw']] });
  wallRun('z', B.z0 + 0.18, B.x0, B.x1, 0.36, ROOF, ROOF + PAR, { chunk: 'bunker', holes: [] });
  wallRun('x', B.x0 + 0.18, B.z0, B.z1, 0.36, ROOF, ROOF + PAR, { chunk: 'bunker', holes: [] });
  wallRun('x', B.x1 - 0.18, B.z0, B.z1, 0.36, ROOF, ROOF + PAR, { chunk: 'bunker', holes: [[-19.8, -17.4, 0, ROOF + PAR, 'raw']] });
  // Coamings round the holes, so nobody walks into one by accident in the dark.
  for (const [x0, z0, x1, z1] of HOLES) {
    for (const [cx, cz, sx, sz] of [
      [(x0 + x1) / 2, z0, x1 - x0, 0.22], [(x0 + x1) / 2, z1, x1 - x0, 0.22],
      [x0, (z0 + z1) / 2, 0.22, z1 - z0], [x1, (z0 + z1) / 2, 0.22, z1 - z0],
    ]) {
      putAll([chamferBox(sx, 0.34, sz, 0.02)], 'rust', cx, ROOF + 0.17, cz, 0, 0, 0, 'bunker');
      S(boxFromCenter(cx, ROOF + 0.17, cz, sx, 0.34, sz, SURFACE.METAL));
    }
  }

  // ── bunker interior dressing ───────────────────────────────────────────────
  // Cable trays and conduit at 3.2 m the length of the corridor. In a space this
  // plain they are the only thing giving the eye a horizontal to measure depth
  // against, and they are why the corridor reads as 23 m and not as 8.
  putAll(PR.cableTray(22.4, 0.5), 'rust', 0, 3.30, -20.2, Math.PI / 2, 0, 0, 'bunker');
  putAll(PR.cableTray(22.4, 0.34), 'metal', 0, 3.02, -20.2, Math.PI / 2, 0, 0, 'bunker');
  putAll(PR.pipeRun([[1.55, 3.5, -31], [1.55, 3.5, -8.8]], 0.09, { seg: 8, flangeEvery: 5.5 }), 'rust', 0, 0, 0, 0, 0, 0, 'bunker');
  putAll(PR.cableTray(21.0, 0.44), 'rust', -13.8, 3.30, -20, 0, 0, 0, 'bunker');
  putAll(PR.cableTray(21.0, 0.44), 'rust', -13.8, 3.30, -12, 0, 0, 0, 'bunker');

  // Generator hall: two engine blocks on plinths, an exhaust stack through the
  // roof, day tanks. Big shapes at 1.3–2.1 m, i.e. all of it is usable cover.
  for (const gz of [-29.4, -24.8]) {
    block(-19, FY + 0.18, gz, 5.6, 0.36, 2.6, 'concrete', SURFACE.CONCRETE, { chunk: 'bunker' });
    block(-19, FY + 1.1, gz, 4.6, 1.5, 1.9, 'metal', SURFACE.METAL, { chunk: 'bunker', c: 0.04 });
    putAll(PR.pipeRun([[-21.6, FY + 2.0, gz], [-21.6, FY + 3.9, gz], [-24.4, FY + 3.9, gz]], 0.19, { seg: 10 }), 'rust', 0, 0, 0, 0, 0, 0, 'bunker');
    for (let i = 0; i < 5; i++) putAll([chamferBox(0.24, 0.6, 0.24, 0.02)], 'metal', -21.1, FY + 1.95, gz - 0.8 + i * 0.4, 0, 0, 0, 'bunker');
  }
  block(-8.6, FY + 1.35, -28.4, 2.2, 2.5, 2.2, 'rust', SURFACE.METAL, { chunk: 'bunker', c: 0.05 });
  putAll(PR.drum({}), 'rust', -6.0, FY, -30.4, 0.3, 0, 0, 'bunker');
  putAll(PR.drum({}), 'rust', -5.3, FY, -29.5, 1.1, 0, 0, 'bunker');
  putAll(PR.drum({}), 'rust', -6.4, FY, -29.2, 2.2, 0, 0, 'bunker');
  S(boxFromCenter(-5.9, FY + 0.45, -29.7, 1.9, 0.9, 1.9, SURFACE.METAL));
  putAll(PR.crate(1.5, 1.1, 1.0, {}), 'wood', -24.0, FY, -20.2, 0.15, 0, 0, 'bunker');
  putAll(PR.crate(1.2, 0.9, 0.9, {}), 'wood', -22.5, FY, -19.9, -0.4, 0, 0, 'bunker');
  S(boxFromCenter(-23.3, FY + 0.55, -20.0, 3.4, 1.1, 1.2, SURFACE.WOOD));

  // Control room: a run of consoles under the observation window, and a bank of
  // relay cabinets that splits the room into two lanes.
  for (let i = 0; i < 4; i++) putAll(PR.console3(2.4, {}), 'dark', -20.5 + i * 2.6, FY, -11.4, 0, 0, 0, 'bunker');
  S(boxFromCenter(-16.6, FY + 0.55, -11.5, 11.2, 1.1, 1.1, SURFACE.METAL));
  for (let i = 0; i < 5; i++) {
    block(-9.6, FY + 1.05, -16.6 + i * 1.0, 1.0, 2.1, 0.92, 'dark', SURFACE.METAL, { chunk: 'bunker', c: 0.02 });
  }
  putAll(PR.crate(1.1, 0.8, 0.8, {}), 'wood', -6.0, FY, -13.6, 0.5, 0, 0, 'bunker');
  S(boxFromCenter(-6.0, FY + 0.4, -13.6, 1.2, 0.8, 0.9, SURFACE.WOOD));

  // East gallery: racks either side, 1.6 m aisle. Nothing in here is longer than
  // 9 m and that is deliberate — it is the one room where a shotgun is correct.
  for (let z = -21.5; z < -14; z += 2.2) {
    block(3.2, FY + 1.0, z, 1.5, 2.0, 0.8, 'rust', SURFACE.METAL, { chunk: 'bunker', c: 0.02 });
    block(6.5, FY + 1.0, z + 1.1, 1.5, 2.0, 0.8, 'rust', SURFACE.METAL, { chunk: 'bunker', c: 0.02 });
  }
  // Pump room: a manifold of pipes and a squat tank.
  putAll(PR.pipeRun([[2.6, FY + 0.6, -31.0], [2.6, FY + 0.6, -27.0], [6.6, FY + 0.6, -27.0], [6.6, FY + 2.4, -27.0]], 0.2, { seg: 10 }), 'rust', 0, 0, 0, 0, 0, 0, 'bunker');
  S(makeBox({ x: 2.3, y: FY, z: -31.2 }, { x: 2.9, y: FY + 0.9, z: -26.7 }, SURFACE.METAL));
  block(5.2, FY + 0.85, -29.6, 3.4, 1.7, 2.2, 'metal', SURFACE.METAL, { chunk: 'bunker', c: 0.05 });

  // Blown east wall — rubble spill out into the alley, and enough of a ramp that
  // it is a real route rather than a window.
  putAll(PR.rubble(40, 2.6, { seed: 31, big: 0.8 }), 'concrete', 9.6, GY + PY, -28.4, 0, 0, 0, 'silo');
  S(boxFromCenter(9.0, PY + 0.20, -28.4, 3.2, 0.4, 3.0, SURFACE.CONCRETE, { tag: 'rubble' }));
  S(boxFromCenter(10.4, PY + 0.10, -28.4, 2.0, 0.2, 3.0, SURFACE.CONCRETE, { tag: 'rubble' }));

  // Caged ladder up the open stairwell to the roof. Left non-solid on purpose:
  // until the player controller grows a climb state a solid ladder is just a
  // thing you bump into, and the alley stair already carries the roof route.
  putAll(PR.ladder(ROOF - FY + 0.5, { cage: true }), 'metal', 3.1, FY, -9.1, Math.PI, 0, 0, 'bunker');
  S(boxFromCenter(3.1, FY + 2.4, -8.85, 0.9, 4.8, 0.4, SURFACE.METAL, { solid: false, blocksSight: false }));

  // ── roof furniture ─────────────────────────────────────────────────────────
  putAll(PR.hvac(2.4, 1.5, 1.8, {}), 'metal', -22.0, ROOF, -16.5, 0.2, 0, 0, 'bunker');
  S(boxFromCenter(-22.0, ROOF + 0.75, -16.5, 2.5, 1.5, 1.9, SURFACE.METAL));
  const fan = new THREE.Mesh(fanBlades(0.55), matFor('metal'));
  fan.position.set(-22.0, ROOF + 1.62, -16.5);
  fan.castShadow = true; fan.receiveShadow = true;
  group.add(fan);

  putAll(PR.hvac(1.8, 1.2, 1.6, {}), 'metal', -4.5, ROOF, -28.0, -0.35, 0, 0, 'bunker');
  S(boxFromCenter(-4.5, ROOF + 0.6, -28.0, 1.9, 1.2, 1.7, SURFACE.METAL));

  // The leaning mast. Nineteen metres, eight degrees out of true, and it is the
  // one thing on this site visible from literally every square metre of it.
  putAll(PR.latticeMast(19, { rBase: 0.95, rTop: 0.34 }), 'rust', -19.5, ROOF, -27.5, 0.4, 0, 0.145, 'bunker');
  S(boxFromCenter(-19.5, ROOF + 1.2, -27.5, 2.0, 2.4, 2.0, SURFACE.METAL, { thickness: 30 }));
  for (const [dx, dz] of [[4.2, 3.4], [-4.6, 2.8], [0.6, -5.0]]) {
    putAll(PR.pipeRun([[-19.5 + 0.9, ROOF + 16.5, -27.5], [-19.5 + dx * 1.9, ROOF + 0.1, -27.5 + dz * 1.9]], 0.03, { seg: 4, flangeEvery: 99 }), 'metal', 0, 0, 0, 0, 0, 0, 'bunker');
  }
  // Dish, aimed south-east at nothing in particular for thirty years.
  const dish = prep(new THREE.SphereGeometry(1.15, 16, 8, 0, Math.PI * 2, 0, Math.PI * 0.42));
  putAll([dish], 'metal', -12.0, ROOF + 1.7, -30.0, 2.4, 2.0, 0, 'bunker');
  putAll([chamferBox(0.24, 1.7, 0.24, 0.02)], 'metal', -12.0, ROOF + 0.85, -30.0, 0, 0, 0, 'bunker');
  S(boxFromCenter(-12.0, ROOF + 1.0, -30.0, 0.6, 2.0, 0.6, SURFACE.METAL));

  // Rooftop overwatch: sandbags at the south parapet, looking straight down onto
  // the pad. Whoever holds this makes the pad crossing expensive, which is what
  // gives the trench a reason to exist.
  putAll(PR.sandbags(4.2, 3, { seed: 9 }), 'sand', -13.0, ROOF + PAR - 0.02, -8.9, 0, 0, 0, 'bunker');
  S(boxFromCenter(-13.0, ROOF + PAR + 0.28, -8.9, 4.4, 0.62, 0.6, SURFACE.SAND));
  putAll(PR.crate(1.2, 0.9, 0.9, {}), 'wood', -10.4, ROOF, -10.4, 0.35, 0, 0, 'bunker');
  S(boxFromCenter(-10.4, ROOF + 0.45, -10.4, 1.3, 0.9, 1.0, SURFACE.WOOD));
  putAll(PR.drum({}), 'rust', 6.0, ROOF, -20.0, 0.7, 0, 0, 'bunker');
  putAll(PR.drum({}), 'rust', 6.6, ROOF, -20.9, 1.9, 0, 0, 'bunker');
  S(boxFromCenter(6.3, ROOF + 0.45, -20.5, 1.7, 0.9, 1.7, SURFACE.METAL));

  // External stair up the east face, in the alley between the bunker and the
  // silo collar — the third way onto the roof, the one an attacker takes, and
  // the reason a 3.8 m gap is worth contesting instead of just walking through.
  buildAlleyStair();
  function buildAlleyStair() {
    const x = 9.9, base = PY, steps = 16, rise = (ROOF - base) / steps, run = 0.30;
    putAll(PR.stair(steps, rise, run, 1.35, {}), 'metal', x, base, -13.0, Math.PI, 0, 0, 'silo');
    rampBox(x, base, -13.0, -13.0 - steps * run, 1.35, ROOF - base);
    for (const sx of [-0.75, 0.75]) {
      putAll(PR.railing(5.6, { h: 1.06, spacing: 1.4 }), 'metal', x + sx, base + 2.3, -15.4, Math.PI / 2, 0, -0.79, 'silo');
      S(makeBox({ x: x + sx - 0.05, y: base, z: -18.0 }, { x: x + sx + 0.05, y: ROOF + 1.0, z: -12.9 },
        SURFACE.METAL, { solid: true, blocksSight: false }));
    }
    // Top landing, and the plate that bridges the parapet gap onto the roof.
    putAll([chamferBox(2.4, 0.09, 2.0, 0.012)], 'metal', x + 0.1, ROOF, -18.9, 0, 0, 0, 'silo');
    S(boxFromCenter(x + 0.1, ROOF - 0.05, -18.9, 2.4, 0.14, 2.0, SURFACE.METAL));
    putAll([chamferBox(2.6, 0.09, 1.8, 0.012)], 'metal', 8.5, ROOF, -18.6, 0, 0, 0, 'bunker');
    S(boxFromCenter(8.5, ROOF - 0.05, -18.6, 2.6, 0.14, 1.8, SURFACE.METAL));
    putAll(PR.railing(2.0, { h: 1.06 }), 'metal', x + 1.25, ROOF, -18.9, Math.PI / 2, 0, 0, 'silo');
    S(makeBox({ x: x + 1.2, y: ROOF, z: -19.9 }, { x: x + 1.3, y: ROOF + 1.08, z: -17.9 },
      SURFACE.METAL, { solid: true, blocksSight: false }));
  }

  // Stairs are a chore for an AABB collider, so each flight collides as a stack
  // of slabs sized to stay under STEP_HEIGHT — the controller walks up them
  // without ever knowing there was a stair there.
  function rampBox(cx, y0, z0, z1, width, rise) {
    const n = Math.max(4, Math.ceil(rise / 0.34));
    const dz = (z1 - z0) / n;
    for (let i = 0; i < n; i++) {
      const y = y0 + rise * (i + 1) / n;
      S(makeBox({ x: cx - width / 2, y: y - 0.7, z: Math.min(z0 + dz * i, z0 + dz * (i + 1)) },
        { x: cx + width / 2, y, z: Math.max(z0 + dz * i, z0 + dz * (i + 1)) }, SURFACE.METAL, { tag: 'stair' }));
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 4 · SILO CAP AND SERVICE GANTRY
  // ═══════════════════════════════════════════════════════════════════════════

  let hoist = null;
  buildSilo();
  function buildSilo() {
    const seg = 8, rm = (SILO.rOut + SILO.rIn) / 2, ring = SILO.rOut - SILO.rIn;
    const chord = 2 * SILO.rOut * Math.tan(Math.PI / seg) + 0.08;
    for (let i = 0; i < seg; i++) {
      const a = (i + 0.5) / seg * Math.PI * 2;
      const cx = SILO.x + Math.cos(a) * rm, cz = SILO.z + Math.sin(a) * rm;
      putAll([chamferBox(chord, SILO.top, ring, 0.05)], 'concrete', cx, SILO.top / 2, cz, -a, 0, 0, 'silo');
      // The visual segment is a rotated slab; its collider is the slab's own
      // bounding box, which over-covers slightly inward. That is the right way
      // to be wrong here — an under-covered ring leaves gaps you fall through.
      const ca = Math.abs(Math.cos(a)), sa = Math.abs(Math.sin(a));
      S(boxFromCenter(cx, SILO.top / 2, cz, ca * ring + sa * chord, SILO.top, sa * ring + ca * chord,
        SURFACE.CONCRETE, { thickness: 200 }));
      for (let k = -1; k <= 1; k++) {
        putAll([cyl(0.055, 0.055, 0.14, 6)], 'metal',
          cx + Math.cos(a + k * 0.13) * 0.6, SILO.top + 0.05, cz + Math.sin(a + k * 0.13) * 0.6, 0, 0, 0, 'silo');
      }
    }
    // The throat, silted to within 20 cm of the collar with thirty years of
    // blown sand and a collapsed grating. Solid, and level with the rim, because
    // a pit you cannot climb out of is a bug wearing a level designer's hat.
    putAll([cyl(SILO.rIn + 0.1, SILO.rIn + 0.1, 1.7, 16)], 'sand', SILO.x, 0.1, SILO.z, 0, 0, 0, 'silo');
    S(boxFromCenter(SILO.x, 0.1, SILO.z, SILO.rIn * 1.72, 1.7, SILO.rIn * 1.72, SURFACE.SAND, { tag: 'floor' }));
    for (let i = 0; i < 5; i++) {
      const a = i * 1.31, r = 1.2 + i * 0.7;
      putAll([chamferBox(2.6, 0.09, 1.4, 0.012)], 'rust',
        SILO.x + Math.cos(a) * r, 0.98, SILO.z + Math.sin(a) * r, a * 1.7, (rnd() - 0.5) * 0.22, 0, 'silo');
    }
    // Hazard banding round the lip. Without it the cap is a circular concrete
    // pad; with it, it is unmistakably the top of a hole, from 40 m, in one
    // glance — which is the entire job of a landmark.
    for (let i = 0; i < 20; i++) {
      const a = (i + 0.5) / 20 * Math.PI * 2;
      putAll([chamferBox(0.9, 0.22, 0.42, 0.02)], i % 2 ? 'paint' : 'dark',
        SILO.x + Math.cos(a) * (SILO.rIn + 0.28), SILO.top + 0.05, SILO.z + Math.sin(a) * (SILO.rIn + 0.28),
        -a, 0, 0, 'silo');
    }
    // Two sand drifts banked up the collar's flanks. They are the only way onto
    // the rim, which makes the cap a position you have to commit to reaching.
    putAll(PR.drift(7.6, 1.30, 3.2, { seed: 6 }), 'sand', SILO.x + 7.6, PY, SILO.z - 1.8, -Math.PI / 2, 0, 0, 'silo');
    for (let i = 0; i < 4; i++) {
      S(makeBox({ x: SILO.x + 6.9 + (3 - i) * 0.8, y: PY, z: SILO.z - 5.4 },
        { x: SILO.x + 6.9 + (4 - i) * 0.8, y: PY + 0.29 * (i + 1), z: SILO.z + 1.8 }, SURFACE.SAND, { tag: 'stair' }));
    }
    putAll(PR.drift(6.4, 1.20, 3.0, { seed: 7 }), 'sand', SILO.x - 7.6, PY, SILO.z + 1.4, Math.PI / 2, 0, 0, 'silo');
    for (let i = 0; i < 4; i++) {
      S(makeBox({ x: SILO.x - 6.9 - (4 - i) * 0.8, y: PY, z: SILO.z - 1.4 },
        { x: SILO.x - 6.9 - (3 - i) * 0.8, y: PY + 0.29 * (i + 1), z: SILO.z + 4.4 }, SURFACE.SAND, { tag: 'stair' }));
    }

    // The launcher closure door, rolled clear on its rails and left there thirty
    // years ago. Nine and a half metres of chamfered concrete 1.25 m tall:
    // mantle cover, a wind break, and the biggest single readable mass on site.
    const dz = -33.5;
    for (const rx of [-3.6, 3.6]) {
      putAll([chamferBox(0.42, 0.22, 13.0, 0.02)], 'metal', SILO.x + rx, PY + 0.10, -28.0, 0, 0, 0, 'silo');
      S(boxFromCenter(SILO.x + rx, PY + 0.10, -28.0, 0.42, 0.22, 13.0, SURFACE.METAL));
    }
    putAll([chamferBox(9.6, 1.25, 8.6, 0.07)], 'concrete', SILO.x, PY + 0.72, dz, 0, 0, 0.028, 'silo');
    S(boxFromCenter(SILO.x, PY + 0.70, dz, 9.5, 1.24, 8.5, SURFACE.CONCRETE, { thickness: 400 }));
    for (const sx of [-4.0, 4.0]) for (const sz of [-3.4, 0, 3.4]) {
      putAll([cyl(0.34, 0.34, 0.5, 10)], 'metal', SILO.x + sx, PY + 0.15, dz + sz, 0, 0, 0, 'silo');
    }
    putAll(PR.drift(9.6, 1.30, 3.2, { seed: 5 }), 'sand', SILO.x, PY, dz - 4.3, Math.PI, 0, 0, 'silo');

    // Service gantry, straddling the cap north–south, 9.5 m to the underside of
    // the girder. Red and white banding, because that is what a lifting beam is
    // painted and because a saturated colour that high is the fastest
    // orientation cue anywhere on the site.
    const spread = 3.4;
    for (const gz of [-5.0, -25.0]) {
      for (const s of [-1, 1]) {
        const foot = gz + s * spread, top = gz + s * 0.55;
        const rr = Math.abs(foot - SILO.z);
        const fy = rr >= SILO.rIn - 0.3 && rr <= SILO.rOut + 0.3 ? SILO.top : PY;
        for (const lx of [-1.5, 1.5]) {
          putAll(PR.pipeRun([[SILO.x + lx, fy, foot], [SILO.x + lx * 0.4, 9.4, top]], 0.14,
            { seg: 8, flangeEvery: 3.2 }), 'metal', 0, 0, 0, 0, 0, 0, 'silo');
          S(boxFromCenter(SILO.x + lx * 0.8, (fy + 9.4) / 2, foot - s * 0.9, 0.55, 9.4 - fy, 2.0,
            SURFACE.METAL, { thickness: 40 }));
        }
      }
      for (let y = 2.4; y < 9.0; y += 2.3) {
        for (const lx of [-1.1, 1.1]) {
          putAll(PR.shs(spread * 2 * (1 - y / 13), 0.09), 'metal', SILO.x + lx, y, gz, Math.PI / 2, 0, 0, 'silo');
        }
      }
      putAll(PR.shs(3.4, 0.11), 'metal', SILO.x, 9.3, gz, 0, 0, 0, 'silo');
    }
    const gL = 20.0, bands = 13;
    for (let i = 0; i < bands; i++) {
      const z = -25.0 + (gL / bands) * (i + 0.5);
      putAll(PR.iBeam(gL / bands + 0.02, 1.15, 0.6, { web: 0.05, flange: 0.075 }), i % 2 ? 'paint' : 'concrete',
        SILO.x, 9.5, z, Math.PI / 2, 0, 0, 'silo');
    }
    S(boxFromCenter(SILO.x, 9.5, -15.0, 0.7, 1.2, gL, SURFACE.METAL, { thickness: 40 }));

    // Trolley and hook block — the one moving thing in the level.
    hoist = new THREE.Group();
    const hm = new THREE.Mesh(mergeGeometries([
      ...PR.shs(1.3, 0.24).map((g) => prep(g)),
      prep(chamferBox(0.55, 0.7, 0.42, 0.02).translate(0, -2.6, 0)),
      prep(cyl(0.045, 0.045, 2.2, 6).translate(0, -1.3, 0)),
      prep(torus(0.28, 0.06, 5, 10, Math.PI * 1.6).rotateX(Math.PI / 2).translate(0, -3.15, 0)),
    ]), matFor('metal'));
    hm.castShadow = true; hm.receiveShadow = true;
    hoist.add(hm);
    hoist.position.set(SILO.x, 8.6, -12.0);
    group.add(hoist);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 5 · THE CATWALK
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // North–south run at x=16 from the stair tower at z=22.5 up to z=−6.5, then
  // west across the pad to x=−6.4 and up four steps onto the bunker roof. Deck
  // at 3.70 with 1.06 m rails: standing on it you are exposed from the waist up
  // to the whole approach, which is the trade for owning every angle onto the
  // pad. Rails are solid to bodies and transparent to bullets — you can shoot a
  // man off this walkway, you just cannot walk through the rail to do it.

  const CW = { x: 16, zS: 22.5, zN: -6.5, xW: -6.4 };
  buildCatwalk();
  function buildCatwalk() {
    const runNS = CW.zS - CW.zN;
    putAll(PR.catwalk(runNS, 1.6, {}), 'metal', CW.x, DECK, (CW.zS + CW.zN) / 2, 0, 0, 0, 'pad');
    S(makeBox({ x: CW.x - 0.85, y: DECK - 0.32, z: CW.zN - 0.8 }, { x: CW.x + 0.85, y: DECK, z: CW.zS }, SURFACE.METAL, { thickness: 5 }));
    const runEW = CW.x + 0.8 - CW.xW;
    putAll(PR.catwalk(runEW, 1.6, {}), 'metal', (CW.x + 0.8 + CW.xW) / 2, DECK, CW.zN, Math.PI / 2, 0, 0, 'pad');
    S(makeBox({ x: CW.xW - 0.8, y: DECK - 0.32, z: CW.zN - 0.85 }, { x: CW.x + 0.85, y: DECK, z: CW.zN + 0.85 }, SURFACE.METAL, { thickness: 5 }));

    // Rails. One 3 m section on the west run is missing — its stanchions are
    // sheared off at the deck — which is a real hazard, a mantle-down shortcut
    // onto the containers below, and the kind of asymmetry that makes a player
    // remember which end of a walkway they are on.
    const rail = (len, x, z, ry, skip) => {
      putAll(PR.railing(len, { skip }), 'metal', x, DECK, z, ry, 0, 0, 'pad');
      const half = len / 2;
      const b = ry === 0
        ? makeBox({ x: x - half, y: DECK, z: z - 0.05 }, { x: x + half, y: DECK + 1.08, z: z + 0.05 }, SURFACE.METAL, { solid: true, blocksSight: false })
        : makeBox({ x: x - 0.05, y: DECK, z: z - half }, { x: x + 0.05, y: DECK + 1.08, z: z + half }, SURFACE.METAL, { solid: true, blocksSight: false });
      S(b);
    };
    rail(runNS, CW.x - 0.78, (CW.zS + CW.zN) / 2, Math.PI / 2);
    rail(runNS, CW.x + 0.78, (CW.zS + CW.zN) / 2, Math.PI / 2);
    rail(runEW, (CW.x + 0.8 + CW.xW) / 2, CW.zN - 0.78, 0);
    // North side, minus a 3.6 m section between x=3.4 and x=7.0.
    rail(9.8, -1.5, CW.zN + 0.78, 0);
    rail(9.8, 11.9, CW.zN + 0.78, 0);

    // Trestles. Real I-beams with a head beam and knee braces, spaced so the
    // main bunker door at x∈[−2,2] is never behind a column.
    for (const z of [21.0, 15.5, 10.0, 4.5, -1.0, -6.0]) trestle(CW.x, z);
    for (const x of [-4.5, 4.5, 10.5]) trestle(x, CW.zN);
    function trestle(x, z) {
      for (const sx of [-0.72, 0.72]) {
        const dx = Math.abs(z - CW.zN) < 0.6 ? 0 : sx, dz = Math.abs(z - CW.zN) < 0.6 ? sx : 0;
        putAll(PR.iBeam(DECK - 0.35 - PY, 0.28, 0.18), 'metal', x + dx, (PY + DECK - 0.35) / 2, z + dz, 0, 0, Math.PI / 2, 'pad');
        S(boxFromCenter(x + dx, (PY + DECK - 0.35) / 2, z + dz, 0.24, DECK - 0.35 - PY, 0.24, SURFACE.METAL, { thickness: 30 }));
        putAll([chamferBox(0.5, 0.06, 0.5, 0.01)], 'metal', x + dx, PY + 0.03, z + dz, 0, 0, 0, 'pad');
      }
      const ry = Math.abs(z - CW.zN) < 0.6 ? Math.PI / 2 : 0;
      putAll(PR.iBeam(2.0, 0.3, 0.2), 'metal', x, DECK - 0.35, z, ry, 0, 0, 'pad');
      for (const s of [-1, 1]) {
        putAll(PR.shs(1.35, 0.08), 'metal',
          x + (ry ? 0 : s * 0.42), DECK - 0.95, z + (ry ? s * 0.42 : 0), ry, 0, s * (ry ? -0.78 : 0.78), 'pad');
      }
    }

    // Stair tower down to the approach: one straight flight, twelve 30 cm risers
    // climbing north to meet the deck. A 31° diagonal is also the only strong
    // non-orthogonal line in the approach, which is most of why it reads.
    putAll(PR.stair(12, 0.30, 0.5, 1.5, {}), 'metal', CW.x, PY, 28.5, Math.PI, 0, 0, 'approach');
    rampBox(CW.x, PY, 28.5, 22.5, 1.5, DECK - PY);
    for (const sx of [-0.86, 0.86]) {
      putAll(PR.railing(7.0, { h: 1.06, spacing: 1.4 }), 'metal', CW.x + sx, PY + 1.85, 25.5, Math.PI / 2, 0, 0.54, 'approach');
      S(makeBox({ x: CW.x + sx - 0.05, y: PY, z: 22.4 }, { x: CW.x + sx + 0.05, y: DECK + 1.0, z: 28.6 }, SURFACE.METAL, { solid: true, blocksSight: false }));
    }
    putAll(PR.iBeam(3.4, 0.3, 0.2), 'metal', CW.x, DECK - 0.35, 22.6, 0, 0, 0, 'approach');
    for (const sx of [-1.5, 1.5]) {
      putAll(PR.iBeam(DECK - 0.35 - PY, 0.28, 0.18), 'metal', CW.x + sx, (PY + DECK - 0.35) / 2, 22.6, 0, 0, Math.PI / 2, 'approach');
      S(boxFromCenter(CW.x + sx, (PY + DECK - 0.35) / 2, 22.6, 0.24, DECK - 0.35 - PY, 0.24, SURFACE.METAL, { thickness: 30 }));
    }

    // Caged ladder off the pad, mid-run. The short way up, and the one that
    // leaves you nowhere to go for four seconds.
    putAll(PR.ladder(DECK - PY + 0.55, { cage: true }), 'metal', CW.x + 0.95, PY, 8.0, Math.PI / 2, 0, 0, 'pad');
    S(boxFromCenter(CW.x + 1.15, (PY + DECK) / 2, 8.0, 0.45, DECK - PY, 0.9, SURFACE.METAL, { solid: false, blocksSight: false }));

    // West end: landing, four steps and a bridging plate onto the bunker roof.
    putAll([chamferBox(2.4, 0.09, 2.4, 0.014)], 'metal', CW.xW, DECK, CW.zN, 0, 0, 0, 'pad');
    S(boxFromCenter(CW.xW, DECK - 0.05, CW.zN, 2.4, 0.14, 2.4, SURFACE.METAL));
    putAll(PR.stair(4, 0.25, 0.32, 1.4, {}), 'metal', CW.xW, DECK, -7.7, Math.PI, 0, 0, 'pad');
    for (let i = 0; i < 4; i++) {
      S(makeBox({ x: CW.xW - 0.7, y: DECK - 0.4, z: -7.7 - 0.32 * (i + 1) }, { x: CW.xW + 0.7, y: DECK + 0.25 * (i + 1), z: -7.7 - 0.32 * i }, SURFACE.METAL, { tag: 'stair' }));
    }
    putAll([chamferBox(1.5, 0.09, 1.6, 0.012)], 'metal', CW.xW, ROOF, -8.4, 0, 0, 0, 'bunker');
    S(boxFromCenter(CW.xW, ROOF - 0.05, -8.4, 1.5, 0.14, 1.8, SURFACE.METAL));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 6 · APPROACH
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // The road from the gate is 34 m of clear ground and it is meant to be
  // frightening. Everything in here exists to give you a way to cross it that is
  // not "run in a straight line": two jersey chevrons that force a slalom, two
  // revetments to leapfrog between, and containers to break the diagonal.

  // Jersey chevrons. Row A blocks the west, Row B blocks the east, 7 m apart, so
  // there is a lane through but it is an S and you are side-on for half of it.
  for (let x = -16; x <= 2.01; x += 3.05) {
    putAll(PR.jersey(3.0, {}), 'concrete', x, GY, 40 + (x % 6 === 0 ? 0.35 : 0), 0.02, 0, 0, 'approach');
    S(boxFromCenter(x, GY + 0.535, 40, 3.0, 1.07, 0.62, SURFACE.CONCRETE, { thickness: 55 }));
  }
  for (let x = -3; x <= 15.01; x += 3.05) {
    putAll(PR.jersey(3.0, {}), 'concrete', x, GY, 33, -0.015, 0, 0, 'approach');
    S(boxFromCenter(x, GY + 0.535, 33, 3.0, 1.07, 0.62, SURFACE.CONCRETE, { thickness: 55 }));
  }

  // Revetments. Embrasures at 1.15–1.65 m: you can put a rifle through one
  // standing, and there is nothing to shoot at below it.
  revetWall(-14, 21.5, 13, 0, [-3.6, 2.4]);
  revetWall(13.5, 30, 10, 0, [-2.2, 2.2]);
  revetWall(-20.6, 15.5, 9, Math.PI / 2, [-1.8, 2.6]);
  // On the pad itself, 1.75 m stubs rather than full revetments — stand-behind
  // cover that still lets you see the roofline over the top of it. A 3.4 m wall
  // here would cut the apron in half and kill every sightline worth having.
  block(-9.5, PY + 0.875, -1.5, 3.6, 1.75, 0.62, 'concrete', SURFACE.CONCRETE, { chunk: 'pad' });
  block(2.6, PY + 0.875, 6.6, 0.62, 1.75, 3.2, 'concrete', SURFACE.CONCRETE, { chunk: 'pad' });
  block(14.5, PY + 0.875, -6.0, 3.2, 1.75, 0.62, 'concrete', SURFACE.CONCRETE, { chunk: 'pad' });
  block(-17.5, PY + 0.875, 6.0, 0.62, 1.75, 3.4, 'concrete', SURFACE.CONCRETE, { chunk: 'pad' });
  function revetWall(x, z, len, ry, slots) {
    putAll(PR.revetment(len, 3.4, { slots }), 'concrete', x, GY, z, ry, 0, 0);
    const along = ry === 0 ? 'x' : 'z';
    // Collision follows the openings so a bullet through an embrasure actually
    // goes through. Below the slot is solid, above the slot is solid.
    const segs = [];
    let cur = -len / 2;
    for (const s of slots.slice().sort((a, b) => a - b)) {
      segs.push([cur, s - 0.275]); cur = s + 0.275;
    }
    segs.push([cur, len / 2]);
    for (const [a, b] of segs) {
      if (b - a < 0.02) continue;
      const cx = along === 'x' ? x + (a + b) / 2 : x, cz = along === 'x' ? z : z + (a + b) / 2;
      S(boxFromCenter(cx, GY + 1.75, cz, along === 'x' ? b - a : 0.7, 3.5, along === 'x' ? 0.7 : b - a, SURFACE.CONCRETE, { thickness: 70 }));
    }
    for (const s of slots) {
      const cx = along === 'x' ? x + s : x, cz = along === 'x' ? z : z + s;
      S(boxFromCenter(cx, GY + 0.575, cz, along === 'x' ? 0.55 : 0.7, 1.15, along === 'x' ? 0.7 : 0.55, SURFACE.CONCRETE, { thickness: 70 }));
      S(boxFromCenter(cx, GY + 2.6, cz, along === 'x' ? 0.55 : 0.7, 1.9, along === 'x' ? 0.7 : 0.55, SURFACE.CONCRETE, { thickness: 70 }));
    }
    // Sand banked against the windward face.
    putAll(PR.drift(len, 0.85, 2.4, { seed: (x * 31 + z) | 0 }), 'sand', x, GY, z, ry, 0, 0);
  }

  // Containers. 2.59 m — you cannot see over one, which is exactly why they are
  // the only props on the approach that create genuine dead ground.
  cont(-21, 12, 12.19, 0.055);
  cont(-23.4, 12.4, 6.06, 0.20, 2.59);
  cont(24.5, 30, 6.06, Math.PI / 2 + 0.05);
  cont(-10.5, 44.5, 6.06, 0.42);
  cont(11.5, 5.0, 6.06, -0.07);
  cont(-15.5, -36, 12.19, 0.09, 0, 'bunker');
  cont(21.5, 8.0, 6.06, Math.PI / 2 - 0.03);
  function cont(x, z, len, ry, y = 0, chunk = null) {
    putAll(PR.container(len, {}), 'rust', x, GY + y, z, ry, 0, 0, chunk);
    const c = Math.cos(ry), s = Math.sin(ry);
    const sx = Math.abs(c) * len + Math.abs(s) * 2.44, sz = Math.abs(s) * len + Math.abs(c) * 2.44;
    S(boxFromCenter(x, GY + y + 1.30, z, sx, 2.59, sz, SURFACE.METAL, { thickness: 8 }));
  }

  // Sandbag emplacements. 1.05 m of sand stops anything this game fires, which
  // makes these the safest low cover on the site and the AI's favourite anchors.
  bags(7.5, 18.0, 4.4, 0.05);
  bags(-4.5, 30.5, 3.6, Math.PI / 2);
  bags(23.5, -7.5, 3.4, 0.2, 'silo');
  bags(-24.0, -3.0, 3.6, Math.PI / 2, 'pad');
  function bags(x, z, len, ry, chunk = null) {
    putAll(PR.sandbags(len, 5, { seed: (x * 7 + z) | 0 }), 'sand', x, GY, z, ry, 0, 0, chunk);
    const c = Math.abs(Math.cos(ry)), s = Math.abs(Math.sin(ry));
    S(boxFromCenter(x, GY + 0.50, z, c * len + s * 0.55, 1.00, s * len + c * 0.55, SURFACE.SAND, { thickness: 90 }));
  }

  // Floodlight masts. Nine metres of nothing, and they are load-bearing: a flat
  // apron with no vertical elements has no sense of scale at all.
  for (const [x, z, ry, ch] of [
    [-25, 45, 0.2, 'approach'], [26, 44, -0.3, 'approach'], [-28.5, 8, 1.2, 'pad'],
    [-8.5, 24, 0.35, 'approach'], [22.5, 26, -0.5, 'approach'],
    [26.5, 15, -0.8, 'approach'], [27, -30, 0.4, 'silo'], [-6, -37, 0.9, 'bunker'],
  ]) {
    const m = PR.floodMast(9, {});
    putAll(m.parts, 'metal', x, GY, z, ry, 0, 0, ch);
    for (const l of m.lamps) {
      const p = new THREE.Vector3(l[0], l[1], l[2]).applyMatrix4(xf(x, GY, z, ry));
      putAll([chamferBox(0.40, 0.03, 0.28, 0.01)], 'lamp', p.x, p.y - 0.02, p.z, ry, -0.55, 0, ch);
    }
    S(boxFromCenter(x, GY + 4.5, z, 0.4, 9.0, 0.4, SURFACE.METAL, { thickness: 40 }));
  }
  // One mast down, lying across the approach. A 9 m diagonal on the ground reads
  // instantly as "something happened here" and doubles as prone cover.
  {
    const m = PR.floodMast(9, {});
    putAll(m.parts, 'metal', 19.5, GY + 0.35, 37.5, 0.7, 0, Math.PI / 2 - 0.06, 'approach');
    S(boxFromCenter(19.5 + 3.4, GY + 0.30, 37.5 + 2.9, 7.4, 0.55, 1.0, SURFACE.METAL, { thickness: 20 }));
    putAll(PR.rubble(14, 1.6, { seed: 44, big: 0.5 }), 'concrete', 19.5, GY, 37.5, 0, 0, 0, 'approach');
  }

  // ── motor pool ─────────────────────────────────────────────────────────────
  // A hardstand east of the catwalk. It exists for two reasons: it is what the
  // overlook actually looks at (the pose faces east-north-east, and 14 m of bare
  // sand out to the wire was the weakest frame in the level), and it opens a
  // third lane up the approach so the catwalk is a route to flank around rather
  // than a wall to walk under.
  apron(18, 8, 30, 34, { cell: 6.0, chunk: 'approach' });
  floorBox(18, 8, 30, 34);
  cont(23.5, 12.5, 12.19, Math.PI / 2 + 0.03);
  cont(27.5, 24.0, 6.06, 0.10);
  cont(20.0, 31.0, 6.06, Math.PI / 2 - 0.06);
  // Pipe stock on timber bearers — a stack of 40 cm cylinders reads as material
  // handling from 40 m and gives the flat hardstand a horizontal it needs.
  for (let r = 0; r < 3; r++) {
    for (let i = 0; i < 5 - r; i++) {
      putAll([cyl(0.28, 0.28, 5.6, 12)], 'rust',
        22.0 + (i + r * 0.5) * 0.58, GY + 0.42 + r * 0.5, 19.5, 0, 0, Math.PI / 2, 'approach');
    }
  }
  for (const bz of [17.2, 21.8]) {
    putAll([chamferBox(3.4, 0.24, 0.26, 0.02)], 'wood', 22.9, GY + 0.12, bz, 0, 0, 0, 'approach');
  }
  S(boxFromCenter(22.9, GY + 0.95, 19.5, 3.6, 1.9, 5.8, SURFACE.METAL, { thickness: 40 }));
  // Transformer bank behind its own little compound.
  for (const tz of [27.5, 29.6]) {
    block(25.0, GY + 0.15, tz, 2.6, 0.3, 1.6, 'concrete', SURFACE.CONCRETE, { chunk: 'approach' });
    block(25.0, GY + 1.05, tz, 2.1, 1.5, 1.25, 'metal', SURFACE.METAL, { chunk: 'approach', c: 0.03 });
    for (let i = 0; i < 7; i++) {
      putAll([chamferBox(0.06, 1.2, 0.34, 0.008)], 'metal', 26.15, GY + 1.05, tz - 0.5 + i * 0.17, 0, 0, 0, 'approach');
    }
    for (const px of [-0.6, 0, 0.6]) putAll([cyl(0.12, 0.14, 0.5, 8)], 'glass', 25.0 + px, GY + 2.05, tz, 0, 0, 0, 'approach');
  }
  putAll(PR.spool(0.9, 0.95, {}), 'metal', 19.5, GY + 0.9, 26.5, 0.9, 0, 0, 'approach');
  S(boxFromCenter(19.5, GY + 0.9, 26.5, 1.85, 1.8, 1.85, SURFACE.WOOD, { thickness: 60 }));
  bags(28.6, 17.5, 3.4, Math.PI / 2, 'approach');

  // Guard post at the gate, and the gate itself.
  block(-13.5, GY + 1.55, 47.0, 3.4, 3.1, 3.0, 'concrete', SURFACE.CONCRETE, { chunk: 'edge' });
  putAll([chamferBox(4.0, 0.22, 3.6, 0.03)], 'concrete', -13.5, GY + 3.2, 47.0, 0, 0, 0, 'edge');
  putAll([chamferBox(1.9, 1.0, 0.06, 0.01)], 'glass', -13.5, GY + 1.9, 45.48, 0, 0, 0, 'edge');
  putAll(PR.pipeRun([[-11.6, GY + 1.15, 45.3], [-4.2, GY + 1.15, 45.3]], 0.08, { seg: 6, flangeEvery: 9 }), 'paint', 0, 0, 0, 0, 0, 0, 'edge');
  S(boxFromCenter(-7.9, GY + 1.15, 45.3, 7.6, 0.2, 0.2, SURFACE.METAL, { solid: true, blocksSight: false }));

  // Spools, crates, drums — the scatter that turns a plan into a place.
  for (const [x, z, ry, ch] of [[-10.5, 27, 0.3, 'approach'], [21.5, 12.5, 1.1, 'approach'], [-3.5, -35.5, 0.6, 'bunker'], [13.5, -6.5, 2.0, 'pad']]) {
    putAll(PR.spool(0.9, 0.95, {}), 'metal', x, GY + 0.9, z, ry, 0, 0, ch);
    S(boxFromCenter(x, GY + 0.9, z, 1.85, 1.8, 1.85, SURFACE.WOOD, { thickness: 60 }));
  }
  for (const [x, z, seed, ch] of [[5.5, 24, 3, 'approach'], [-24.5, 30, 4, 'approach'], [9.5, -2.5, 5, 'pad'], [-19.5, -5.5, 6, 'pad'], [25.0, -19, 7, 'silo'], [-16, -34.5, 8, 'bunker']]) {
    const r = mulberry(seed);
    let n = 0;
    for (let i = 0; i < 4; i++) {
      const w = 0.9 + r() * 0.7, h = 0.7 + r() * 0.6;
      const px = x + (r() - 0.5) * 2.6, pz = z + (r() - 0.5) * 2.4;
      const stack = i === 3 && n > 0 ? 0.85 : 0;
      putAll(PR.crate(w, h, w * 0.9, {}), 'wood', px, GY + stack, pz, r() * 3, 0, 0, ch);
      S(boxFromCenter(px, GY + stack + h / 2, pz, w, h, w * 0.9, SURFACE.WOOD, { thickness: 22 }));
      n++;
    }
    for (let i = 0; i < 3; i++) {
      const px = x + (r() - 0.5) * 3.4, pz = z + (r() - 0.5) * 3.0;
      putAll(PR.drum({}), 'rust', px, GY, pz, r() * 3, 0, 0, ch);
      S(boxFromCenter(px, GY + 0.45, pz, 0.62, 0.9, 0.62, SURFACE.METAL, { thickness: 12 }));
    }
  }

  // Low pipe run along the west half of the bunker's south face at 1.6 m — cover
  // you shoot *under* rather than over, which is a height nothing else here
  // offers. It stops short of the control-room door: a service run that blocks
  // a doorway is the classic way to make a route look open and play closed.
  putAll(PR.pipeRun([[-25.5, 1.62, -7.6], [-11.4, 1.62, -7.6]], 0.21, { seg: 12, flangeEvery: 4.6 }), 'rust', 0, 0, 0, 0, 0, 0, 'pad');
  putAll(PR.pipeRun([[7.9, 1.62, -7.6], [11.2, 1.62, -11.4], [11.2, 1.62, -31]], 0.21, { seg: 12, flangeEvery: 5.2 }), 'rust', 0, 0, 0, 0, 0, 0, 'pad');
  for (const x of [-24.2, -20.0, -15.8, -11.8]) {
    putAll([chamferBox(0.22, 1.4, 0.22, 0.014)], 'metal', x, GY + 0.7, -7.6, 0, 0, 0, 'pad');
    S(boxFromCenter(x, GY + 0.7, -7.6, 0.24, 1.4, 0.24, SURFACE.METAL, { thickness: 24 }));
  }
  S(makeBox({ x: -25.6, y: 1.40, z: -7.85 }, { x: -11.3, y: 1.85, z: -7.35 }, SURFACE.METAL, { thickness: 4 }));
  S(makeBox({ x: 7.8, y: 1.40, z: -7.85 }, { x: 11.45, y: 1.85, z: -7.35 }, SURFACE.METAL, { thickness: 4 }));
  S(makeBox({ x: 10.95, y: 1.40, z: -31 }, { x: 11.45, y: 1.85, z: -11.0 }, SURFACE.METAL, { thickness: 4 }));
  // Everything that has to cross the doorways crosses them at 3.3 m instead.
  putAll(PR.cableTray(19.0, 0.5), 'rust', -1.5, 3.30, -7.4, 0, 0, 0, 'pad');
  putAll(PR.pipeRun([[-11.0, 3.16, -7.4], [7.6, 3.16, -7.4]], 0.11, { seg: 8, flangeEvery: 4.4 }), 'rust', 0, 0, 0, 0, 0, 0, 'pad');

  // Bollards along the apron edge.
  for (let x = -22; x <= 4; x += 3.2) {
    putAll([cyl(0.13, 0.15, 0.95, 10)], 'paint', x, GY + 0.475, 11.4, 0, 0, 0, 'pad');
    S(boxFromCenter(x, GY + 0.475, 11.4, 0.3, 0.95, 0.3, SURFACE.METAL, { thickness: 30 }));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 7 · PERIMETER
  // ═══════════════════════════════════════════════════════════════════════════

  // Chain-link only where it is seen: across the gate line and up both flanks of
  // the approach. Everywhere else a graded earth berm does the job of keeping
  // the player in without a hundred metres of alpha-tested quads.
  const chainGeos = [];
  fence(0, 50, 60, 0, [[-4.5, 4.5]]);
  fence(30, 6, 88, Math.PI / 2, []);
  fence(-31, 22, 56, Math.PI / 2, []);
  function fence(x, z, len, ry, gaps) {
    const segs = [];
    let cur = -len / 2;
    for (const [a, b] of gaps) { segs.push([cur, a]); cur = b; }
    segs.push([cur, len / 2]);
    for (const [a, b] of segs) {
      if (b - a < 0.5) continue;
      const mx = ry ? x : x + (a + b) / 2, mz = ry ? z + (a + b) / 2 : z;
      putAll(PR.fenceFrame(b - a, 2.6, { spacing: 3.2, barbed: true }), 'metal', mx, GY, mz, ry, 0, 0, 'edge');
      const g = new THREE.PlaneGeometry(b - a, 2.35, 1, 1);
      g.translate(0, 1.28, 0);
      // Six tiles a metre, two diamonds a tile — 8 cm mesh, which is what
      // 9-gauge chain-link actually is. Tile it any coarser and the fence reads
      // as a cargo net.
      const uv = g.attributes.uv;
      for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * (b - a) * 6, uv.getY(i) * 14);
      chainGeos.push(prep(g).applyMatrix4(xf(x + (ry ? 0 : (a + b) / 2), GY, z + (ry ? (a + b) / 2 : 0), ry)));
      S(boxFromCenter(mx, GY + 1.4, mz, ry ? 0.14 : b - a, 2.8, ry ? b - a : 0.14, SURFACE.METAL,
        { solid: true, blocksSight: false, thickness: 2 }));
    }
  }
  if (chainGeos.length) {
    const mesh = new THREE.Mesh(mergeGeometries(chainGeos), chainlinkMaterial());
    mesh.receiveShadow = false; mesh.castShadow = false; mesh.frustumCulled = true;
    mesh.name = 'chainlink';
    group.add(mesh);
  }

  // Berms. Seven facets rather than three, so the crest rolls instead of
  // creasing, and one collision box a side.
  const bermProfile = [[-8, 0], [-5.6, 1.5], [-3.2, 2.9], [-1.0, 3.6], [1.0, 3.6], [3.2, 2.9], [5.6, 1.5], [8, 0]];
  for (const [x, z, len, ry] of [[0, 56, 100, Math.PI / 2], [0, -48, 100, Math.PI / 2], [40, 4, 108, 0], [-40, 4, 108, 0]]) {
    const g = extrude(bermProfile, len, { color: [1.02, 0.99, 0.94] });
    putAll([g], 'sand', x, GY - 0.1, z, ry, 0, 0, 'edge');
    const sx = ry ? len : 16, sz = ry ? 16 : len;
    S(boxFromCenter(x, GY + 1.8, z, sx, 3.6, sz, SURFACE.SAND, { thickness: 900, tag: 'bounds' }));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 8 · SAND, EVERYWHERE
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // Nothing in the desert stands on a clean floor. Drifts banked against the
  // windward (south-west) face of every long wall are the cheapest possible way
  // to stop props reading as objects dropped onto a plane.
  for (const [x, z, len, ry, h] of [
    [-17.5, -7.7, 13, 0, 0.55],
    [-26.1, -20, 20, -Math.PI / 2, 0.7], [-13, 12.3, 14, Math.PI, 0.45],
    [11.5, 6.6, 11, 0, 0.5], [-21, 10.4, 11, 0, 0.5],
    [8.1, -20, 18, Math.PI / 2, 0.6], [-4, -32.1, 16, Math.PI, 0.55],
    [-20.5, 12.2, 8, Math.PI, 0.4],
  ]) {
    putAll(PR.drift(len, h, 2.6, { seed: (x * 13 + z * 7) | 0 }), 'sand', x, GY, z, ry, 0, 0);
  }

  // Gravel and spalled concrete, scattered wherever the eye is likely to be
  // pointed at the floor. It is 10–25 cm of nothing, it has no collision, and it
  // is the difference between a concrete apron and a grey plane.
  for (const [x, z, n, r, seed] of [
    [5, 3, 30, 6.5, 61], [-7, 6, 22, 5, 62], [11, -3, 20, 5, 63], [-19, 2, 18, 5, 68],
    [0, 20, 24, 7, 64], [-14, 17, 20, 6, 65], [8, 33, 18, 6, 69], [22, 20, 18, 6, 70],
    [18, -12, 22, 6, 66], [1, -24, 18, 5, 67], [-16, -12, 16, 5, 71], [4, -30, 14, 4, 72],
  ]) {
    putAll(PR.rubble(n, r, { seed, big: 0.17 }), 'concrete', x, PY - 0.02, z, 0, 0, 0);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 9 · MERGE
  // ═══════════════════════════════════════════════════════════════════════════

  let drawables = 0, tris = 0;
  for (const [key, geos] of buckets) {
    if (!geos.length) continue;
    const mat = key.split('|')[1];
    let merged;
    try { merged = mergeGeometries(geos); } catch { merged = null; }
    if (!merged) { for (const g of geos) g.dispose(); buckets.set(key, []); continue; }
    grime(merged, mat);
    merged.computeBoundingSphere();
    merged.computeBoundingBox();
    const mesh = new THREE.Mesh(merged, matFor(mat));
    mesh.name = key;
    mesh.castShadow = mat !== 'sand' || (merged.boundingBox.max.y - merged.boundingBox.min.y) > 0.6;
    mesh.receiveShadow = true;
    mesh.frustumCulled = true;
    mesh.matrixAutoUpdate = false;
    mesh.updateMatrix();
    group.add(mesh);
    drawables++;
    tris += merged.attributes.position.count / 3;
    for (const g of geos) g.dispose();
    buckets.set(key, []);
  }

  // Contact grime and windblown dust, baked per vertex. Two rules, both of them
  // observations rather than art direction: dirt collects where a surface meets
  // the ground, and sand settles on anything facing the sky.
  function grime(geo, matName) {
    const p = geo.attributes.position.array;
    const n = geo.attributes.normal.array;
    const c = geo.attributes.color.array;
    const dusty = matName !== 'glass' && matName !== 'lamp';
    for (let i = 0; i < p.length; i += 3) {
      const y = p[i + 1], ny = n[i + 1];
      const k = 0.58 + 0.42 * Math.min(1, Math.max(0, (y - 0.02) / 0.85));
      let r = c[i] * k, g = c[i + 1] * k, b = c[i + 2] * k;
      if (dusty && ny > 0) {
        // Only the last metre or so of a vertical face gets much; horizontal
        // faces get it all, which is what separates a ledge from a wall.
        const d = Math.pow(Math.max(0, ny), 1.6) * 0.30;
        r += (1.12 - r) * d; g += (1.03 - g) * d; b += (0.84 - b) * d;
      }
      c[i] = r; c[i + 1] = g; c[i + 2] = b;
    }
    geo.attributes.color.needsUpdate = true;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 10 · PRACTICAL LIGHTS
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // The sun is 24° above the horizon and coming from the north-west, which means
  // the bunker interior gets nothing but two shafts through the roof. These are
  // the emergency circuit: sodium, dim, and just enough to shape the corridor
  // without lifting it out of silhouette. Budgeted by tier because every one of
  // these is a per-fragment cost on every material in range.
  const lightBudget = [2, 3, 5, 7][G.settings.quality] || 5;
  const practicals = [];
  const LAMPS = [
    [0, 3.35, -12.5, 0xffb24a, 7.5, 11],
    [0, 3.35, -25.5, 0xffb24a, 6.0, 11],
    [-16.5, 3.20, -12.0, 0xbfe2ff, 5.0, 10],
    [-18.0, 3.30, -26.0, 0xffa838, 6.5, 12],
    [4.8, 3.20, -18.0, 0xffb24a, 4.5, 8],
    [SILO.x, 8.4, -14.0, 0xffd6a0, 9.0, 16],
    [-13.0, 3.10, -20.0, 0xffb24a, 4.0, 9],
  ];
  for (let i = 0; i < Math.min(lightBudget, LAMPS.length); i++) {
    const [x, y, z, col, intensity, dist] = LAMPS[i];
    const l = new THREE.PointLight(col, intensity, dist, 2);
    l.position.set(x, y, z);
    l.castShadow = false;
    group.add(l);
    practicals.push({ light: l, base: intensity, phase: i * 1.7, flicker: i === 4 || i === 6 });
    // The fitting itself, so the light has a visible source.
    putAll([chamferBox(0.46, 0.09, 0.16, 0.012)], 'lamp', x, y + 0.12, z, 0, 0, 0);
  }
  // The lamp geometry above went into a bucket that has already been merged, so
  // fold any late arrivals in as their own small mesh rather than losing them.
  flushLate();
  function flushLate() {
    for (const [key, geos] of buckets) {
      if (!geos.length) continue;
      let merged;
      try { merged = mergeGeometries(geos); } catch { merged = null; }
      buckets.set(key, []);
      if (!merged) continue;
      merged.computeBoundingSphere();
      const mesh = new THREE.Mesh(merged, matFor(key.split('|')[1]));
      mesh.castShadow = false; mesh.receiveShadow = false; mesh.frustumCulled = true;
      mesh.name = key + ':late';
      group.add(mesh);
      drawables++;
      tris += merged.attributes.position.count / 3;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 11 · NAVIGATION DATA FOR THE AI
  // ═══════════════════════════════════════════════════════════════════════════

  G.world.statics = statics;
  G.world.grid = buildGrid(statics);
  G.world.bounds = { min: { x: -40, y: -4, z: -48 }, max: { x: 40, y: 34, z: 58 } };

  const world = G.world;
  const cover = buildCover(world, statics);
  G.world.cover = cover;
  G.world.spawns = buildSpawns(world, cover);

  // Cover points are derived from the geometry rather than hand-placed, because
  // a hand-placed list rots the moment a prop moves 30 cm. Every solid box whose
  // top lands between knee and head height contributes points along each of its
  // four faces, offset far enough out that a body standing there is clear of it.
  // `dir` points at the thing the cover is protecting you from — i.e. back into
  // the box — which is what the AI needs to test an approach against.
  function buildCover(w, boxes) {
    const out = [];
    const probe = [];
    for (const b of boxes) {
      if (!b.solid || !b.blocksSight) continue;
      if (b.tag === 'floor' || b.tag === 'bounds' || b.tag === 'stair') continue;
      const top = b.max.y, bot = b.min.y;
      if (top - bot < 0.35) continue;                // a plate is not cover
      const sx = b.max.x - b.min.x, sz = b.max.z - b.min.z;
      if (sx < 0.55 || sz < 0.25) { if (sz < 0.55 || sx < 0.25) continue; }
      for (const [nx, nz] of [[0, 1], [0, -1], [1, 0], [-1, 0]]) {
        const along = nx !== 0 ? sz : sx;
        if (along < 0.9) continue;
        const n = Math.max(1, Math.floor(along / 1.7));
        for (let i = 0; i < n; i++) {
          const t = (i + 0.5) / n;
          let px, pz;
          if (nx !== 0) { px = (nx > 0 ? b.max.x : b.min.x) + nx * 0.66; pz = b.min.z + sz * t; }
          else { pz = (nz > 0 ? b.max.z : b.min.z) + nz * 0.66; px = b.min.x + sx * t; }
          const g = groundBelow(w, px, top + 0.9, pz, 3.2);
          if (!g) continue;
          // Everything below is measured against the floor you would actually be
          // standing on, not against y=0 — otherwise a roof parapet, which is the
          // best crouch cover on the site, filters out for being "too high".
          const rise = top - g.y;
          if (rise < 0.80 || rise > 2.30) continue;
          if (Math.abs(g.y - bot) > 0.9) continue;   // the box does not sit on that floor
          const stance = rise < 1.40 ? 'crouch' : 'stand';
          // Body clearance: nothing solid in the volume a person would occupy.
          queryAABB(w.grid, { x: px - 0.36, y: g.y + 0.12, z: pz - 0.36 },
            { x: px + 0.36, y: g.y + (stance === 'crouch' ? 1.15 : 1.75), z: pz + 0.36 }, probe);
          let blocked = false;
          for (const q of probe) { if (q.solid && q.tag !== 'floor') { blocked = true; break; } }
          if (blocked) continue;
          out.push({
            pos: { x: px, y: g.y, z: pz },
            dir: { x: -nx, y: 0, z: -nz },
            height: rise,
            stance,
          });
        }
      }
    }
    // Thin it out. Two cover points 40 cm apart are the same cover point, and a
    // fat list makes every AI query slower for nothing.
    const kept = [];
    const cell = 2.0, seen = new Map();
    for (const c of out) {
      const k = Math.floor(c.pos.x / cell) + ',' + Math.floor(c.pos.z / cell) + ','
        + Math.round(Math.atan2(c.dir.z, c.dir.x) * 2);
      if (seen.has(k)) continue;
      seen.set(k, 1);
      kept.push(c);
    }
    return kept;
  }

  // Spawns are cover points, spread by farthest-point sampling inside each zone
  // so a wave never materialises as a clump and never all in one room.
  function buildSpawns(w, cov) {
    const zones = [
      { name: 'approach', r: [-30, 14, 30, 50], n: 5 },
      { name: 'pad', r: [-28, -8, 28, 14], n: 5 },
      { name: 'bunker', r: [-27, -33, 9, -8], n: 6 },
      { name: 'silo', r: [8, -42, 31, -5], n: 5 },
      { name: 'roof', r: [-27, -33, 9, -8], n: 3, minY: 4.0 },
      { name: 'catwalk', r: [-8, -8, 18, 24], n: 2, minY: 3.0 },
    ];
    const out = [];
    for (const z of zones) {
      const pool = cov.filter((c) => c.pos.x >= z.r[0] && c.pos.x <= z.r[2]
        && c.pos.z >= z.r[1] && c.pos.z <= z.r[3]
        && (z.minY ? c.pos.y > z.minY : c.pos.y < 4.0));
      if (!pool.length) continue;
      const picked = [pool[Math.floor(pool.length * 0.5)]];
      while (picked.length < z.n && picked.length < pool.length) {
        let best = null, bestD = -1;
        for (const c of pool) {
          let d = Infinity;
          for (const p of picked) d = Math.min(d, (c.pos.x - p.pos.x) ** 2 + (c.pos.z - p.pos.z) ** 2);
          if (d > bestD) { bestD = d; best = c; }
        }
        if (!best || bestD < 9) break;
        picked.push(best);
      }
      // y matches the stub's convention: roughly torso height above the floor,
      // so a spawned enemy's centre is already clear of the ground.
      for (const p of picked) out.push({ x: p.pos.x, y: p.pos.y + 1.7, z: p.pos.z, ground: p.pos.y, zone: z.name });
    }
    return out;
  }

  // ═══════════════════════════════════════════════════════════════════════════

  engine.scene.add(group);

  if (typeof console !== 'undefined' && console.info) {
    console.info(`[level] site 9 — ${drawables} static meshes, ${tris | 0} tris, ` +
      `${statics.length} collision boxes, ${cover.length} cover points, ${G.world.spawns.length} spawns`);
  }

  let t = 0;
  return {
    group, statics,
    // The gate, looking straight up the road at the silo cap and the gantry. You
    // walk in from outside the wire; the whole facility is laid out in front of
    // you from the first frame and nothing about it is hidden.
    spawn: { x: 0, y: 1.80, z: 44 },
    spawnYaw: 0,
    cover, drawables,

    // The screenshot rig reads these instead of its own table, so they are the
    // frames this level gets judged on. Chosen the way you would choose stills
    // for a trailer rather than the way you would choose debug cameras: between
    // them they cover all three zones plus the vertical, they show the compound
    // both with the sun and against it, and at least one of them is pointed at
    // nothing but floor, because material work is invisible in a wide shot.
    //
    // The sun sits at about 24° in the north-west, so a camera at yaw ≈ 0.60
    // faces it and one at yaw ≈ −2.55 has it over its shoulder. Every pose here
    // is one or the other on purpose — a shot lit from the side at dusk is the
    // one lighting condition that flatters nothing.
    poses: {
      // Where the player actually starts: outside the wire, looking up the road.
      // The whole facility is in this one frame — chevrons, revetments, the
      // catwalk, the mast, the gantry — and none of it is hidden.
      spawn: { pos: [0, 1.80, 44], yaw: 0, pitch: -0.02 },

      // Standing in the slalom, between the two jersey chevrons: barriers
      // running diagonally out of the near right, the revetment mid-left, and
      // 44 m of open road to the compound. This is the shot that has to make you
      // want a rifle, and the barriers are there to say why you cannot just run.
      approach: { pos: [-6.5, 1.72, 36.5], yaw: 0.06, pitch: -0.03 },

      // From the catwalk at 3.7 m, three-quarters onto the whole site: the pad
      // below, the bunker and its leaning mast to the left, the silo cap and the
      // striped gantry to the right, rails in the near field for scale.
      overlook: { pos: [16, 5.42, 3.0], yaw: 0.42, pitch: -0.14 },

      // The bunker spine, looking south out of the blast-door end. Dark walls,
      // ceiling services for depth, a lit doorway at 7 m. Deliberately a few
      // degrees off-axis: a perfect one-point perspective reads as a test render.
      corridor: { pos: [0, 1.72, -15.5], yaw: 3.02, pitch: -0.02 },

      // Straight into the sun, from the middle of the pad. The sun sits behind
      // the bunker's west end at almost exactly the bearing of the leaning mast,
      // so the site's tallest landmark is a black lattice against it and the
      // catwalk cuts the frame just above the eyeline. Everything in here is
      // either a silhouette or a rim light.
      sunward: { pos: [0.5, 1.72, 9.5], yaw: 0.62, pitch: 0.13 },

      // The reverse: sun over the shoulder, raking south-east across the silo
      // cap. Full form on the collar and its hazard banding, the gantry legs
      // converging overhead, the alley and the bunker's east wall falling away
      // behind, and every shadow running back toward the lens.
      backlit: { pos: [12.6, 1.75, -25.0], yaw: -2.52, pitch: -0.02 },

      // Nothing but floor: apron bays and their joints, gravel, the cast lip of
      // the cable trench, the trays in the bottom of it and a checker plate over.
      ground: { pos: [5.5, 1.72, 5.5], yaw: -0.35, pitch: -0.62 },

      // Viewmodel frames. A weapon reads best as a dark shape against a bright
      // aperture, which is exactly what the corridor's south door is; the ADS
      // frame is down the approach lane, because that is where you would use it.
      weapon: { pos: [0.6, 1.72, -12.0], yaw: 3.05, pitch: -0.02, ads: 0 },
      ads: { pos: [-6.5, 1.72, 36.5], yaw: 0.06, pitch: -0.03, ads: 1 },

      // Extras: the two positions a player remembers the level by.
      silo: { pos: [19, 2.77, -8.5], yaw: 0.0, pitch: -0.10 },
      roof: { pos: [-13, 6.32, -10.6], yaw: 0.0, pitch: -0.12 },
    },

    update(dt) {
      t += dt;
      // A very slow pendulum on the hook block, a turning extractor, and two
      // lamps on a dying ballast. Three moving things in a dead facility is
      // exactly enough — any more and it stops reading as abandoned.
      if (hoist) { hoist.rotation.x = Math.sin(t * 0.35) * 0.035; hoist.rotation.z = Math.sin(t * 0.27 + 1.1) * 0.02; }
      if (fan) fan.rotation.y += dt * 0.55;
      for (const p of practicals) {
        if (!p.flicker) continue;
        const f = Math.sin(t * 31 + p.phase) * Math.sin(t * 7.3 + p.phase * 2);
        p.light.intensity = p.base * (0.72 + 0.28 * (f > -0.4 ? 1 : 0.15));
      }
    },
  };

  // ── local helpers ──────────────────────────────────────────────────────────

  function fanBlades(r) {
    const parts = [];
    for (let i = 0; i < 5; i++) {
      parts.push(prep(chamferBox(r * 0.9, 0.02, r * 0.34, 0.006)
        .rotateX(0.35).translate(r * 0.5, 0, 0).rotateY(i / 5 * Math.PI * 2)));
    }
    parts.push(prep(cyl(0.09, 0.09, 0.16, 8)));
    return mergeGeometries(parts);
  }

  function chainlinkMaterial() {
    // A 64² diamond weave, alpha-tested. Alpha test rather than blending so it
    // sorts correctly against everything behind it and costs nothing extra.
    const s = 128;
    const cv = document.createElement('canvas');
    cv.width = cv.height = s;
    const g2 = cv.getContext('2d');
    g2.fillStyle = '#000'; g2.fillRect(0, 0, s, s);
    g2.strokeStyle = '#fff'; g2.lineWidth = 9; g2.lineCap = 'square';
    for (let i = -s; i <= s * 2; i += s / 2) {
      g2.beginPath(); g2.moveTo(i, -2); g2.lineTo(i + s, s + 2); g2.stroke();
      g2.beginPath(); g2.moveTo(i, s + 2); g2.lineTo(i + s, -2); g2.stroke();
    }
    const tex = new THREE.CanvasTexture(cv);
    tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
    tex.anisotropy = engine.tier ? engine.tier.aniso : 4;
    return new THREE.MeshStandardMaterial({
      color: 0x8d949c, roughness: 0.62, metalness: 0.75,
      alphaMap: tex, alphaTest: 0.5, side: THREE.DoubleSide,
    });
  }
}

// Cheap value-noise fbm. Only the terrain uses it and only at build time, so a
// hash and four octaves is plenty — a real simplex here would buy nothing.
function hash2(x, y) {
  const s = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
  return s - Math.floor(s);
}
function vnoise(x, y) {
  const xi = Math.floor(x), yi = Math.floor(y);
  const xf = x - xi, yf = y - yi;
  const u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
  const a = hash2(xi, yi), b = hash2(xi + 1, yi), c = hash2(xi, yi + 1), d = hash2(xi + 1, yi + 1);
  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v;
}
function fbm(x, y) {
  let f = 0, amp = 0.5, fr = 1;
  for (let i = 0; i < 4; i++) { f += vnoise(x * fr, y * fr) * amp; amp *= 0.5; fr *= 2.03; }
  return f * 2 - 1;
}
