// Echowake -- the shared junk cards: 6 curses and 6 status cards.
//
// One IIFE that registers into DATA.cards (no top-level names). Data only: every number is an op field and the rules text is
// generated by DATA.cardHtml from `fx` and `hand`. Tests: tests/hocus_vocus_treasure.test.mjs. Ids, hero ids and behaviour are the
// contract of CONTENT_SPEC section 2; enemies and events reference these ids exactly, so nothing here may be renamed.
//
// THE TWO FAMILIES
//   CURSES (hero 'curse', type 'curse'): the song's sour notes. They come from events, Tempo Trials (the seeded `curses` mod),
//   boss relics and elite spoils, live in the deck for the rest of the run, and are always unplayable. Some are pure clutter, some
//   bite if you leave them in your hand.
//   STATUS CARDS (hero 'status', type 'status'): temporary junk that enemies shuffle into the draw or discard pile mid fight
//   (`add` enemy ops). They vanish when the combat ends (temp cards are never part of the run deck). Two of them can be played.
//
// HOW THE OPS RUN. A curse or status card is acted by the FRONT hero: `self` in its ops is whoever stands in front when the card
// resolves, and a debuff in a `hand.*` op names its target explicitly. `hand.turnEnd` ops run if the card is still in hand when the
// turn ends (before the hand is discarded); `hand.drawn` ops run when the card lands in the hand. A `hurt` op never takes a hero
// below 1 HP, so these cards wear a hero down but cannot finish one off on their own.
//
//   curse_regret     unplayable. In hand at end of turn: the front hero loses 2 HP.
//   curse_smudge     unplayable. Pure clutter (a dead draw, nothing more).
//   curse_doubt      unplayable. When drawn: the front hero gains 1 Weak.
//   curse_burden     unplayable and innate: it is always in your opening hand.
//   curse_hex        unplayable. In hand at end of turn: both heroes gain 1 Vulnerable.
//   curse_decay      unplayable. In hand at end of turn: both heroes lose 1 HP.
//
//   status_blot      unplayable and ethereal: it clogs one draw and then evaporates by itself.
//   status_tangle    cost 1, exhaust: remove Bind from both heroes (either hero can be the Bound one).
//   status_scorch    unplayable and ethereal. In hand at end of turn: the front hero loses 2 HP.
//   status_redacted  unplayable. A black bar in the hand that never leaves until the fight does.
//   status_static    cost 0, exhaust: the front hero loses 2 HP and you draw 1 card (a free cycle with a price).
//   status_wilt      unplayable. When drawn: lose 1 Energy.
//
// Curses and status cards use rarity 'token' and need no `up`, no slots and no art.c.
(() => {
  const cards = {
    // ------------------------------------------------------------------ curses
    curse_regret: {
      name: 'Regret', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 2, tgt: 'front' }] },
      art: { m: 'mirror' },
      flavor: 'You know the line you should have sung. It keeps humming it for you.',
    },
    curse_smudge: {
      name: 'Wrong Note', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      art: { m: 'ink_splash' },
      flavor: 'One sour note in the good song. Nobody remembers whose.',
    },
    curse_doubt: {
      name: 'Doubt', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { drawn: [{ op: 'status', s: 'weak', n: 1, tgt: 'front' }] },
      art: { m: 'eye' },
      flavor: 'Is that really how the song goes?',
    },
    curse_burden: {
      name: 'Burden', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable', 'innate'], fx: [],
      art: { m: 'void' },
      flavor: 'Somebody has to carry it, and the silence has chosen you.',
    },
    curse_hex: {
      name: 'Hex', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'status', s: 'vulnerable', n: 1, tgt: 'both' }] },
      art: { m: 'sigil' },
      flavor: 'A song sung backward, once, by someone who meant it.',
    },
    curse_decay: {
      name: 'Decay', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 1, tgt: 'both' }] },
      art: { m: 'poison_bloom' },
      flavor: 'The oldest notes fade first. Yours is not so far behind.',
    },

    // ------------------------------------------------------------------ status cards
    status_blot: {
      name: 'Silence', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable', 'ethereal'], fx: [],
      art: { m: 'ink_splash' },
      flavor: 'A mouthful of the Hush. It fades by itself, if you let it.',
    },
    status_tangle: {
      name: 'Tangle', hero: 'status', type: 'status', rarity: 'token', cost: 1,
      kw: ['exhaust'], fx: [{ op: 'removeStatus', s: 'bind', tgt: 'both' }],
      art: { m: 'web' },
      flavor: 'Silk around the wrist. Snip, snip, snip.',
    },
    status_scorch: {
      name: 'Scorch', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable', 'ethereal'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 2, tgt: 'front' }] },
      art: { m: 'fire' },
      flavor: 'A scrap of soul-fire, still warm and still cross.',
    },
    status_redacted: {
      name: 'Muted', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable'], fx: [],
      art: { m: 'void' },
      flavor: 'A gap where a good note used to be.',
    },
    status_static: {
      name: 'Static', hero: 'status', type: 'status', rarity: 'token', cost: 0,
      kw: ['exhaust'], fx: [{ op: 'hurt', n: 2, tgt: 'self' }, { op: 'draw', n: 1 }],
      art: { m: 'lightning' },
      flavor: 'A hair-raising crackle. Grab it and it grabs back.',
    },
    status_wilt: {
      name: 'Wilt', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { drawn: [{ op: 'energy', n: -1 }] },
      art: { m: 'petals' },
      flavor: 'A pressed flower gone brittle. Every song it touches loses a little colour.',
    },
  };

  DATA.add('cards', cards);
})();
