// Hocus Vocus: the shared junk cards: 6 curses and 6 status cards.
//
// One IIFE that registers into DATA.cards (no top-level names). Data only: every number is an op field and the rules text is
// generated by DATA.cardHtml from `fx` and `hand`. Tests: tests/hocus_vocus_treasure.test.mjs. Ids, hero ids and behaviour are the
// contract of CONTENT_SPEC section 2; enemies and events reference these ids exactly, so nothing here may be renamed (only the
// display names and flavours speak Hocus Vocus: bible 4, HV_HEROES 2.5).
//
// THE TWO FAMILIES
//   CURSES (hero 'curse', type 'curse'): the little jinxes of the feed and the stage. They come from Detours, Encores (the seeded
//   `curses` mod), Headliner Charms and Rival spoils, live in the deck for the rest of the tour, and are always unplayable. Some are
//   pure clutter, some bite if you leave them in your hand.
//   STATUS CARDS (hero 'status', type 'status'): temporary junk that enemies shuffle into the draw or discard pile mid fight
//   (`add` enemy ops). They vanish when the combat ends (temp cards are never part of the run deck). Two of them can be played.
//
// HOW THE OPS RUN. A curse or status card is acted by the LEAD hero: `self` in its ops is whoever stands in the lead when the card
// resolves, and a debuff in a `hand.*` op names its target explicitly. `hand.turnEnd` ops run if the card is still in hand when the
// turn ends (before the hand is discarded); `hand.drawn` ops run when the card lands in the hand. A `hurt` op never takes a hero
// below 1 HP, so these cards wear a hero down but cannot make one lose their voice on their own.
//
//   curse_regret     Cringe Replay: unplayable. In hand at end of turn: the lead hero loses 2 HP.
//   curse_smudge     Pitchy: unplayable. Pure clutter (a blank draw, nothing more).
//   curse_doubt      Stage Fright: unplayable. When drawn: the lead hero gains 1 Muffled.
//   curse_burden     Excess Baggage: unplayable and Opener: it is always in your opening hand.
//   curse_hex        Hot Take: unplayable. In hand at end of turn: both heroes gain 1 Exposed.
//   curse_decay      Screen Time: unplayable. In hand at end of turn: both heroes lose 1 HP.
//
//   status_blot      Glossed Over: unplayable and One Take: it clogs one draw and then fades by itself.
//   status_tangle    Untangle: cost 1, Fade: remove Tangled from both heroes (either hero can be the Tangled one).
//   status_scorch    Hot Mic: unplayable and One Take. In hand at end of turn: the lead hero loses 2 HP.
//   status_redacted  Airbrushed: unplayable. A soft pastel blur in the hand that never leaves until the fight does.
//   status_static    Live Wire: cost 0, Fade: the lead hero loses 2 HP and you draw 1 card (a free cycle with a price).
//   status_wilt      Out of Breath: unplayable. When drawn: lose 1 Breath.
//
// Curses and status cards use rarity 'token' and need no `up`, no slots and no art.c.
(() => {
  const cards = {
    // ------------------------------------------------------------------ curses
    curse_regret: {
      name: 'Cringe Replay', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 2, tgt: 'front' }] },
      art: { m: 'mirror' },
      flavor: 'Your brain plays it back at two in the morning. In slow motion. With subtitles.',
    },
    curse_smudge: {
      name: 'Pitchy', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      art: { m: 'ink_splash' },
      flavor: 'Someone in the comments said so, and now it lives in your deck.',
    },
    curse_doubt: {
      name: 'Stage Fright', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { drawn: [{ op: 'status', s: 'weak', n: 1, tgt: 'front' }] },
      art: { m: 'eye' },
      flavor: 'Cold hands, small voice. Breathe. It always passes.',
    },
    curse_burden: {
      name: 'Excess Baggage', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable', 'innate'], fx: [],
      art: { m: 'void' },
      flavor: 'Somebody has to carry it, and the van is already full.',
    },
    curse_hex: {
      name: 'Hot Take', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'status', s: 'vulnerable', n: 1, tgt: 'both' }] },
      art: { m: 'sigil' },
      flavor: 'Nobody asked for it. Everybody saw it anyway.',
    },
    curse_decay: {
      name: 'Screen Time', hero: 'curse', type: 'curse', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 1, tgt: 'both' }] },
      art: { m: 'poison_bloom' },
      flavor: 'Just one more minute. That was an hour ago.',
    },

    // ------------------------------------------------------------------ status cards
    status_blot: {
      name: 'Glossed Over', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable', 'ethereal'], fx: [],
      art: { m: 'ink_splash' },
      flavor: 'A smear of the Gloss. It wipes off by itself, if you let it.',
    },
    status_tangle: {
      name: 'Untangle', hero: 'status', type: 'status', rarity: 'token', cost: 1,
      kw: ['exhaust'], fx: [{ op: 'removeStatus', s: 'bind', tgt: 'both' }],
      art: { m: 'web' },
      flavor: 'Mic cables round your ankles. Over, under, through, and free.',
    },
    status_scorch: {
      name: 'Hot Mic', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable', 'ethereal'], fx: [],
      hand: { turnEnd: [{ op: 'hurt', n: 2, tgt: 'front' }] },
      art: { m: 'fire' },
      flavor: 'Still switched on, still very warm, and still very cross about it.',
    },
    status_redacted: {
      name: 'Airbrushed', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable'], fx: [],
      art: { m: 'void' },
      flavor: 'There was a real note here once. Now it is very, very smooth.',
    },
    status_static: {
      name: 'Live Wire', hero: 'status', type: 'status', rarity: 'token', cost: 0,
      kw: ['exhaust'], fx: [{ op: 'hurt', n: 2, tgt: 'self' }, { op: 'draw', n: 1 }],
      art: { m: 'lightning' },
      flavor: 'A crackling cable. Grab it and it grabs back.',
    },
    status_wilt: {
      name: 'Out of Breath', hero: 'status', type: 'status', rarity: 'token',
      kw: ['unplayable'], fx: [],
      hand: { drawn: [{ op: 'energy', n: -1 }] },
      art: { m: 'petals' },
      flavor: 'Too many high notes in a row. Everybody needs a sip of water.',
    },
  };

  DATA.add('cards', cards);
})();
