// Hocus Vocus: the 24 gems: six per colour with tiers 1, 1, 2, 2, 3, 3. Colour ids red, blue, green, gold stay; players read them
// as Pink, Blue, Green, Gold (DATA.COLOUR_NAME). Names come from plan/HV_WORLD_DATA.md section 3.
//
// One IIFE that registers into DATA.gems (no top-level names). Data only: gem text is generated by DATA.gemText from `mod`, except
// the one gem whose four-way effect reads better by hand (`text`). Tests: tests/hocus_vocus_treasure.test.mjs (validator, quotas,
// the power ladder, and every gem played on cards of every type, both spots, and through a real combat).
//
// HOW A GEM WORKS (DESIGN 4.6, DATA.resolveCard). A slot takes a gem of its own colour, a rainbow slot (internal id prism) takes any.
// `dmg`, `block` and `heal` add N to EVERY matching op on the card (per hit, ops inside cond and repeat and ops other gems appended
// included, hook bodies excluded); `hits` adds to the first top level dmg op; `cost` is a signed delta and tier 3 only (ignored on X
// and 0 cost cards); `draw`, `energy`, `status`, `poison`, `fx` are APPENDED to the end of the card's ops in slot order; `kw` adds and
// `kwRemove` removes keywords; `cond` gates the whole gem on the owner's spot (internal row ids front and back). A gem with nothing
// to apply to is shown grey.
//
// COLOUR IDENTITY (why each colour is what it is, and where it is safe to socket)
//   PINK  (red) offence. Lives in slots of cards that have a dmg op. Flat damage, extra hits, a life-stealing rider, a lead spot
//         power gem, and at tier 3 a card that also splashes the whole line. The flat keys (`dmg`, `hits`) do nothing on a card
//         without a dmg op, which is exactly why the slot rules only put pink on attacks.
//   BLUE  defence. Lives on cards with Block, heal or a hero status. Flat Block and healing, Feedback, Shimmy and, at tier 3, a
//         Block skill that shields the whole party. Appended `status` and `fx` work on any card; the flat `block` and `heal` keys
//         need a matching op (Lullaby Sapphire carries both, because a blue slot sits on a Block card or a healing card).
//   GREEN utility. Works on ANY card: no flat damage, Block or heal keys, only draw, Hold, cost, Breath and pick effects.
//   GOLD  wild. Works on ANY card: status seeds (Volume, Crescendo, Shimmy), gold and Vox on play, a resource amplifier, and a
//         backing spot gem that draws and shimmies. No flat keys either.
//
// THE POWER LADDER (rough "damage equivalents" per play of the card, see the model in the test): tier 1 is a solid small bonus
// worth about 2.5 to 5, tier 2 is a real upgrade worth about 5 to 10, tier 3 changes what the card is for: a strike becomes a
// sweep, a Block skill becomes a Feedback engine or a party shield, any card gets cheaper or pays Breath back, an ordinary card
// starts a Crescendo. Measured with the greedy bot (a gem in every matching slot of an 18 card deck, Act 1 and 2 Rivals): damage
// taken falls by about 9 for a tier 1 gem, 16 to 20 for tier 2 and 22 to 25 for tier 3, the ladder the value model in the test predicts.
//
// BALANCE PASS 1 (relic lab: recorded greedy fights refought at full HP with the gem socketed in four matching slots, party HP lost per
// fight as a share of max HP, against no gem). Three gems measured below the tier 1 average and were raised: Talkback Lapis (Feedback
// 1 to 2: -1.5 to -2.7), Afterglow Amber (Warm Tea 3 beside the Vox and gold: -0.1 to -2.7) and Key Change Citrine (Volume 2 beside the
// Crescendo: -1.3 to -2.3). For reference Lullaby Sapphire -2.8, Harmony Tanzanite -3.2, Monitor Sapphire -6.3, Two Step Aquamarine -6.0.
// The value model in the test now prices Crescendo (id ritual) at 7 a point (it was 10): the lab says a Crescendo 1 saves about what
// Volume 2 does.
//
// TARGETING. Appended ops with `tgt:'enemy'` make an area card ask for a target, and `tgt:'all'` never does; the one enemy op that
// could be either (Callback Rhodonite's life steal) is written `enemy` on purpose: it is a single bite and it should land on the
// enemy you chose. Fortissimo Kunzite hits `all`, so it is safe on an area card.
//
// LOCKED (Tour Bus unlocks, never tier 1): Callback Rhodonite, Harmony Tanzanite (tier 2); Showstopper Morganite, Unison Iolite,
// Deep Breath Tourmaline, Backbeat Amber (tier 3). Each colour keeps an unlocked tier 2 and tier 3 gem so every Sparkle Booth and
// Detour that asks for a colour or a tier can always answer.
(() => {
  const gems = {
    // ------------------------------------------------------------------ RED: offence
    ember_ruby: {
      name: 'Forte Rose Quartz', color: 'red', tier: 1, art: { cut: 'round' },
      mod: { dmg: 2 },
    },
    vanguard_garnet: {
      name: 'Leading Note Spinel', color: 'red', tier: 1, art: { cut: 'square' },
      mod: { cond: 'front', dmg: 3 },
    },
    twinfang_spinel: {
      name: 'Trill Tourmaline', color: 'red', tier: 2, art: { cut: 'oval' },
      mod: { hits: 1 },
    },
    bloodmoon_carnelian: {
      name: 'Callback Rhodonite', color: 'red', tier: 2, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'dmg', n: 4, tgt: 'enemy', lifesteal: true }] },
    },
    sunfall_ruby: {
      name: 'Fortissimo Kunzite', color: 'red', tier: 3, art: { cut: 'star' },
      mod: { fx: [{ op: 'dmg', n: 6, tgt: 'all' }] },
    },
    kirin_jasper: {
      name: 'Showstopper Morganite', color: 'red', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { cond: 'front', hits: 1, dmg: 3 },
    },

    // ------------------------------------------------------------------ BLUE: defence
    tidewatch_sapphire: {
      // Both flat keys on purpose: a blue slot sits on a Block card or a healing card, and this gem must work on either.
      name: 'Lullaby Sapphire', color: 'blue', tier: 1, art: { cut: 'round' },
      mod: { block: 3, heal: 2 },
    },
    thornwake_lapis: {
      name: 'Talkback Lapis', color: 'blue', tier: 1, art: { cut: 'oval' },
      mod: { status: { s: 'thorns', n: 2, tgt: 'self' } },
    },
    mirrorlake_aquamarine: {
      name: 'Two Step Aquamarine', color: 'blue', tier: 2, art: { cut: 'square' },
      mod: { block: 2, status: { s: 'dodge', n: 1, tgt: 'self' } },
    },
    springwell_tanzanite: {
      name: 'Harmony Tanzanite', color: 'blue', tier: 2, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'heal', n: 2, tgt: 'both' }] },
    },
    ironbark_sapphire: {
      name: 'Monitor Sapphire', color: 'blue', tier: 3, art: { cut: 'star' },
      mod: { block: 3, status: { s: 'thorns', n: 4, tgt: 'self' } },
    },
    sanctum_iolite: {
      name: 'Unison Iolite', color: 'blue', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { fx: [{ op: 'block', n: 6, tgt: 'both' }] },
    },

    // ------------------------------------------------------------------ GREEN: utility (works on any card)
    quickthought_emerald: {
      name: 'Sight Read Emerald', color: 'green', tier: 1, art: { cut: 'round' },
      mod: { draw: 1 },
    },
    keepsake_peridot: {
      name: 'Sustain Peridot', color: 'green', tier: 1, art: { cut: 'oval' },
      mod: { kw: ['retain'] },
    },
    evergreen_jade: {
      name: 'Evergreen Jade', color: 'green', tier: 2, art: { cut: 'square' },
      mod: { draw: 1, kwRemove: ['exhaust'] },
    },
    scholars_malachite: {
      name: 'Rewind Malachite', color: 'green', tier: 2, art: { cut: 'drop' },
      mod: { fx: [{ op: 'pick', from: 'discard', n: 1, then: 'toHand' }] },
    },
    featherlight_emerald: {
      name: 'Falsetto Emerald', color: 'green', tier: 3, art: { cut: 'star' },
      mod: { cost: -1 },
    },
    wellspring_tourmaline: {
      name: 'Deep Breath Tourmaline', color: 'green', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { energy: 1 },
    },

    // ------------------------------------------------------------------ GOLD: wild (works on any card)
    sunwake_topaz: {
      name: 'Turn It Up Topaz', color: 'gold', tier: 1, art: { cut: 'round' },
      mod: { status: { s: 'might', n: 1, tgt: 'self' } },
    },
    coinluck_citrine: {
      name: 'Tip Jar Citrine', color: 'gold', tier: 1, art: { cut: 'oval' },
      mod: { fx: [{ op: 'gold', n: 4 }] },
    },
    inkwell_amber: {
      name: 'Afterglow Amber', color: 'gold', tier: 2, art: { cut: 'square' },
      mod: { fx: [{ op: 'ink', n: 1 }, { op: 'gold', n: 2 }, { op: 'status', s: 'regen', n: 3, tgt: 'self' }] },
    },
    heartflame_topaz: {
      // Four conditions read badly, so this one carries its own text. A hero only ever holds the resource of their own
      // (Bloom, Groove, Reverb or Rumble), so exactly one of the four ops can fire, and only once that resource is above zero.
      name: 'Heartstrings Topaz', color: 'gold', tier: 2, art: { cut: 'drop' },
      text: 'If you hold Bloom, Groove, Reverb or Rumble, gain 2 more of it.',
      mod: {
        fx: [
          { op: 'cond', if: { status: { s: 'bloom' } }, then: [{ op: 'status', s: 'bloom', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'sumi' } }, then: [{ op: 'status', s: 'sumi', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'ward' } }, then: [{ op: 'status', s: 'ward', n: 2, tgt: 'self' }] },
          { op: 'cond', if: { status: { s: 'charge' } }, then: [{ op: 'status', s: 'charge', n: 2, tgt: 'self' }] },
        ],
      },
    },
    solstice_citrine: {
      name: 'Key Change Citrine', color: 'gold', tier: 3, art: { cut: 'star' },
      mod: { status: { s: 'ritual', n: 1, tgt: 'self' }, fx: [{ op: 'status', s: 'might', n: 2, tgt: 'self' }] },
    },
    dusklight_amber: {
      name: 'Backbeat Amber', color: 'gold', tier: 3, art: { cut: 'drop' }, locked: true,
      mod: { cond: 'back', draw: 2, status: { s: 'dodge', n: 1, tgt: 'self' } },
    },
  };

  DATA.add('gems', gems);
})();
