#!/usr/bin/env node
// Dumps every player-facing id of the content registries with its current name and text, as markdown (stdout) or JSON (--json).
//   node tools/hocus_vocus/inventory.mjs > hocus_vocus/plan/inventory.md
// Used by the re-theme plan and by plan_check.mjs (does the plan cover every id?).
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const { boot } = await import(path.join(here, '..', '..', 'tests', 'hocus_vocus_lib.mjs'));
const g = boot({ only: ['util', 'data', 'data_cards_shared', 'data_cards_hanae', 'data_cards_kuro', 'data_cards_raiga', 'data_cards_suzu', 'data_enemies_1', 'data_enemies_2', 'data_enemies_3', 'data_events', 'data_gems', 'data_meta', 'data_relics', 'data_text'] });
const D = g.DATA;
const REG = ['heroes', 'cards', 'enemies', 'relics', 'gems', 'events', 'achievements', 'trials', 'lore', 'tiles', 'brushes', 'keywords', 'statuses'];
const one = (s) => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
const card = (id, c) => {
  let text = '';
  try { text = D.cardText ? D.cardText(id) : ''; } catch (e) { text = ''; }
  return { id, name: c.name, hero: c.hero, type: c.type, rarity: c.rarity, cost: c.cost, text: one(text), flavor: one(c.flavor) };
};
const out = {};
for (const reg of REG) {
  const R = D[reg] || {};
  out[reg] = Object.keys(R).map((id) => {
    const v = R[id];
    if (reg === 'cards') return card(id, v);
    if (reg === 'enemies') return { id, name: v.name, title: v.title, tier: v.tier, size: v.size, chapter: v.chapter, lore: one(v.lore), moves: Object.keys(v.moves || {}), phases: (v.phases || []).map((p) => one(p.say)) };
    if (reg === 'events') return { id, title: v.title, chapters: v.chapters, text: one(v.text), choices: (v.choices || []).map((c) => ({ label: one(c.label), cost: one(c.cost) })) };
    if (reg === 'lore') return { id, title: v.title, text: one(Array.isArray(v.text) ? v.text.join(' ') : v.text), lines: v.lines ? Object.fromEntries(Object.entries(v.lines).map(([k, a]) => [k, a])) : undefined };
    return Object.assign({ id }, Object.fromEntries(Object.entries(v).filter(([, x]) => typeof x === 'string' || typeof x === 'number').map(([k, x]) => [k, typeof x === 'string' ? one(x) : x])));
  });
}
out.tips = Array.isArray(D.tips) ? D.tips : Object.values(D.tips || {}).map((x) => (typeof x === 'string' ? x : x.text));
if (process.argv.includes('--json')) { console.log(JSON.stringify(out)); process.exit(0); }
const md = [];
md.push('# Inventory of every player-facing id (generated by tools/hocus_vocus/inventory.mjs)\n');
for (const reg of REG.concat(['tips'])) {
  const rows = out[reg] || [];
  md.push(`## ${reg} (${rows.length})\n`);
  if (reg === 'tips') { rows.forEach((t, i) => md.push(`- tip ${i + 1}: ${one(t)}`)); md.push(''); continue; }
  if (reg === 'cards') { md.push('| id | name | hero | type | rarity | cost | rules text | flavour |', '|---|---|---|---|---|---|---|---|'); rows.forEach((r) => md.push(`| ${r.id} | ${r.name} | ${r.hero} | ${r.type} | ${r.rarity} | ${r.cost} | ${r.text} | ${r.flavor} |`)); md.push(''); continue; }
  if (reg === 'enemies') { md.push('| id | name | title | tier | size | verse | lore | moves | phase lines |', '|---|---|---|---|---|---|---|---|---|'); rows.forEach((r) => md.push(`| ${r.id} | ${r.name} | ${r.title || ''} | ${r.tier} | ${r.size} | ${r.chapter} | ${r.lore} | ${r.moves.join(', ')} | ${r.phases.join(' / ')} |`)); md.push(''); continue; }
  if (reg === 'events') { rows.forEach((r) => md.push(`- **${r.id}** (verses ${JSON.stringify(r.chapters)}): ${r.title}. ${r.text} Choices: ${r.choices.map((c) => `[${c.label}${c.cost ? ' | ' + c.cost : ''}]`).join(' ')}`)); md.push(''); continue; }
  if (reg === 'lore') { rows.forEach((r) => md.push(`- **${r.id}**: ${r.title}. ${r.text ? r.text.slice(0, 300) : ''}${r.lines ? ' LINES: ' + JSON.stringify(r.lines).slice(0, 400) : ''}`)); md.push(''); continue; }
  rows.forEach((r) => md.push('- ' + JSON.stringify(r)));
  md.push('');
}
console.log(md.join('\n'));
