// The 3D view's juice table for every action the 2D `FX` table has and the hand-written 3D one (client3d/fx.ts) does not: read from the 2D
// table (colours, count, speed, lift, the sound, the shake), so every action bursts in 3D the way it does in 2D. Writes src/client3d/fx-table.ts.
//   npx tsx scripts/gen-fx3d.ts          (a test fails when an action has no 3D burst: run this, commit the file)

import { readFileSync, writeFileSync } from 'node:fs';
import { ACTIONS } from '../src/shared/actions';
import { PAL } from '../src/shared/palette';

const src = readFileSync(new URL('../src/client/juice/fx.ts', import.meta.url), 'utf8');
const a = src.indexOf('const FX = {') + 'const FX = '.length, b = src.indexOf('} satisfies Record<Action, FxSpec>');
const table = new Function('C', `return ${src.slice(a, b + 1)}`)(PAL) as Record<string, { sfx: string; burst: { colors: number[]; count: number; speed: number; up?: boolean; gravity?: number }; shake: { px: number } }>;

const hand = readFileSync(new URL('../src/client3d/fx.ts', import.meta.url), 'utf8');
const have = new Set([...hand.matchAll(/^    ([a-zA-Z]+): \{ colors:/gm)].map((m) => m[1]));
const hex = (n: number) => `0x${n.toString(16).padStart(6, '0')}`;
const r1 = (n: number) => Math.round(n * 10) / 10;
const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));

const lines: string[] = [];
for (const act of ACTIONS) {
    if (have.has(act)) continue;
    const s = table[act];
    if (!s) throw new Error(`no 2D burst for ${act}`);
    const bu = s.burst;
    const speed = r1(bu.speed / 22), up = r1((bu.up ? 4.4 : 2.6) * clamp(bu.speed / 60, 0.6, 1.6)), size = bu.count > 20 ? 1.2 : bu.count > 8 ? 1 : 0.8;
    lines.push(`    ${act}: { colors: [${bu.colors.map(hex).join(', ')}], n: ${Math.round(bu.count * 1.6)}, speed: ${speed}, up: ${up}, size: ${size}, sfx: '${s.sfx}', shake: ${Math.round(s.shake.px * 0.027 * 1000) / 1000} },`);
}
writeFileSync(new URL('../src/client3d/fx-table.ts', import.meta.url), `// GENERATED by scripts/gen-fx3d.ts from the 2D juice table: the 3D bursts of every action fx.ts does not write by hand. Do not edit.
import type { FxDef } from './fx';

export const FX_GENERATED: Record<string, FxDef> = {
${lines.join('\n')}
};
`);
console.log(`${lines.length} generated, ${have.size} by hand, ${ACTIONS.length} actions`);
