// Regenerates palette.gpl (GIMP/Lospec format) from src/shared/palette.ts so the repo's
// ComfyUI sprite pipeline can snap generated art to our colours:
//   python tools/comfyui/make_sprite.py "<subject>" --name x --palette awesome_farm/palette.gpl
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('../src/shared/palette.ts', import.meta.url), 'utf8');
const rows = [...src.matchAll(/\['(.)',\s*'(\w+)',\s*0x([0-9a-f]{6})\],\s*\/\/\s*(.*)/gi)];
if (!rows.length) throw new Error('no palette rows found in palette.ts');

const lines = rows.map(([, ch, name, hex]) => {
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16));
    return `${String(r).padStart(3)} ${String(g).padStart(3)} ${String(b).padStart(3)}\t${name} (${ch})`;
});
writeFileSync(new URL('../palette.gpl', import.meta.url),
    `GIMP Palette\nName: Awesome Farm\nColumns: 5\n# Generated by scripts/palette-gpl.mjs from src/shared/palette.ts — edit that file, not this one.\n${lines.join('\n')}\n`);
console.log(`palette.gpl: ${rows.length} colours`);
