// Card icons for EMBERKIN, authored here and written out as spritegrid JSON.
//
// One 20×20 glyph per card. They live in one file rather than 34 hand-typed
// JSON files because they share a construction and want to be compared side by
// side while you draw them: same weight of outline, same light from the upper
// left, same two-tone body plus one highlight. The palette is per-glyph so a
// Tide card can be blue and an Ember one orange without a shared ramp forcing
// everything to the same hue.
//
//   node tools/spritegrid/cardicons.mjs            # write emberkin/art/cards/*.json
//   node tools/spritegrid/cardicons.mjs --sheet    # …and a contact sheet to look at
//
// Legend used by every glyph below:
//   .  transparent      K  outline (near-black, one tone for every icon)
//   d  darkest body     m  mid body        b  bright body      h  highlight
//   a  accent (a second material — metal, bone, cloth)
//   A  bright accent    s  shadow inside the silhouette
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { validate, raster, sheet, encodePNG } from './render.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(REPO, 'emberkin', 'art', 'cards');

// One outline colour across the set is what makes a mixed hand look like a set.
const K = '#1b1220';

/** Palettes by material, so the glyphs read as fire, water, wood, metal… */
const P = {
  ember:  { K, d: '#7a1e12', m: '#c8451c', b: '#ff8a2b', h: '#ffd98a', a: '#4a3550', A: '#8f7aa8', s: '#5a1410' },
  tide:   { K, d: '#12406b', m: '#1f74b0', b: '#46b6e8', h: '#c8f2ff', a: '#3d3350', A: '#8f7aa8', s: '#0e3055' },
  verdant:{ K, d: '#1c4a24', m: '#2f8438', b: '#63c martin', h: '#d2f5a0', a: '#5d4436', A: '#9c7a5c', s: '#143a1c' },
  spark:  { K, d: '#6b5210', m: '#c39a18', b: '#ffe14d', h: '#fffbcf', a: '#3d3350', A: '#8f7aa8', s: '#4d3a0c' },
  gloom:  { K, d: '#2c1c46', m: '#553087', b: '#8f5fd0', h: '#d9b8ff', a: '#3a2a30', A: '#7c6470', s: '#1f1333' },
  stone:  { K, d: '#3c3340', m: '#6b6270', b: '#9d94a4', h: '#d6cfdc', a: '#4a3550', A: '#8f7aa8', s: '#2b242f' },
  steel:  { K, d: '#33303f', m: '#6f6c82', b: '#a8a5bd', h: '#e6e4f2', a: '#7a4a20', A: '#c08444', s: '#26232f' },
  flesh:  { K, d: '#6b1730', m: '#b32a45', b: '#e8546a', h: '#ffb3bd', a: '#4a3550', A: '#8f7aa8', s: '#500f22' },
  gold:   { K, d: '#7a5410', m: '#c69320', b: '#ffc94d', h: '#fff0b8', a: '#4a3550', A: '#8f7aa8', s: '#5c3d0a' },
};
P.verdant.b = '#63c14a';        // typo guard: keep the ramp honest
// Bag items borrow the same materials. A root is wood with fire on it, so its
// accent is the ember ramp rather than the usual violet.
P.root = { K, d: '#4a3320', m: '#6b4a2c', b: '#8f6a3f', h: '#c49a63',
           a: '#c8451c', A: '#ff8a2b', s: '#33230f' };

/**
 * A seed-orb. A sphere is the one shape a formula draws better than a hand
 * does: the band across the middle is the seam the shell opens on, and the
 * light is thrown from the upper left like everything else in the set.
 */
const orbArt = () => {
  const R = 9.4, cx = 9.5, cy = 9.5;
  const rows = [];
  for (let y = 0; y < 20; y++) {
    let row = '';
    for (let x = 0; x < 20; x++) {
      const dx = x + .5 - cx, dy = y + .5 - cy, d = Math.hypot(dx, dy);
      if (d > R) { row += '.'; continue; }
      if (d > R - 1.3) { row += 'K'; continue; }
      if (y === 9) { row += 'K'; continue; }
      if (y === 10) { row += 'a'; continue; }
      // Shade off the sphere's own normal, not off a straight diagonal: a
      // linear ramp across a circle bands into stripes, which is what the
      // first pass at these looked like.
      const nx = dx / R, ny = dy / R;
      const nz = Math.sqrt(Math.max(0, 1 - nx * nx - ny * ny));
      const L = 1 / Math.sqrt(.5 * .5 + .5 * .5 + .8 * .8);
      const l = (nx * -.5 + ny * -.5 + nz * .8) * L;
      row += l > .93 ? 'h' : l > .74 ? 'b' : l > .42 ? 'm' : 'd';
    }
    rows.push(row);
  }
  return rows.join('\n');
};

/**
 * Every glyph, 20 rows of 20. Drawn to sit inside an 18px circle so the card's
 * art window can crop to a disc without clipping anything that matters.
 */
/**
 * Every glyph, 20 rows of 20.
 *
 * Rules that keep a mixed hand looking like one set, learned the hard way from
 * a first pass where everything came out looking like a pendant:
 *   · the silhouette has to be readable filled solid black — if it needs the
 *     shading to be legible, it is the wrong shape
 *   · fill the frame; a 10px shape floating in 20px reads as a trinket
 *   · outline the outside only. An inner ring of dark tone punches a hole and
 *     turns a flame into a locket
 *   · light from the upper left, always: h on the top-left face, d on the
 *     bottom-right, m in between
 */
const ICONS = {
  // ---- edges: something sharpened, about to be swung ----------------------
  edge: ['steel', `
................KK..
...............KhbK.
..............KhbmK.
.............KhbmdK.
............KhbmdKK.
...........KhbmdK...
..........KhbmdK....
.........KhbmdK.....
........KhbmdK......
.......KhbmdK.......
......KhbmdK........
.....KhbmdK.........
....KKbmdK..........
...KaAAaK...........
..KaAaaK............
..KaaaK.............
.KAaK...............
.KaK................
.KK.................
....................`],
  whet: ['stone', `
....................
.................KK.
................KhbK
...............KhbmK
..............KhbmdK
.............KhbmdK.
............KhbmdK..
...........KhbmdK...
..........KhbmdK....
.........KKmdKK.....
....KKKKKKKKKKKK....
...KhbbbbbbbbbmdK...
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KdmmmmmmmmmmdK...
....KKKKKKKKKKKK....
....KaaK....KaaK....
....KaaK....KaaK....
....KKKK....KKKK....
....................`],
  killedge: ['flesh', `
.........KK.........
........KhbK........
........KhbK........
.......KhbmK........
.......KhbmK........
......KhbmdK........
......KhbmdK...KK...
.....KhbmdK...KhbK..
.....KhbmdK..KhbmK..
....KKbmdKK.KhbmdK..
...KaAAAAaKKhbmdK...
...KaaaaaaKhbmdK....
....KKaaKKKbmdK.....
.....KaaK.KmdK......
.....KaaK.KdK.......
.....KaaK.K.........
.....KKKK...........
....................
....................
....................`],
  reaper: ['gloom', `
...KKKKKKKKKKKK.....
..KhbbbbbbbbbmdK....
.KhbmmmmmmmmmmdK....
KhbmmdKKKKKKKKKK....
KhbmdK..............
KbmdK...............
KmdK................
KdK.................
KK......KaK.........
........KAK.........
........KaK.........
........KAK.........
........KaK.........
........KAK.........
........KaK.........
........KAK.........
.......KKaKK........
.......KaaaK........
.......KaaaK........
........KKK.........`],
  soulfang: ['gloom', `
..KKK........KKK....
.KhbmK......KhbmK...
.KhbmK......KhbmK...
.KhbmdK....KhbmdK...
.KhbmdK....KhbmdK...
.KhbmdK....KhbmdK...
..KbmdK....KbmdK....
..KbmdK....KbmdK....
..KbmdK....KbmdK....
...KbmK....KbmK.....
...KbmK....KbmK.....
....KmK....KmK......
....KmK....KmK......
.....KK....KK.......
....................
....KaAAAAAAaK......
...KaAaaaaaaAaK.....
....KaaaaaaaaK......
.....KKKKKKKK.......
....................`],
  bloodedge: ['flesh', `
...............KK...
..............KhbK..
.............KhbmK..
............KhbmdK..
...........KhbmdK...
..........KhbmdK....
.........KhbmdK.....
........KhbmdK......
.......KhbmdK.......
......KhbmdK........
.....KKbmdK.........
....KaAAaK..........
....KaaaK...........
.....KKK............
....................
..KdK.....KdK.......
.KdmbK...KdmbK......
.KmbhK...KmbhK......
..KbK.....KbK.......
...K.......K........`],
  kindle: ['ember', `
..........KK........
.........KhbK.......
.........KhbK.......
........KhbmK.......
.......KhbmmK.......
......KhbmmdK.......
.....KhbmmmdK.......
....KhbmmmmdK.......
...KhbmmmmmdKK......
..KhbmmmmmmmbdK.....
..KbmmmmmmmmmdK.....
..KbmmmmmmmmmdK.....
..KdbmmmmmmmmdK.....
...KdbmmmmmmdK......
....KdbmmmmdK.......
.....KdbmmdK........
......KddK..........
.......KK...........
....................
....................`],
  rootbind: ['verdant', `
....................
...KK..........KK...
..KhbK........KbmK..
..KhbmKKKKKKKKdbmK..
...KhbmmmmmmmmmmdK..
....KKKKKKKKKKKKK...
.......KaAAaK.......
.......KaAaaK.......
.......KaAAaK.......
.......KaAaaK.......
.......KaAAaK.......
.......KaAaaK.......
....KKKKKKKKKKKKK...
...KhbmmmmmmmmmmdK..
..KhbmKKKKKKKKdbmK..
..KhbK........KbmK..
...KK..........KK...
....................
....................
....................`],
  // ---- guard: something between you and the hit --------------------------
  guard: ['steel', `
...KKKKKKKKKKKKKK...
..KhhbbbbbbbbbbmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmKaAaKmmmdK..
..KhbmmmKaAaKmmmdK..
..KhbmmmKaAaKmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
....KhbmmmmmmmdK....
.....KhbmmmmmdK.....
......KhbmmmdK......
.......KhbmdK.......
........KhdK........
.........KK.........
....................
....................`],
  hunker: ['stone', `
....................
....KKKKKKKKKK......
...KhbbbbbbbmdK.....
..KhbmmmmmmmmmdK....
..KhbmmmmmmmmmdK....
..KhbmmKaAaKmmdK....
..KhbmmKaAaKmmdK....
..KhbmmmmmmmmmdK....
...KhbmmmmmmmdK.....
....KhbmmmmmdK......
.....KhbmmmdK.......
......KKKKKK........
....................
..KKKKKKKKKKKKKK....
.KaAAAAAAAAAAAAaK...
.KaaaaaaaaaaaaaaK...
.KKKKKKKKKKKKKKKK...
....................
....................
....................`],
  ironhide: ['steel', `
..KKKKKKKKKKKKKK....
.KhhbbbbbbbbbbmdK...
.KhbmKKKKKKKKmmdK...
.KhbmKaAAAAaKmmdK...
.KhbmKaAaaaAKmmdK...
.KhbmKaAAAAaKmmdK...
.KhbmKKKKKKKKmmdK...
.KhbmmmmmmmmmmmdK...
.KhbmmmmmmmmmmmdK...
..KhbmmmmmmmmmdK....
..KhbmmmmmmmmmdK....
...KhbmmmmmmmdK.....
....KhbmmmmmdK......
.....KhbmmmdK.......
......KhbmdK........
.......KhdK.........
........KK..........
....................
....................
....................`],
  shieldwall: ['steel', `
.KKKKKKKK..KKKKKKKK.
KhhbbbbmdKKhhbbbbmdK
KhbmmmmmdKKhbmmmmmdK
KhbmKaAKdKKhbmKaAKdK
KhbmKaAKdKKhbmKaAKdK
KhbmmmmmdKKhbmmmmmdK
KhbmmmmmdKKhbmmmmmdK
.KhbmmmmdK.KhbmmmmdK
.KhbmmmdK...KhbmmmdK
..KhbmdK.....KhbmdK.
...KhbK.......KhbK..
....KK.........KK...
....................
.KKKKKKKKKKKKKKKKKK.
KaAAAAAAAAAAAAAAAAaK
KaaaaaaaaaaaaaaaaaaK
.KKKKKKKKKKKKKKKKKK.
....................
....................
....................`],
  bulwark: ['gold', `
..KKKKKKKKKKKKKKKK..
.KhhbbbbbbbbbbbbmdK.
.KhbmmmmmmmmmmmmmdK.
.KhbmmKKKKKKKKmmmdK.
.KhbmmKaAAAAaKmmmdK.
.KhbmmKaAaaaAKmmmdK.
.KhbmmKaAAAAaKmmmdK.
.KhbmmKKKKKKKKmmmdK.
.KhbmmmmmmmmmmmmmdK.
..KhbmmmmmmmmmmmmdK.
..KhbmmmmmmmmmmmdK..
...KhbmmmmmmmmmdK...
....KhbmmmmmmmdK....
.....KhbmmmmmdK.....
......KhbmmmdK......
.......KhbmdK.......
........KhdK........
.........KK.........
....................
....................`],
  thornmail: ['verdant', `
...K.....K.....K....
..KbK...KbK...KbK...
.KKmKKKKKmKKKKKmKK..
KhbbbbbbbbbbbbbbmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmKaAAAaKmmmmdK.
KhbmmmKaAaaAKmmmmdK.
KhbmmmKaAAAaKmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
.KhbmmmmmmmmmmmmdK..
..KhbmmmmmmmmmmdK...
...KhbmmmmmmmmdK....
....KKmKKKKKmKK.....
.....KbK...KbK......
......K.....K.......
....................
....................
....................`],
  wardstance: ['spark', `
.........KK.........
........KhbK........
..KKKKKKKbmKKKKKKK..
.KhbbbbbbbmbbbbbmdK.
.KhbmmmmmmmmmmmmmdK.
.KhbmKKKKKKKKKKmmdK.
.KhbmKaAAAAAAaKmmdK.
.KhbmKaAaaaaaAKmmdK.
.KhbmKaAAAAAAaKmmdK.
.KhbmKKKKKKKKKKmmdK.
.KhbmmmmmmmmmmmmmdK.
..KhbmmmmmmmmmmmdK..
...KhbmmmmmmmmmdK...
....KhbmmmmmmmdK....
.....KhbmmmmmdK.....
......KhbmmmdK......
.......KhbmdK.......
........KhdK........
.........KK.........
....................`],
  // ---- attack buffs: heat under the whole fight --------------------------
  focus: ['spark', `
....................
....................
.....KKKKKKKKKK.....
...KKhbbbbbbbbmKK...
..KhbmmmmmmmmmmmdK..
.KhbmmmmKKKKmmmmmdK.
KhbmmmmKaAAaKmmmmmdK
KhbmmmKaAAAAaKmmmmdK
KhbmmmKaAKKAaKmmmmdK
KhbmmmKaAKKAaKmmmmdK
KhbmmmKaAAAAaKmmmmdK
KdbmmmmKaAAaKmmmmmdK
.KdbmmmmKKKKmmmmmdK.
..KdbmmmmmmmmmmmdK..
...KKdbbbbbbbbdKK...
.....KKKKKKKKKK.....
....................
....................
....................
....................`],
  whetstone: ['stone', `
....................
....KKKKKKKKKKKK....
...KhbbbbbbbbbmdK...
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KdbmmmmmmmmmmmdK..
...KKKKKKKKKKKKKK...
....................
.............KK.....
............KhbK....
...........KhbmK....
..........KhbmdK....
.........KhbmdK.....
........KhbmdK......
.......KKbmdK.......
......KaAAaK........
......KaaaK.........
.......KKK..........
....................`],
  fanghone: ['ember', `
.........KKK........
........KhbmK.......
........KhbmK.......
........KhbmdK......
........KhbmdK......
.........KbmdK......
.........KbmdK......
.........KbmdK......
..........KbmK......
..........KmK.......
...........KK.......
....................
..KKKKKKKKKKKKKK....
.KaAAAAAAAAAAAAaK...
.KaAaaaaaaaaaaaAK...
.KaaaaaaaaaaaaaaK...
..KKKKKKKKKKKKKK....
....................
....................
....................`],
  berserk: ['flesh', `
..KK............KK..
.KhbK..........KbmK.
.KhbmK........KdbmK.
..KhbmK......KdbmK..
...KhbmK....KdbmK...
....KhbmK..KdbmK....
.....KhbmKKdbmK.....
......KhbmbmdK......
.......KhbmdK.......
.......KKKKKK.......
.....KKhbbbmdKK.....
....KhbmmmmmmmdK....
...KhbmmhhmmmmmdK...
...KhbmmhhmmmmmdK...
...KhbmmmmmmmmmdK...
....KdbmmmmmmmdK....
.....KdbmmmmmdK.....
......KdbbbbdK......
.......KKKKKK.......
....................`],
  grit: ['stone', `
....................
.....KKKKKKKK.......
....KhbbbbbbmK......
...KhbmKKKKmmdK.....
...KhbmKaAaKmmdK....
..KhbmmKaAaKmmmdK...
..KhbmmKaAaKmmmdK...
..KhbmmKaAaKmmmdK...
..KhbmmmmmmmmmmdK...
..KhbmmmmmmmmmmdK...
...KdbmmmmmmmmdK....
....KdbmmmmmmdK.....
.....KKKKKKKKK......
....................
..KKKKKKKKKKKKKKKK..
.KaAAAAAAAAAAAAAAaK.
.KaaaaaaaaaaaaaaaaK.
.KKKKKKKKKKKKKKKKKK.
....................
....................`],
  temper: ['gold', `
.........KK.........
........KhbK........
........KhbK........
.......KhbmK........
......KhbmmK........
.....KhbmmdK........
....KhbmmmdK........
...KhbmmmmdKK.......
..KhbmmmmmmbdK......
..KbmmmmmmmmdK......
..KdbmmmmmmmdK......
...KdbmmmmmdK.......
....KdbmmmdK........
.....KddddK.........
...KKKKKKKKKKKK.....
..KaAAAAAAAAAaK.....
..KaaaaaaaaaaaK.....
..KKKKKKKKKKKKK.....
....................
....................`],
  warcry: ['gold', `
................KK..
...............KhbK.
..............KhbmK.
...KKKKKKKKKKKhbmdK.
..KhbbbbbbbbbbbmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KdbmmmmmmmmmmmdK...
..KKKKKKKKKKKhbmdK..
..............KhbmK.
...............KhbK.
................KK..
....................
....KaK....KaK......
...KaAaK..KaAaK.....
....KaK....KaK......
....................`],
  dragonheart: ['ember', `
...KKKK....KKKK.....
..KhbbbmKKhbbbmK....
.KhbmmmmmbmmmmmdK...
KhbmmmmmmmmmmmmmdK..
KhbmmKKKKKKKKmmmdK..
KhbmKaAAAAAAaKmmdK..
KhbmKaAaaaaaAKmmdK..
KhbmKaAAAAAAaKmmdK..
KhbmKKKKKKKKKKmmdK..
KhbmmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmdK...
..KhbmmmmmmmmmdK....
...KhbmmmmmmmdK.....
....KhbmmmmmdK......
.....KhbmmmdK.......
......KhbmdK........
.......KhdK.........
........KK..........
....................
....................`],
  // ---- healing and hearts ------------------------------------------------
  snack: ['verdant', `
..........KaK.......
..........KaK..KaAK.
..KKKKKK..KaK.KaAaK.
.KhbbbbmKKKaKKaaK...
KhbmmmmmmbmmmmmK....
KhbmmmmmmmmmmmmmdK..
KhbmhhmmmmmmmmmmdK..
KhbmhhmmmmmmmmmmdK..
KhbmmhmmmmmmmmmmdK..
KhbmmmmmmmmmmmmmdK..
KhbmmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmdK...
.KhbmmmmmmmmmmmdK...
..KhbmmmmmmmmmdK....
...KhbmmmmmmmdK.....
....KhbmmmmmdK......
.....KKKKKKKK.......
....................
....................
....................`],
  dewdrop: ['tide', `
.........KK.........
........KhbK........
........KhbK........
.......KhbmK........
.......KhbmdK.......
......KhbmmdK.......
.....KhbmmmmdK......
....KhbmmmmmmdK.....
....KhbmmmmmmdK.....
...KhbmhhmmmmmdK....
...KhbmhhmmmmmdK....
...KhbmmmmmmmmdK....
...KhbmmmmmmmmdK....
...KdbmmmmmmmmdK....
....KdbmmmmmmdK.....
.....KdbmmmmdK......
......KdbmmdK.......
.......KKKK.........
....................
....................`],
  vigor: ['flesh', `
...KKKK....KKKK.....
..KhbbbmKKhbbbmK....
.KhbmmmmmbmmmmmdK...
KhbmhhmmmmmmmmmmdK..
KhbmhhmmmmmmmmmmdK..
KhbmmhmmmmmmmmmmdK..
KhbmmmmmmmmmmmmmdK..
KhbmmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmdK...
..KhbmmmmmmmmmdK....
...KhbmmmmmmmdK.....
....KhbmmmmmdK......
.....KhbmmmdK.......
......KhbmdK........
.......KhdK.........
........KK..........
.......KaAK.........
......KaAAaK........
.......KaaK.........
........K...........`],
  heartroot: ['verdant', `
..KKKK....KKKK......
.KhbbbmKKhbbbmK.....
KhbmmmmmbmmmmmdK....
KhbmhhmmmmmmmmmdK...
KhbmhhmmmmmmmmmdK...
KhbmmhmmmmmmmmmdK...
KhbmmmmmmmmmmmmdK...
.KhbmmmmmmmmmmdK....
..KhbmmmmmmmmdK.....
...KhbmmmmmmdK......
....KhbmmmmdK.......
.....KhbmmdK........
......KhbdK.........
.......KaK..........
......KaAaK.........
.....KaAKAaK........
....KaAaKaAaK.......
...KaAaK.KaAaK......
...KaaK...KaaK......
....KK.....KK.......`],
  titanheart: ['gold', `
.KKKKKK....KKKKKK...
KhbbbbbmKKhbbbbbmK..
KhbmmmmmmbmmmmmmmK..
KhbmhhmmmmmmmmmmmdK.
KhbmhhmmmmmmmmmmmdK.
KhbmmhmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
.KhbmmmmmmmmmmmmdK..
..KhbmmmmmmmmmmdK...
...KhbmmmmmmmmdK....
....KhbmmmmmmdK.....
.....KhbmmmmdK......
......KhbmmdK.......
.......KhbdK........
........KdK.........
..KKKKKKKKKKKKKK....
.KaAAAAAAAAAAAAaK...
.KaaaaaaaaaaaaaaK...
..KKKKKKKKKKKKKK....`],
  kinbond: ['gold', `
..KKKK....KKKK......
.KhbbbmKKhbbbmK.....
KhbmmmmmbmmmmmdK....
KhbmhhmmmmmmmmmdK...
KhbmmhmmmmmmmmmdK...
KhbmmmmmmmmmmmmdK...
.KhbmmmmmmmmmmdK....
..KhbmmmmmmmmdK.....
...KhbmmmmmmdK......
....KhbmmmmdK.......
.....KhbmmdK........
......KhbdK.........
.......KaK..........
....KKKKaKKKK.......
...KaAAAAAAAaK......
...KaAaaaaaaAK......
...KaAAAAAAAaK......
...KaaaaaaaaaK......
...KKKKKKKKKKK......
....................`],
  // ---- draw, energy, tempo -----------------------------------------------
  quickstep: ['spark', `
.............KKKK...
............KhbbmK..
...........KhbmmdK..
..........KhbmdKK...
.........KhbmdK.....
.KKKKKKKKKhbmdK.....
KhbbbbbbbbbmdK......
KhbmmmmmmmmdK.......
KdbmmmmmmmdK........
.KKKKKKKKKK.........
....................
..KK...KK...KK......
.KhbK.KhbK.KhbK.....
.KbmK.KbmK.KbmK.....
..KK...KK...KK......
....................
....KaAAAAAAaK......
....KaaaaaaaaK......
.....KKKKKKKK.......
....................`],
  surge: ['spark', `
..........KKKK......
.........KhbbmK.....
........KhbmmdK.....
.......KhbmmdK......
......KhbmmdK.......
.....KhbmmdKKKKK....
....KhbmmdhbbbmdK...
...KhbmmdhbmmmmdK...
...KKKKKKbmmmmdK....
........KbmmmdK.....
.......KdbmmdK......
......KdbmmdK.......
.....KdbmmdK........
....KdbmmdK.........
....KKKKKK..........
....................
..KaK.KaK.KaK.KaK...
.KaAaKKaAaKaAaKaAaK.
..KaK.KaK.KaK.KaK...
....................`],
  adrenaline: ['flesh', `
.........KaK........
........KaAaK.......
.........KaK........
.......KKKaKKK......
......KhbbAbbmK.....
.....KhbmmAmmmdK....
.....KhbmmAmmmdK....
.....KhbmmAmmmdK....
.....KhbmmAmmmdK....
.....KhbmmAmmmdK....
.....KhbmmmmmmdK....
.....KhbmhhmmmdK....
.....KhbmhhmmmdK....
.....KhbmmmmmmdK....
.....KhbmmmmmmdK....
.....KdbmmmmmmdK....
......KdbmmmmdK.....
.......KKKKKK.......
....................
....................`],
  eternal: ['spark', `
..........KKKK......
.........KhbbmK.....
........KhbmmdK.....
.......KhbmmdK......
......KhbmmdK.......
.....KhbmmdKKKKK....
....KhbmmdhbbbmdK...
...KhbmmdhbmmmmdK...
...KKKKKKbmmmmdK....
........KbmmmdK.....
.......KdbmmdK......
......KdbmmdK.......
.....KdbmmdK........
....KKKKKK..........
....................
..KKKKKKKKKKKKKK....
.KaAAAAAAAAAAAAaK...
.KaAaaaaaaaaaaAaK...
.KaaaaaaaaaaaaaaK...
..KKKKKKKKKKKKKK....`],
  // ---- powers: rules that stay on the table ------------------------------
  venomcoat: ['verdant', `
.......KKKKKK.......
......KhbbbbmK......
......KhbmmmdK......
......KhbmmmdK......
.......KKmmKK.......
.....KKKKmmKKKK.....
....KhbbbbbbbbmK....
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KhbmhhmmmmmmdK...
...KhbmhhmmmmmmdK...
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KdbmmmmmmmmmdK...
....KdbmmmmmmmdK....
.....KKKKKKKKKK.....
........KaK.........
.......KaAaK........
........KaK.........
....................`],
  emberoil: ['ember', `
.......KKKKKK.......
......KhbbbbmK......
......KhbmmmdK......
......KhbmmmdK......
.......KKmmKK.......
.....KKKKmmKKKK.....
....KhbbbbbbbbmK....
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KhbmhhmmmmmmdK...
...KhbmhhmmmmmmdK...
...KhbmmmmmmmmmdK...
...KdbmmmmmmmmmdK...
....KdbmmmmmmmdK....
.....KKKKKKKKKK.....
........KaK.........
.......KaAaK........
......KaAAAaK.......
.......KaAaK........
........KaK.........`],
  twinstrike: ['steel', `
..KK............KK..
.KhbK..........KbmK.
.KhbmK........KdbmK.
..KhbmK......KdbmK..
...KhbmK....KdbmK...
....KhbmK..KdbmK....
.....KhbmKKdbmK.....
......KhbmbmdK......
.......KhbmdK.......
......KhbmbmdK......
.....KhbmKKdbmK.....
....KhbmK..KdbmK....
...KhbmK....KdbmK...
..KhbmK......KdbmK..
.KhbmK........KdbmK.
.KhbK..........KbmK.
..KK............KK..
....................
....................
....................`],
  // ---- elements: the face of a kin's own move -----------------------------
  elem_ember: ['ember', `
..........KK........
.........KhbK.......
.........KhbK.......
........KhbmK.......
.......KhbmmK.......
......KhbmmdK.......
.....KhbmmmdK.......
....KhbmmmmdK.......
...KhbmmmmmdKK......
..KhbmmmmmmmbdK.....
..KbmmmmmmmmmdK.....
..KbmmmmmmmmmdK.....
..KdbmmmmmmmmdK.....
...KdbmmmmmmdK......
....KdbmmmmdK.......
.....KdbmmdK........
......KddK..........
.......KK...........
....................
....................`],
  elem_tide: ['tide', `
.........KK.........
........KhbK........
........KhbK........
.......KhbmK........
.......KhbmdK.......
......KhbmmdK.......
.....KhbmmmmdK......
....KhbmmmmmmdK.....
....KhbmmmmmmdK.....
...KhbmhhmmmmmdK....
...KhbmhhmmmmmdK....
...KhbmmmmmmmmdK....
...KhbmmmmmmmmdK....
...KdbmmmmmmmmdK....
....KdbmmmmmmdK.....
.....KdbmmmmdK......
......KdbmmdK.......
.......KKKK.........
....................
....................`],
  elem_verdant: ['verdant', `
...............KKK..
.............KKhbmK.
...........KKhbmmdK.
.........KKhbmmmmdK.
.......KKhbmmmmmmdK.
.....KKhbmmmmmmmmdK.
....KhbmmmmmmmmmmdK.
...KhbmmmmmhmmmmmdK.
..KhbmmmmmhhmmmmmdK.
..KhbmmmmhhmmmmmmdK.
..KhbmmmhhmmmmmmdK..
..KhbmmhhmmmmmmdK...
..KdbmhhmmmmmmdK....
...KdbhmmmmmmdK.....
....KdbmmmmmdK......
.....KdbmmmdK.......
..KaaaKdbmdK........
.KaAaaaaKdK.........
KaaK.....K..........
.K..................`],
  elem_spark: ['spark', `
..........KKKK......
.........KhbbmK.....
........KhbmmdK.....
.......KhbmmdK......
......KhbmmdK.......
.....KhbmmdKKKKK....
....KhbmmdhbbbmdK...
...KhbmmdhbmmmmdK...
...KKKKKKbmmmmdK....
........KbmmmdK.....
.......KdbmmdK......
......KdbmmdK.......
.....KdbmmdK........
....KdbmmdK.........
....KKKKKK..........
....................
....................
....................
....................
....................`],
  elem_gloom: ['gloom', `
.......KKKKKK.......
.....KKhbbbbmKK.....
....KhbmmmmmmmdK....
...KhbmmmmmmmmmdK...
..KhbmmmmmmmmmmmdK..
..KhbmmmKKKKKmmmdK..
.KhbmmmKKKKKKKmmmdK.
.KhbmmKKKKKKKKKmmdK.
.KhbmmKKKKKKKKKmmdK.
.KhbmmKKKKKKKKKmmdK.
.KhbmmmKKKKKKKmmmdK.
..KhbmmmKKKKKmmmdK..
..KdbmmmmmmmmmmmdK..
...KdbmmmmmmmmmdK...
....KdbmmmmmmmdK....
.....KKdbbbbdKK.....
.......KKKKKK.......
....................
....................
....................`],
  elem_stone: ['stone', `
....................
.......KKKKKK.......
.....KKhbbbbmdKK....
...KKhbmmmmmmmmdK...
..KhbmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmmdK.
KhbmmmmhhmmmmmmmmdK.
KhbmmmhhmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KhbmmmmmmmmmmmmmmdK.
KdbmmmmmmmmmmmmmmdK.
.KdbmmmmmmmmmmmmdK..
..KdbmmmmmmmmmmdK...
...KdbmmmmmmmmdK....
....KKdbbbbbbdKK....
......KKKKKKKK......
....................
....................
....................`],
  elem_aether: ['gold', `
.........KK.........
........KhbK........
........KhbK........
.......KhbmK........
.......KhbmK........
..KK...KhbmK...KK...
.KhbKKKKhbmKKKKbmK..
.KhbmmmmhbmmmmmmdK..
..KhbmmmmbmmmmmdK...
...KhbmmmmmmmmdK....
....KhbmmmmmmdK.....
....KhbmmmmmmdK.....
...KhbmmdKdbmmdK....
..KhbmdK...KdbmdK...
..KbmdK.....KdbmK...
..KdK.........KdK...
..KK...........KK...
....................
....................
....................`],
  overkill: ['ember', `
..K..............K..
.KbK............KbK.
.KmK............KmK.
.KdKK..........KKdK.
..KhbK........KbmK..
..KhbmKKKKKKKKdbmK..
...KhbmhbbbbbmmdK...
...KhbmmmmmmmmmdK...
..KhbmmmmmmmmmmmdK..
..KhbmmKKKKKKmmmdK..
..KhbmKaAAAAaKmmdK..
..KhbmKaAaaaAKmmdK..
..KhbmKKKKKKKKmmdK..
..KhbmmmmmmmmmmmdK..
...KdbmmmmmmmmmbdK..
....KdbmmmmmmmbdK...
.....KdbmmmmmbdK....
......KdbbbbbdK.....
.......KKKKKK.......
....................`],

  // ---- bag items ---------------------------------------------------------
  // The bag used to be a list of names. These are the same 20x20 glyphs the
  // cards use, so an orb in the bag and an orb on a card are the same object.
  item_bloomorb:  ['verdant', orbArt()],
  item_gleamorb:  ['tide', orbArt()],
  item_prismorb:  ['gloom', orbArt()],
  item_salve: ['verdant', `
.......KKKKKK.......
.......KaaaaK.......
.......KaaaaK.......
......KKaaaaKK......
......KaaaaaaK......
......KKhbmmKK......
.....KhhbmmmmdK.....
....KhbbmmmmmmdK....
....KhbbmmmmmmdK....
...KhbbmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
....KhbmmmmmmmdK....
....KhbmmmmmmmdK....
.....KKdmmmmdKK.....
.......KKKKKK.......
....................
....................
....................`],
  item_greatsalve: ['tide', `
.......KKKK.........
.......KaaK.........
......KKaaKK........
......KaaaaK........
.....KKhbmmKK.......
....KhhbmmmmdK......
...KhbbmmmmmmdK.....
..KhbbmmmmmmmmdK....
..KhbmmmmmmmmmmdK...
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
.KhbmmmmmmmmmmmmdK..
..KhbmmmmmmmmmmdK...
..KhbmmmmmmmmmmdK...
...KKdmmmmmmmdKK....
.....KKKKKKKKK......
....................
....................`],
  item_revive: ['root', `
.........KK.........
........KAAK........
.......KAAAAK.......
.......KAaaAK.......
........KaaK........
........KhbK........
.......KhbmdK.......
......KhbbmmdK......
.....KhbbmmmmdK.....
....KhbmmmmmmmdK....
...KhbmmmmmmmmmdK...
...KhbmmmmmmmmmdK...
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
...KhbmmmmmmmmmdK...
....KhbmmmmmmmdK....
.....KKdmmmmmdKK....
.......KKKKKKK......
....................
....................`],
  item_elixir: ['gloom', `
.......KKKKKK.......
.......KaaaaK.......
........KaaK........
........KaaK........
.......KhbmmK.......
......KhbmmmmK......
.....KhbmmmmmmK.....
....KhbmmmmmmmmK....
...KhbmmmmmmmmmmK...
..KhbmmmhhmmmmmmdK..
..KhbmmhhhhmmmmmdK..
..KhbmmmhhmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
..KhbmmmmmmmmmmmdK..
...KhbmmmmmmmmmdK...
....KKdmmmmmmdKK....
......KKKKKKKK......
....................
....................`],
};

// ---------------------------------------------------------------- write out
const built = [];
for (const [id, [pal, art]] of Object.entries(ICONS)) {
  const rows = art.trim().split('\n').map((r) => r.replace(/\r/g, ''));
  const used = new Set();
  for (const r of rows) for (const ch of r) if (ch !== '.') used.add(ch);
  const palette = {};
  for (const ch of [...used].sort()) {
    if (!P[pal][ch]) throw new Error(`${id}: palette "${pal}" has no colour for "${ch}"`);
    palette[ch] = P[pal][ch];
  }
  const sp = { id, name: id, w: 20, h: 20, palette, rows };
  validate(sp, id);
  built.push(sp);
}

mkdirSync(OUT, { recursive: true });
for (const sp of built) {
  writeFileSync(join(OUT, `${sp.id}.json`), JSON.stringify(sp, null, 2) + '\n');
}
console.log(`wrote ${built.length} card icons → emberkin/art/cards/`);

if (process.argv.includes('--sheet')) {
  const out = process.argv[process.argv.indexOf('--sheet') + 1] || '/tmp/cardicons.png';
  const img = sheet(built, 6, 8);
  writeFileSync(out, encodePNG(img.data, img.W, img.H));
  console.log(`contact sheet → ${out}`);
}
