// Embeds the spritegrid JSON in emberkin/art/ into emberkin/index.html.
//
// The game ships as one self-contained HTML file, so the art has to live inside
// the script. Authors edit JSON (renderable, reviewable, diffable); this script
// stamps it between the ART:BEGIN / ART:END markers. Never hand-edit that block.
//
//   node tools/spritegrid/embed.mjs           # write
//   node tools/spritegrid/embed.mjs --check   # verify index.html is up to date
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { validate } from './render.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ART = join(REPO, 'emberkin', 'art');
const INDEX = join(REPO, 'emberkin', 'index.html');
const BEGIN = '/* ART:BEGIN — generated by tools/spritegrid/embed.mjs, do not edit by hand */';
const END = '/* ART:END */';

const loadDir = (dir, expect) => {
  const out = {};
  if (!existsSync(dir)) return out;
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
    const sp = JSON.parse(readFileSync(join(dir, f), 'utf8'));
    const id = sp.id || f.replace(/\.json$/, '');
    const { w, h } = validate(sp, f);
    if (expect && (w !== expect[0] || h !== expect[1])) {
      throw new Error(`${f}: expected ${expect[0]}x${expect[1]}, got ${w}x${h}`);
    }
    out[id] = { name: sp.name || id, palette: sp.palette, rows: sp.rows };
  }
  return out;
};

// Emit compactly: one row per line keeps diffs readable without bloating the file.
const emit = (group) => {
  const parts = [];
  for (const [id, sp] of Object.entries(group)) {
    const pal = Object.entries(sp.palette)
      .map(([k, v]) => `${JSON.stringify(k)}:${JSON.stringify(v)}`)
      .join(',');
    const rows = sp.rows.map((r) => JSON.stringify(r)).join(',\n');
    parts.push(`${JSON.stringify(id)}:{n:${JSON.stringify(sp.name)},p:{${pal}},r:[\n${rows}]}`);
  }
  return `{\n${parts.join(',\n')}\n}`;
};

const creatures = loadDir(ART, [40, 40]);
const tiles = loadDir(join(ART, 'tiles'), [16, 16]);
const actors = loadDir(join(ART, 'actors'));

const block = [
  BEGIN,
  `const ART_CREATURES = ${emit(creatures)};`,
  `const ART_TILES = ${emit(tiles)};`,
  `const ART_ACTORS = ${emit(actors)};`,
  END,
].join('\n');

const html = readFileSync(INDEX, 'utf8');
const a = html.indexOf(BEGIN);
const b = html.indexOf(END);
if (a < 0 || b < 0) throw new Error(`markers not found in ${INDEX}`);
const next = html.slice(0, a) + block + html.slice(b + END.length);

if (process.argv.includes('--check')) {
  if (next !== html) {
    console.error('emberkin/index.html art block is stale — run: node tools/spritegrid/embed.mjs');
    process.exit(1);
  }
  console.log(`art block up to date (${Object.keys(creatures).length} creatures, ${Object.keys(tiles).length} tiles, ${Object.keys(actors).length} actors)`);
} else {
  writeFileSync(INDEX, next);
  console.log(`embedded ${Object.keys(creatures).length} creatures, ${Object.keys(tiles).length} tiles, ${Object.keys(actors).length} actors → emberkin/index.html`);
}
